### ISSUE TITLE
Very slow translation due in-memory page swapping - Moses

### ISSUE THREAD

**Issue by davidecaroselli** [ModernMT/MMT#135]
I'm experiencing some slow-down issue in translation. It happens that the Translation Time is 6-8 time slower than expected (~7 seconds instead of 1.7 on benchmark-1.1).

The bad news: this issue is a sort of random behavior. In fact when it happens, if I stop and start again the engine, the problem could have been solved. I suspect then that there's some issue at the startup that puts Moses into a sort of "invalid" state, in which translations took more than expected.

I've already run some tests to verify that the issue is not related to the java part (the distribute infrastructure), and I have evidence that the upper layer forwards the translation requests to the JNI with the right timing: no deadlocks or delays.

After a discussion with @cidermole we suspect that the problem could be in the "dynamic SA version".
David as soon as you have any updates, you can directly report them here.

**Comment by davidecaroselli** [comment]
After a discussion with @cidermole I've run some tests to inspect this very strange behavior. Results shown that the problem is not actually an initialization issue, instead, as David suggested, it's a RAM availability issue.

I run the same test on an Amazon EC2 Instance m4.10xlarge (160 GB of RAM) and the mean translation time is 1/3 and, most important, does not change with the Engine restart.

These are the test results, for every run, I restarted MMT (`./mmt stop & ./mmt start`)

**Translation speed on m4.4xlarge (64 Gb):**
* RUN 1: `3.24s per sentence`
* RUN 2: `6.42s per sentence`
* RUN 3: `2.80s per sentence`
* RUN 4: `6.26s per sentence`

**Translation speed on m4.10xlarge (160 Gb):**
* RUN 1: `0.84s per sentence`
* RUN 2: `0.81s per sentence`
* RUN 3: `0.81s per sentence`
* RUN 4: `0.87s per sentence`

**Comment by cidermole** [comment]
Davide,

there are ways to
1. lock the mmapped pages (using `mlock()`) - in case they should be swapped out;
2. mmap them with `MAP_HUGETLB` so the file is backed by huge pages in memory (TLB friendly, i.e. quicker random access, which both LM and TM use a LOT).

I suspect that 2. happens opportunistically even without the flag, i.e. the kernel figures that we are mapping a large file that should be mapped with 2 MB pages instead of 4 kB pages. See the following output with a running b1.1 engine:

```
$ cat /proc/meminfo | grep Huge
AnonHugePages:  10086400 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

$ top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                          
 3618 dmadl     30  10  0.120t 0.087t 0.011t S  1384 62.6 828:43.40 java                             
# reports 11 GB of shared mappings
```

However, I also suspect that if there is memory fragmentation, then the kernel may be unable to provide huge pages opportunistically. Maybe not even if you ask for them.

There is a way to reserve huge pages on the kernel boot cmdline (though I suspect that won't work with EC2). The alternative is e.g. `echo 20 > /proc/sys/vm/nr_hugepages` (as early as possible after boot), see https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt

**Comment by davidecaroselli** [comment]
@cidermole very interesting analysis. Do you think is possible to change every mmap call with mmap+mlock? What would be the effort?

**Comment by davidecaroselli** [comment]
After an internal discussion, we decided that investigating a possible improvement is not a priority for now.
