### ISSUE TITLE
0.13 AdaptiveLM Pro and Cons

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#139]
This is an open discussion regarding the AdaptiveLM in 0.13.
I am trying to understand how this may impact the product.

Pro:
- up to 2 BLEU scores increase

Cons:
- More storage and Memory required during training and operation
- 25% slower training overall (100% LM only)

@davidecaroselli @cidermole @nicolabertoldi @mfederico I would like to have your opinion know if there is any other pro or cons

**Comment by nicolabertoldi** [comment]
Regarding training speed, I think that this is only because the LM (background and domain-specific are trained sequentially); probably, training in parallel could reduce training time.
A reasonable solution could be the sequential training of the domain-specific LMs and in parallel the training of the background. Probably in this way we optimize time and CPU resources.

Regarding the storage, I think the storage for all the domain-specific LM is a (rather) small percentage of the storage of the background LM, especially if the BG LM is estimated on a significant larger monolingual corpus. For instance, in our 63-domain English-Italian benchmark 1.1, the BG LM has a size of 19Gb, while the sum of all the domain-specific LMs is only 4Gb bytes      (~21% of BG LM)
Viceversa, if a few (or no) additional monolingual data are available, the storage of the domain-specific LMs is almost equal to that of the BG LM. But, in this case is likely that the LMs are quite small, as the parallel data are quite small.

@davidecaroselli @cidermole @nicolabertoldi @mfederico  @marcotrombetti

**Comment by mfederico** [comment]
On the long run I guess that big language models will be trained just once and will be updated once in a while. So big LM files could reside in a separate folder. 

@davidecaroselli @cidermole @nicolabertoldi @mfederico @marcotrombetti

**Comment by davidecaroselli** [comment]
I agree with @nicolabertoldi and @mfederico on the training issue.
Regarding other PROs I would like to add that it can be made incremental for even better performance.

On the RAM aspect, we worked a lot in the past months to increase the quality and we succeed. If the speed and memory consumption start to become a priority, we should focus on that and start to rework components in order to make them more lite and maybe even distributed. 

@cidermole @marcotrombetti @luca-mastrostefano

**Comment by cidermole** [comment]
Model size (HDD, RAM):

benchmark-1.1: 21.5 GiB total models/lm size
3.8 GiB adaptive models
17.7 GiB background.slm

CPU:

without adaptive LM: 0.6 s / sentence
with adaptive LM: 0.73 s / sentence

Quality:

Though definitely an improvement in general, it is possible that you get slightly worse translations than from a non-adapted system. This could be the case if the Context Analyzer makes a mistake and assigns a high score to the wrong domain. More probable with very short input (e.g. single sentence).

**Comment by cidermole** [comment]
If really necessary, LM training can be optimized to be much faster. In practice it is unnecessary to pass the corpus and sort n-grams twice in `lmplz`.
If we start optimizing LM training, we should also get rid of the intermediate text file (ARPA) that Roldano was discussing.

**Comment by ugermann** [comment]
Why is the ARPA file even written to disk? I always pipe the output of
lmplz into build_binary.

- Uli

On Fri, May 27, 2016 at 11:25 AM, David Madl <notifications@github.com>
wrote:

> If really necessary, LM training can be optimized to be much faster. In
> practice it is unnecessary to pass the corpus and sort n-grams twice in
> lmplz.
> If we start optimizing LM training, we should also get rid of the
> intermediate text file (ARPA) that Roldano was discussing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ModernMT/MMT/issues/139#issuecomment-222113204>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEQLOxZ0dXRoTYtJjcKbEkfo9A0ixb5vks5qFsacgaJpZM4IoMkr>
> .
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by davidecaroselli** [comment]
Trying to sum up what we have discussed about, I would say that the speed/memory issues of the AdaptiveLM do not impact so much on the overall performance, while this technology brought to MMT 2 BLEU points, a very important quality boost.

Furthermore if the speed and memory issues became a priority, they can be solved in further releases reengineering the training pipeline.

In conclusion, my opinion is that the AdaptiveLM proved to be an indispensable component of our infrastructure. I would like to close this issue for the end of this week if you all agree. If you think that we're still missing some points, please add to this discussion.

Thank you all.
