### ISSUE TITLE
handling of numerical expressions

### ISSUE THREAD

**Issue by cettolo** [ModernMT/MMT#145]
I run an experiment for assessing the effectiveness of the module that handles numerical expressions. Two MMT instances were employed: the standard MMT and a version where the module for handling numerical expressions was disabled; they were run on both the test set of the benchmark 1.1 and the benchmarck 0.3 of numerical expressions. Results show that both in terms of BLEU and of numerical expression error rate the module does not yield any gain. A detailed analysis of the behaviour of the two engines didn't reveal any specific issue that could be easily solved: sometimes the module is better in handling the "localizations" of decimal points (from "." in English to "." in Italian), sometimes not. Sometimes the problems due to the module are related to the wrong translation of the patterns, sometimes to the heuristics used for restoring the original values.
My feeling is that the module could be effective but some effort is still needed to make it working properly. Meanwhile, by default it could be disabled in order to save not advantageous processing.

**Comment by marcotrombetti** [comment]
I noticed that many numbers still get converted into 00.
This will lower the BLEU score of those segments because it is reasonable
that standard Moses is making a smaller mistake.

My hypothesis is that the numerical manager solve some problems and break
the translation in other places giving a zero net result.

I agree we have to work on it. But I also think it is important to improve
what we have.

Marco

2016-06-16 8:12 GMT+02:00 Mauro Cettolo <notifications@github.com>:

**Comment by davidecaroselli** [comment]
With commit https://github.com/ModernMT/MMT/commit/3ae98a49742a01c208ae3bbb907d324cad6ef3ac numerical expressions are replaces with "all 0s" placeholder because, for the current implementation, it seems the most "correct" way (I've discussed with @cettolo about these details).

The quality does not seem to change anyway, as Marco said, this can be a starting point that we can use to improve this technology in the future.
