### ISSUE TITLE
differences between Binary distribution and Contributor  distribution

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#156]
Using exactly the same engine (i.e. the same models and .ini files), the binary distribution and the distribution from source (for contributors) report different BLEU scores at the end of the same 'mmt evaluate' task.

By inspecting quickly code and translations, it emerges that:
1. mmt-bleu.perl is different in the two distributions;
2. some files in the two $MMT_HOME/runtime/ENGINE/evaluation/translations/MMT.raw/ directiories differ (those produced by contributor distribution seem to contain some more tokens).

**Comment by davidecaroselli** [comment]
Hi @cattoni 

having the latest release that differs from the latest master/develop commit (aka distribution from source) is perfectly normal so no worries that,  even with the same models, the engine produces slightly different translation.

Also using the same models sometimes cannot work properly: if we changed any tokenization rule,  the pipeline used during translation differs from the one used during the training, so the translation could be even worse.

Regarding the script mmt-bleu, @nicolabertoldi and @cettolo found a bug that prevented the script to works correctly in some cases, that's why the two scripts differs.

**Comment by cattoni** [comment]
Hi @davidecaroselli 
Thanks for the explanations.
So the latest release is updated much less frequently than the master/develop commit.

Concerning the mmt-bleu script, could we expect that latest release will include the (fixed) version or is this operation postponed til 0.14 release?

**Comment by davidecaroselli** [comment]
I think we will release a 0.13.x version very soon in order to include several fixes and enhancements we have done in the last month.

Anyway, if you want to be always updated with the latest fixes, I suggest that you keep your local github repo in sync with master branch and periodically rebuild the engine, that's the best option for a MMT developer. 

cheers

**Comment by cattoni** [comment]
I've tested the difference between release and master/develop commit because of our HPC cluster: on it github cannot run, so my original idea was to port the release.

Now I think that the best way is to port on Kore the same master/develop commit I use on the AWS machine (that is the one I use for development/test): in this way if the port succeds we have the same development environment.
