### ISSUE TITLE
mmt start: parameter -v does not change the verbosity level

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#158]
It appears that using the parameter "-v" in "mmt start" does not influence the verbosity level in the 

`${MMT_HOME}/runtime/${ENGINE_NAME}/logs/node.log`

file.

The only way I've found to change the verbosity level is to modify the [verbose] attribute in the

`${MMT_HOME}/engines/${ENGINE_NAME}/models/moses.ini`

file.

**Comment by nicolabertoldi** [comment]
Have you tried with “—verbose”?

**Comment by cattoni** [comment]
I've also tried "--verbosity" as reported by the online help: it doesn't work too.

The parameter "--verbose" causes an error "unrecognized arguments" -- this is consistent with the online help.

**Comment by davidecaroselli** [comment]
The `-v` option of MMT set the verbosity level of the MMT log, not Moses.
This is a design choice because, for the moment, the Moses log is incredibly verbose, even at low level. Furthermore, it lacks of a proper logging framework, the result is that the text is simply outputted to stderr without any criteria, resulting in mixed text between Moses output and MMT.

For this reason we choose to keep the original Moses INI file option independent from MMT verbosity level. In future releases we should unify and normalize the logging system between the two layers (Java and c++).

For the moment, please use the verbosity value in the moses.ini file.

**Comment by cattoni** [comment]
ok, thanks.
