### ISSUE TITLE
Help needed with context, context-file, context-array parameters

### ISSUE THREAD

**Issue by wsuphappyhour** [ModernMT/MMT#160]
Hi, 

I am trying to figure out how to correctly use context-file and context-array in API call. So far I can use context parameter and I get the desired/correct output of ModerMT:
![image](https://cloud.githubusercontent.com/assets/20355306/17437153/9ae5f298-5b24-11e6-8177-087600a404d1.png)
But when I try to use context-file or array I get simple output:
![image](https://cloud.githubusercontent.com/assets/20355306/17437178/da70ec10-5b24-11e6-9f1c-1b90f59aad74.png)
Documentation states that output should be the same as context output.
My API call  looks like:
curl "http://localhost:8045/translate?q=Patients%20with%20unresolved%20thrombus%20at%20the%20lesion%20site\u002E&context-file=beckman" | python -mjson.tool >> TEST.txt

Should the path to context-file be full path /home/matecat/ModernMT/Data/beckman?(tried all the variations with no avail)
Could you please provide 2 correct samples of context-file and context-array usage in translate API call

For time being  I am using this: echo "This is an example" | extras/translate --context-weights medtronics:1 as suggested in #137

Thanks

**Comment by davidecaroselli** [comment]
Hi @wsuphappyhour 

here's some examples that work with the data in `examples/data/train/`:

**CONTEXT ARRAY**
```
$ curl "http://localhost:8045/translate?q=world&context_array=%5B%7B%22id%22%3A%20%22europarl%22%2C%22score%22%3A1.0%7D%5D" | python -mjson.tool
```
The array sent is `[{"id": "europarl","score":1.0}]`. The current version of the API does not output back the context passed, this is a bad design choice and it will change in future release.

**CONTEXT FILE**
In order to get the context weights out of a text file you have to use the `GET context` API, you cannot use directly the Translate one. Here's an example:
```
curl "http://localhost:8045/context?local_file=/home/ubuntu/mmt/examples/data/train/europarl.en" | python -mjson.tool

{
    "data": [
        {
            "id": "europarl",
            "score": 0.99998164
        },
        {
            "id": "ibm",
            "score": 0.19798715
        },
        {
            "id": "microsoft",
            "score": 0.18271142
        }
    ],
    "status": 200
}
```

You can then reuse the context array obtained in the Translated call as previously illustrated.
