### ISSUE TITLE
mmt tune: set default iterations to 10 and add option --maximum-iterations

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#161]
Currently "mmt tune" can run up to 25 iterations and user can't reduced them.

Please limit to 10 the maximum number of iterations and add in "mmt tune" the parameter 
`--maximum-iterations`
so that user can furterly limit then.
Such parameter interfaces directly with mert-moses.pl

Thanks

**Comment by cattoni** [comment]
To be more clear: having the --maximum-iterations parameter in "mmt tune" allows users to set the maximum number of iterations to a value different from default (such value can be higher or lower than default value).

Concerning which is the appropriate value for the default number of iterations (10 or 25 or ...): esperience of people with more experience on mert issues can provide this info.
For example Mauro says that a good procedure is (1) to execute mert for a number of times (with a random component that differenciates the paths) and (2) to take the average of the weights obtained from the different mert executions.

**Comment by cettolo** [comment]
The Foster&Kuhn paper (WMT, 2009):

http://www.aclweb.org/anthology/W09-0439

analysed the instability of MERT. Successively, in:

http://www.mt-archive.info/MTS-2011-Cettolo.pdf

we proposed and experimentally compared  two methods for overcoming that issue, one of them being the weight averaging mentioned by Roldano. Randomly changing the starting point of MERT, quite large changes of the BLEU score on test sets can be observed (in our exps, even 2-3 points). In fact, it is a matter of fact that it is a good practice to have multiple MERT runs. This should be considered for MMT. Since MERT is time consuming, a tradeoff could be to run 3-5 MERT runs, each for at most 10 iterations; then, in each run look for the weights which maximize the BLEU score on the dev set and finally average them.

**Comment by cettolo** [comment]
By the way, the option of mert-moses.pl to have deterministic MERT runs is "--predictable-seeds" which "provide[s] predictable seeds to mert so that random restarts are the same on every run". If it is not specified, in general different MERT runs give different optimal weights.

**Comment by davidecaroselli** [comment]
We have implemented the option `--max-interations=X` for `./mmt tune` in commit https://github.com/ModernMT/MMT/commit/03c960e621aebf2333070f27055cb020b7ae1c3e .
We opted for keeping the original default iterations right now.

We have also added **by default** the deterministic tune, if you want to have random seeds, just use the option `--random-seeds`.
