### ISSUE TITLE
Tree-based decoding

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#166]
First of all, congratulations for this outstanding project. Creating a machine translation engine has never been this easy! The translations results are remarkable.

When translating form English into German, I've encountered some issues with verbs. If the verb consists of several parts, only the first part is translated. For example, "the door opens quickly" is translated as "Das Tor geht schnell" instead of "Das Tor geht schnell auf".Could this be due to the phrase-based model? Would a tree-based model help? Can I use treee-based decoding in MMT?

**Comment by mfederico** [comment]
Hi @mehmedes and thanks for your comment. Tree-based decoding is not an option with MMT. 
From September, we will start experimenting MMT with English-German, too.  Yes, the kind of error
you describe could be partially due to limitations of the phrase-based approach: the word "opens" aligns to two non-contiguous phrases "geht" and "auf", and during decoding only one-to-one phrases are generated. Hence, the hope is that for frequent expressions, if you have enough training data, the system contains the entire phrase-pair "opens quickly" "geht schnell auf".  Yes, tree-based decoding e.g. with a hierarchical model, could in principle solve the problem, as it would handle phrases with gaps. In this case, with a rule : X-> opens X | geht X auf 
I would suggest that we go back to this issue in a couple of months, when we will start digging into En-De translation.

**Comment by mehmedes** [comment]
Thanks for your quick reply. I’m looking forward to it. You do a great job!

I was wondering whether there could be any improvements if I increased/reduced the number of n-grams.
