### ISSUE TITLE
Unable to run example in version MMT 0.13

### ISSUE THREAD

**Issue by r0n13** [ModernMT/MMT#170]
With a fresh installation of Ubuntu and MMT, I get an error when I try to create an engine as in the example in `README.md`. This is the command and the output:

```
./mmt create en it examples/data/train/

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

ERROR Unexpected exception:
	ValueError('need more than 0 values to unpack',)
Traceback (most recent call last):
  File "./mmt", line 440, in <module>
    main()
  File "./mmt", line 406, in main
    main_create(args)
  File "./mmt", line 383, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/mmt/scripts/engine.py", line 108, in build
    free_memory = fileutils.free()
  File "/mmt/scripts/libs/fileutils.py", line 53, in free
    _, total, used, available = output.split('\n')[4].split()
ValueError: need more than 0 values to unpack
```

**Comment by davidecaroselli** [comment]
Hi @r0n13 

we found out that the functions used in file `fileutils.py` are not very stable, this has been fixed in current master branch. Can you please try replace the file `MMT/scripts/libs/fileutils.py` with this version: [fileutils.py.zip](https://github.com/ModernMT/MMT/files/494960/fileutils.py.zip) ?

Let me know if this fixed the issue,
Thank you.

Davide

**Comment by r0n13** [comment]
Thanks @davidecaroselli for the quick response. That worked! 👍

**Comment by davidecaroselli** [comment]
Great!
