### ISSUE TITLE
Big model use case

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#184]
Hi,
I successfully built an engine with 9 tmx sources totalling 23 Mio segments, and one text source (news shuffle) of 1.5 GB for monolingual extra data.
the engine folder totals 50 GB of which 15GB for the LM and 35 GB for the Sapt files.

I kept increasing the memory up to 90 GB of ram.

Never loaded the model successfully.

I am rebuilding with less data right now.

Just curious if you guys loaded such big size models and how long it takes.

**Comment by davidecaroselli** [comment]
Hi @vince62s ,
we're currently testing MMT with very large models. I think @cattoni has some results on this topic.
By the way, this is the activity we need to perform in order to make a production-ready release, so it's definitely in our roadmap.

**Comment by vince62s** [comment]
update:
I divided the data by half, leading a engine folder size of 23 GB.
Model loads perfectly but takes twice the size in memory.
I did not expect this behavior.

**Comment by vince62s** [comment]
good to know:
1) how long did it take to load the model at "start" command
2) how much ram do you have on the machine to load such a model ?

**Comment by cattoni** [comment]
I've tested such engine on a m4.10xlarge AWS machine (40 cores, 160 GB RAM):

1. "mmt start" took 10m0.3s to complete (real time of command "time");
2. after "mmt start":
- the RAM occupied by the engine was 39GB (command "free"); 
- according to the command "top", the java process took 194GB of Virtual Mem, 122GB of Resident Mem, 86GB of Shared Mem

**Comment by vince62s** [comment]
@davidecaroselli 

1) do you find it "normal" ? is this normal SAPT behavior to use much more memory than its disk space ?
2) I think you need to update the "memory" requirement in the HW home page. it's much more than 1GB for 350MB of training data.

in the end, one will need many big machines to cover a 100 pairs of languages :) 

cheers.

**Comment by davidecaroselli** [comment]
@vince62s 

Thanks for the feedback on memory requirements, we will update that info.
For the ratio between disk space / RAM space: with the new infrastructure of MMT there is no more 1-to-1 ratio.
At the moment the LM is the one that definitely takes much RAM (both because of the monolingual data, and the optimization needed for the AdaptiveLM). While the SAPT are much less greedy of RAM.
Please notice also that lots of data-structures are memory mapped, this means that the OS keep them in RAM if it has enough free space (instead of waste free space, it tends to use it as much as it can). So it can be possible that on large machines MMT will try to occupy RAM if it's free in order to speed up the computation.

Generally speaking, this release is not a low-RAM engine yet. But in the future we will work to make the system more efficient for sure!

Thank you.
