### ISSUE TITLE
Apostrophe de-Escaper for output

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#185]
Hi (it's me again :)
My first test with a big model (english to french) seems to output with no escaper at detokenization step.
egs: 
l&apos;intention
instead of
l'intention
unless there is an option to force it.
Cheers,
Vincent

**Comment by davidecaroselli** [comment]
Hi vince (again :) )!

probably you meant that the output is: **l&amp;apos;intention** instead of **l'intention**.
This is not a bug: the output of MMT is XML, in fact you can request the translation of text with html or, more in general, xml.

Because of this feature, MMT **must** escape raw text as defined in the XML standard, otherwise you won't be able do distinguish between text and xml.

e.g.
`Click the <b>red</b> <button>`, is `<button>` xml or text? - parser will consider it an *xml* tag.
`Click the <b>red</b> &lt;button&gt;`, `<button>` is text for sure

You can find more info on the in/out standard of MMT in the [Wiki API Documentation](https://github.com/ModernMT/MMT/wiki/API-Documentation#input-format).

**Comment by vince62s** [comment]
oh this was in command line ./mmt translate
are you saying this has also to be XMLed for input and output ?
thanks

**Comment by davidecaroselli** [comment]
oh yes, sorry for not mentioned it.
`mmt translate` is just a "nice interface" to MMT [Translation API](https://github.com/ModernMT/MMT/wiki/API-Documentation#translation-api), so it supports all the features of the regular MMT translate.

Event with `mmt translate` you can safely pass xml text and it will translated without problems!
