### ISSUE TITLE
Domain Names vs IDs - Inconsistency?

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#189]
MMT now allows multiple domains with the same name.
Each domain has a unique id.

This command looks ambiguous:
```
./mmt add ibm "hello Mike!" "ciao Mike!"
```

How do I make sure I am adding the data to the right domain?

I this we have 2 ways:
1 - Domain names are unique
2 - IDs are used 

Number 1 is my favorite because it is simpler for the user and it is also aligned with the way files are named in the training folder.

**Comment by davidecaroselli** [comment]
Hi @marcotrombetti,

You're right, at the moment that command seems ambiguous, in fact if it detects that there are two domains with the same name, it fails.

Having the name unique is not applicable in a real production environment: we cannot say to the user that he cannot name it's TMX "europarl" just because another user has already used that name.

The solution is: that command should prompt all the options in case of ambiguity and the user will select the right one (all the metadata of the domains will be printed).

Please note that in the API such "inconsistency" is not present because the ID is always used.

**Comment by mfederico** [comment]
What about adding a user id to the domain name?

**Comment by davidecaroselli** [comment]
@mfederico this is what we will introduce with the plugin implementation! :)

**Comment by davidecaroselli** [comment]
Update on this topic.

We haven't introduced the concept of **user** yet because we wanted to keep the MMT logic very simple and let the products interfacing with it to handle all the Authentication and Authorization  management.

In case of name ambiguity `mmt add` is now printing a message alerting this situation and let the user choose between ids. For example:

```bash
$ ./mmt add europarl "hello Mike!" "ciao Mike!"
ERROR Illegal Argument: ambiguous domain name "europarl", choose one of the following ids: [1, 4]

$ ./mmt add 4 "hello Mike!" "ciao Mike!"
SUCCESS - contribution added to domain "4"
```

Currently Domain has only `id` and `name` fields; we will include in this command any other additional fields we will put in the future in order to better distinguish between two domains with the same name.
