### ISSUE TITLE
Use Java API directly?

### ISSUE THREAD

**Issue by alexandergunnarson** [ModernMT/MMT#196]
First of all, MMT looks like an incredible project and I'm very impressed! I ran the example you put in the readme and it was very cool to see how quickly I could get results from it.

I was wondering, is there a way to use the Java API directly rather than only going through the REST API? I don't necessarily want to be locked into some of the design choices (sensible though they may be) of e.g. Jetty and a local RocksDB instance. I'd prefer using Netty with perhaps DynamoDB with maybe S3 integration or something (though maybe EBS with your RocksDB integration is the way to go) — I'm not sure yet. I'm not yet familiar with the inner workings of MMT. I tried to use Maven to just package the contents of /src folder into a library .jar I could use, but that doesn't work because MMT apparently relies on certain binaries (not quite sure which ones). I'm definitely all for microservices architecture, but I'd like a little more modularity. Could you point me in the right direction on this?

Thanks for your time!

**Comment by davidecaroselli** [comment]
Hi Alex,

you can use MMT directly from Java just including the jar compiled into the `build` folder. However the current implementation uses "external" binaries for the training, the ones contained into `build/bin`. These are actually used by the `mmt` python script, not the Java code itself.

So if you want to use the MMT runtime code you have to:
- Include the JAR `build/mmt-0.xx.jar` in your project
- Because MMT uses JNI, it need also the path to the native libraries, so you have to launch the java process with the option `-Djava.library.path=/absolute/path/to/MMT/build/lib`
- If you plan to use the textprocessing pipeline, you have to specify where its models are. You can do it directly from Java with this line of code: `TextProcessingModels.setPath(new File("/path/to/MMT/build/res"));`

If you're familiar with Maven,  you can also add dependencies to your project like so:
```xml
<dependency>
    <groupId>eu.modernmt</groupId>
    <artifactId>mmt-core</artifactId>
    <version>0.14</version>
</dependency>
```

You can also import some specific modules and not the whole project.

**Comment by davidecaroselli** [comment]
I'm closing this issue, if you have any further question, please re-open it.
Thanks
