### ISSUE TITLE
ERROR Illegal state: failed to start kafka

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#219]
this is still happening from time to time.
I read a past post but I don't see the kafka/zdata stuff to delete.

what part of the log do you need to see what happens ?

**Comment by vince62s** [comment]
seems to be kind of:
NoNode for /brokers /config /admin things

**Comment by vince62s** [comment]
removing the runtime engine subfolder seems to solve the issue.

**Comment by davidecaroselli** [comment]
Hi @vince62s ,

first of all thanks for the solution 😄 
Anyways, the logs of the embedded Kafka process are reported in file `runtime/<engine-name>/logs/embedded-kafka.log`.
You don't find the folder kafka/zdata because we moved it in runtime and it's deleted every time MMT is restarted so we avoid the bug with Zookeeper.

Regarding your issue I have probably an idea of what happened: we store the various processes' pids in runtime folder. Now it can happen that after machine reboot a process gets exactly the same pid reported in our runtime folder.
If this happens, MMT thinks that a component is already running and don't start it. This of course could create problem with the engine start. Removing the runtime folder deletes this files so MMT is forced to restart everything again.

Have you noticed if you encounter this problem more often after a reboot?

**Comment by vince62s** [comment]
this is definitely part of the problem, I figured it out.
