### ISSUE TITLE
TMX question

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#221]
Question regarding tmx files.

will MMT ignore what is source or target in the XML file?
ie
can we use the exact same TMX file for training say EN-IT and IT-EN 2 engines ?

thx

**Comment by cattoni** [comment]
Hi @vince62s 

When creating an engine, MMT is aware of the source and target in a TMX provided in the training dir.
If source and target match the language direction the TMX is used as it is, otherwise it is reversed.

For example: given a TMX containing source=EN and target=IT, in case of creating a EN-IT engine the sentence pairs in the TMX are extracted as they are. In case of creating a IT-EN engine, the source sentences in the TMX are extracted as target, and the target sentences in the TMX are extracted as source.

Please note that during engine creation, a specific cleaning of the TMX is applied in order to remove the so called "draft" segments.

**Comment by vince62s** [comment]
Thanks.
I am having another strange issue with numbers.
In english thousand separator is "," and when translated in the target language weird things happen.
Example EN to FR:

There were more then 150 000 new cases of cancer => Il y a eu plus de 000 000 nouveaux cas de cancer
There were more then 150000 new cases of cancer => Il y a eu plus de 150000 nouveaux cas de cancer
There were more then 180,000 new cases of cancer => Il y a eu plus de 180,000 180,000 nouveaux cas de cancer

How can we fix this ? (only the second one works fine)
thanks

**Comment by davidecaroselli** [comment]
Hi @vince62s 

I've just created a new issue #222  because this is not related to TMX import. Thanks for the report, we're going to solve this problems in the next days. Please follow the other issue for news.

Thank you!
