### ISSUE TITLE
Fault-tolerance in model persistence

### ISSUE THREAD

**Issue by alexandergunnarson** [ModernMT/MMT#224]
Hey!

(Thanks, by the way, for answering my question about the Java interop. My team and I have decided to move away from that approach and just use the Docker/container approach you give in the readme.)

I'm just wondering about fault-tolerance in the context of model persistence. For instance, let's say I have a ModernMT instance running in a Docker image on EC2. Let's further say I pipe a whole bunch of training corpora into it and train on them. Then I start directing translation requests to this ModernMT instance, and start incrementally adding translation data / sentence pairs to further tune it. After a while, I'll end up with a few gigabytes — maybe tens or even hundreds of gigabytes, I don't know — in RocksDB, comprising the model. Here's where my concern comes in. ModernMT seems to rely heavily on RocksDB, and while I'm totally on board with the fact that it's blazing fast, I'm worried about its replicability and fault-tolerance since it's just a local DB. I read what you said about deploying a cluster and how joining a cluster means locally replicating the DB, which is really nice feature (I mean, really slow if the model is huge, but a potentially acceptable tradeoff). However, what do I do in order to ensure that data is preserved across e.g. node or even entire cluster failures? Regular EC2 backups to S3? In short, I'm wondering whether persistence providers for MMT are modular. It might be nice to have data replication to e.g. DynamoDB or something — I'm not sure yet.

What are your thoughts on this?

Thanks for your time and your efforts!

**Comment by davidecaroselli** [comment]
Hi @alexandergunnarson ,

*short answer: current version of MMT (0.14) does not support clustering. This is a temporary problem and it is due the fact that the simplistic approach we had in the past is no longer valid with actual databases.*

For MMT prior 0.14 the backup is indeed trivial: the models are static, you can simply copy the engine folder wherever you like because models never change.
With new version of ModernMT this is starting to be more complex. The infrastructure itself is built to be fault-tolerant and reliable if properly configured:
- Updates (both TMX and single contributions) are appended to an [Apache Kafka](https://kafka.apache.org/intro) queue. If you're concerned about data integrity and availability you can configure your own Kafka cluster and set MMT work with it thought the configuration file.
- Once data are available in Kafka, they will be eventually pulled by the MMT node.
- So ideally when we will have reintroduced clustering, you will end up with N nodes in the cluster having an exact updated copy of the models at any moment. This ensures a high replication of data.
- If a node fails you will be able to remove it from the cluster without harming the operation of the cluster.
- New nodes will join the cluster and will synchronize models with its pairs.

Hope this has answered you questions. If not, please don't hesitate to ask me more :)

Cheers,
Davide

**Comment by davidecaroselli** [comment]
I'm closing this issue, if you have any further questions please don't hesitate to re-open it and continue the thread.

Thanks!
