### ISSUE TITLE
pre cassandra models

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#239]
Hi,
I Haven't updated my repo for a while (6 to 8 weeks )
Just to make sure if I just git pull , will my previous models be upgraded ? will ut still work ?
thanks.

**Comment by davidecaroselli** [comment]
Hi @vince62s 

the up-to-date `master` branch version is v0.15 and unfortunately its models are not backward-compatible so you need a full retrain of the engines. 

We will probably put more effort in future releases in order to provide scripts for porting models from one version to another, but in this case the changes done to the Translation Model and Language Model made the them impossible to convert.

sorry for that!
Davide

**Comment by vince62s** [comment]
hello @davidecaroselli 
I git pulled. I mvn clean installed.
I started to cretae a new engine.
on step 2, IOError: no such file ... /vendor/cassandra-3.10/conf/caasndra.yaml
as a matter of fact there is no cassandra folder in vendor.
I tried git submodule init and update, no chance.
any clue ?

**Comment by davidecaroselli** [comment]
yes, you have to run the last step of the [INSTALL.md](https://github.com/ModernMT/MMT/blob/master/INSTALL.md):
```
./setup.py
```

**Comment by vince62s** [comment]
ok thanks.
is the option --cluster-port now only one port ? does it take only one or 2 consecutive ?

**Comment by davidecaroselli** [comment]
yes, the old option `--cluster-ports` completely ignored the second port (for legacy reasons) so we decided to remove the useless parameter. Now `--cluster-port` only need one single port.

**Comment by vince62s** [comment]
the default API GT key is not valid for GNMT, is it ?

**Comment by vince62s** [comment]
@davidecaroselli 
One more issue:
I successfully created and started one model.
I tried to create a second one (while the first one is started) and I got an error message.
embedded-caassandra.log complains about a port already in use ...

**Comment by davidecaroselli** [comment]
API GT key: exactly, the provided GT API key is not valid for GNMT, you have to provide your own with the option `--gt-key`

On the port already in use: @AndRossi is testing this issue right now, we'll keep you updated!

**Comment by davidecaroselli** [comment]
@vince62s  we have just pushed a fix for the problem you shown. In order to update your code you can simply `git pull origin master`, no need for re-compile but you have to run again the command:
```
./setup.py
```
 Once done that, please check that there are no "orphans" processes of MMT with the command `jps` and `ps aux | grep cassandra` (otherwise, kill them with `kill -9 <process-pid>)`
Now you can (again) run multiple engines on the same machine.

Please let me know if this solved the issue. Thanks!
Davide

**Comment by vince62s** [comment]
thanks guys, works fine now.

**Comment by davidecaroselli** [comment]
Great! Thanks @vince62s for your patience.
I'm closing the issue right now, if you have any other problem don't hesitate to re-open it.

**Comment by vince62s** [comment]
reopening ...
I was able to train a new engine while an other one was started, but when starting a new one I have a message saying port 9042 was in use. I figured it out (need to specify --db-port for another engine) but might be good to document it.
cheers.

**Comment by alexandergunnarson** [comment]
@davidecaroselli I've appreciated your insight on this! I wanted to ask you a question about model compatibility in general, actually. When a new version introduces an incompatibility in the model, it's straightforward to handle when I only have a corpus to be imported  — I just need to retrain. However, what happens if I've been training a model incrementally for a while and I need to re-import those incremental translations? Do I need to preserve those incrementally provided translations somewhere in some translation database, export them to a huge sentence-aligned corpus file, append the "original" corpus, and *then* train? It would be nice to have some sort of model-to-corpus functionality in such cases so translations don't have to be stored in multiple places.

**Comment by AndRossi** [comment]
Hi @vince62s, 
Thank you for your feedback! You are right, we should create documentation to make that part clearer.
After your suggestion we have created a [FAQs page](https://github.com/ModernMT/MMT/wiki/FAQs).
At the moment it only answers to your issue, but we plan to add new Q&A soon.

Thanks again for your contributions.

**Comment by davidecaroselli** [comment]
Hi @alexandergunnarson 
your guess is correct indeed. At the moment there is no such functionality in MMT, so you should keep track of new domains and contributions, organize them into domain-separated parallel text and retrain from that.

I understand that this is not really an easy task, but your suggestion gave me an interesting idea: we can create a `dump` functionality that exports data inside the models in a sort of "standard" way that can be imported back in different releases.

This could be a really nice-to-have feature for next release.

Thanks for the suggestion,
Davide

**Comment by alexandergunnarson** [comment]
No problem at all! Thank you for letting me know the current state of things. Keep up the good work — ModernMT is a really high-quality project! :)

**Comment by davidecaroselli** [comment]
Thank Alex! :)

**Comment by alexandergunnarson** [comment]
You're welcome :)
