### ISSUE TITLE
Avoiding overfit

### ISSUE THREAD

**Issue by whwhite** [ModernMT/MMT#240]
Does ModernMT use some sort of cross validation to avoid overfit with its translations?  If so, what technique is used to avoid overfit?

**Comment by nicolabertoldi** [comment]
At present, ModernMT is an enhancemnet of the phrase-based SMT toolkit Moses.

It is up to the user to avoid overfitting by having quite general data sets for training and tuning.
Nevertheless, the need of avoiding overfitting strongly relates to the actual application scenario of ModernMT.

Consider that ModernMt aims at automatically adapting the translation to the context of the input;
hence, to a given extent, a light overfitting is desired when the input text is close to any portion of the training data.
Nevertheless, ModernMT is able to keep a reasonable level of genericity, in order to translate a text which is definitely far from the training data.

**Comment by davidecaroselli** [comment]
I'm closing this issue, if you have any further question please don't hesitate to re-open it!
