### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#242]
Hi,
I know this is not new, but I would like to know if there are some plans to boost a bit the performance.
On a huge Ram machine, we can have one reasonable engine, but once we put 2 or more, performance degrades a lot.
Don't you think it would be possible to prune massively the sapt to reduce the memory footprint ?
Also, at a given time, how many java process should be running per engine ?
thanks.

**Comment by cattoni** [comment]
Hi @vince62s 

A way to reduce both memory space and the translation time is to reduce the search space, by modifying some parameters in the moses.ini file:

`$MMT_HOME//engines/$ENGINE/models/decoder/moses.ini`

Namely you can halve the default value of

`[cube-pruning-pop-limit]`

setting it to 500 instead of 1000

and of `sample-limit` in 

`SAPT name=Sapt path=${DECODER_PATH}sapt input-factor=0 output-factor=0 sample-limit=1000 lr-func=DM0`

setting to 500 instead of 1000


Typically the loss in quality is low (~ 0.1 BLEU point).

**Comment by vince62s** [comment]
I knew about the first one, I always use 400 (does no degradation)

however the second one is new to me: is this at training time or loading / translation time ?

**Comment by cattoni** [comment]
Hi @vince62s 

The translation time.
So it could also improve the tuning phase.

**Comment by vince62s** [comment]
I'll try that, thanks.

**Comment by davidecaroselli** [comment]
Hi @vince62s 

I would also add another tip: if you're running two engines on the same machine, they are basically competing for the same resources: CPU and RAM - this could lead to performance degradation.

In order to change the number or cores assigned to an engine you can edit the `engine.xconf` file like so:
```xml
<node xsi:schemaLocation="...">
          <engine source-language="..." target-language="...">
                    <decoder threads="6" />
          </engine>
</node>
```

This way you're saying to the engine that it should use only 8 translation threads. For example if you have a 16 CPU machine, and two engines you could set 6 threads each (why not 8? the process is also doing other stuff beside translating, use all CPU for such task could result in lower translation speed).

As of the RAM, unfortunately we don't have easy solution for that at the moment. We are investigating into pruning techniques, but I am not able to give you any forecasts at the moment.

**Comment by vince62s** [comment]
I think it's more a memory issue than a cpu one. just the fact that all engines are loaded at the same time creates an issue.
Am I right saying that there are 3 java processes per engine , plus one java overall process ?
ie if I run 3 engines , I see 10 java processes ?

**Comment by AndRossi** [comment]
Hi @vince62s,

In MMT 0.15 version and above, each engine runs 4 java processes (assuming you are not using your nodes in MMT Clusters):
- the MMT itself process
- a Zookeeper process
- a Kafka process
- a Cassandra process

Otherwise, if your nodes are connected in MMT Clusters, you will have as many MMT processes as the number of your nodes, but one single Zookeeper process, one single Kafka process and one single Cassandra process per cluster.

**Comment by davidecaroselli** [comment]
I would like to add another tip before closing this issue. Another speed problem could be the **cold start**: MMT uses a lot of mmap, this means that the engine is slow just after launch, and it gets faster as soon as it starts translating.

You can "pre-load" the models file in the OS filesystem cache just before starting MMT with this command:
```
find engines/{engine_name}/models/ -type f -exec dd if={} of=/dev/null bs=1024000 \;
```

With this expedient, the MMT engine will be at its maximum speed from the very beginning, and also model loading will be lot faster.

I'm closing this issue right now but, as always, if you have any other question please don't hesitate to re-open it!
