### ISSUE TITLE
Importing of parallel text files into an existing engine

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#244]
Hello MMT team,

Hope it's all well with you.

I am trying to add parallel text files to an already-built engine, but it seems MMT doesn't accept such file format. The parameters for import command are the following:

usage: mmt [-h] [-d DOMAIN] [-x TMX_FILE] [-e ENGINE] [-p API_PORT]

Does this mean that it only accepts TMX file format? I am having hard time converting UN corpora parallel text files into TMX file due to its huge size. 

Please let me know what you think. If this is not available at the moment, maybe it could be added to your enhancement list.

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan 

As you guessed, at the moment the mmt import functionality does not accept parallel corpora.

The “import” function was designed thinking that after training an engine, a translator may produce additional translation resources and may want to add them to the engine knowledge.
These contributions are usually either TMX files or simple sentences, so the engine, through the import command or through its REST APIs, accepts these kind of inputs.

An already existing parallel corpus such as the UN corpus should probably be employed during the initial training phase - however I understand that this is not entirely possible due to the RAM issues we spoke of last week.

To overcome the RAM issues, I suggest you to just use a portion of the UN corpus. 
Even with just a portion, in fact, your training corpora are so big that MMT precision will still be acceptable.

For any more questions or problems, don’t hesitate to contact us.

Have a nice day!

Andrea

**Comment by mzeidhassan** [comment]
Thanks Andrea! I see.

And yes, due to the RAM issue we spoke about last week, I trained the engine without the UN corpus. Now, with the added RAM in place, I thought it's now the time to import it.

I will follow your advice and use a portion of it. Thanks again for the great support and the awesome product. 

I am closing the issue.

Kind regards,
Mohamed
