### ISSUE TITLE
failure of "mmt start"  (eu.modernmt.engine.BootstrapException: Unable to initialize the DB)

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#247]
After updating to the today commit of branch "develop" (a685313), "mmt start" of medium-size engines fails in loading models, with the following error in the runtime/$ENGINE/logs/node.log :
```
FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: Unable to initialize the DB
	at eu.modernmt.cluster.db.DatabaseLoader.load(DatabaseLoader.java:100)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:405)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:45)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: eu.modernmt.persistence.PersistenceException: invalid query (possible causes: syntax error, unauthorized...)
```

Moreover the cassandra java process keeps on running after command end (it must be killed by hand).

The problem comes up with both new engines (created with this version) and old engines (created and running with 14 April version)
Please note that the problem DOES NOT come up with the (simple) "default" engine.

**Comment by AndRossi** [comment]
Hi Roldano,

Can you please send me an example of a "create" command line that raises
this issue?

(By the way we are about to release a script for porting 0.15.x engines to
both the current develop version and the current master version.
I'll keep you up to date!).

Andrea

**Comment by cattoni** [comment]
Hi Andrea

Maybe my post was not clear: "mmt create" works successfully, it is "mmt start" that raises the error.

"mmt start" fails with medium-size engines, e.g. an Arabic-English engine trained with TED data (bilingual words: 288K src, 3892K tgt, monolingual words: 4020K tgt). Size of the engine/models directory: 1.1GB.

Should you need more info, don't hesitate to call me!

Ciao

  Roldano

**Comment by AndRossi** [comment]
Hi @cattoni , 

I tried to create and start a medium-size engine with about 10M words and it seems to work fine here.
Can you try to download again the source code in a separate folder and perform the MMT installation again? Hopefully this will solve the problem.

Andrea

**Comment by cattoni** [comment]
Hi @AndRossi 

Your suggestion was successful !
With the last version of MMT source reinstalled from scratch (= from "git clone" on) the problem did not arise when running a newly created engine with the ar-en data previously described.

So upgrading a new release with  'git pull' appears not safe: a re-installation from scratch is needed.

Maybe a command to clean binaries/libraries (both C++ and java) could make "git pull" safe ... maybe...

Anyway, thanks for your support!

   Roldano

**Comment by AndRossi** [comment]
Hi @cattoni,

I'm glad it worked! 
I think that your issue occurred because we made some changes on the C code in order to reduce che amount of RAM it requires.

I was just thinking that using "mvn clean install" instead of "mvn install" to build the binaries may be just as effective as re-downloading everything from scratch as I suggested you (but I'm not very sure). Had you tried it?

Andrea

**Comment by cattoni** [comment]
Hi @AndRossi 

Yes, the sequence of commands I issued was:
1. cd $MMT_HOME ; git pull 
2. cd vendor ; ./compile
3. cd ../src ; mvn clean install

So "mvn clean install" was present, but didn't work as expected, since the produced version generated the reported problem.

I agree, it appears strange that "clean" substep of "mvn" does not remove all the binaries and libraries...

Would you like me to retry the whole procedure? I mean
a) install from scratch version v0.15.1 commit of 14 April
b) upgrade to commit of 21 April with the above sequence of commands (i.e. without re-installing from scratch)
and check if the problem is present? If yes, then by inspecting the produced version we could understand better what was not as expected.

Best

Roldano

**Comment by davidecaroselli** [comment]
@AndRossi given the fact that the error seems related to the DB I would exclude that the problem was related to the C part. My guess is that with the new "compile" script we modify the script in Cassandra, while the old version didn't. That's why the old installation was not working properly.

Anyways, everything seems ok now, so we know for sure that the problem was a partial "installation" where some of the components were still "old version". With a brand new clone of the repo you're always sure you have everything up-to-date.

Cheers guys!
