### ISSUE TITLE
mert fails if dev contains empty lines

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#253]
tuning fails if either source or target side of the development set contains empty lines 
this can happen if any line of the original set is actually empty, or contains only xml tags (wchi are removed in the tuning phase

possible solutions:
1) insert the removal of such "empty" lines in the preprocessing step;
2) insert the removal of such "empty" lines directly in mert-moses.pl

In both case, the removal has to be done considering source and target together in order to keep sentence alignment.

3) other ideas?

To me, solution 2 is the best one because it solves a "bug" of the mert tuning, and has minimal or no impact on the rest of the system

if you agree on option 2, i volunteer to fix the bug.

**Comment by davidecaroselli** [comment]
100% with you on that.

Just please notice: because the problem is also in the master/develop branch, please implement the fix in the `develop` branch and then marge **from** `develop` **to** `features/neural_decoder` (the branch I'm assuming you actually want the fix into).

In this way we will have both branches (develop and features/neural_decoder) fixed, without interfering with the actual state of the branches.

Thanks Nicola!
