### ISSUE TITLE
Alignment failed

### ISSUE THREAD

**Issue by chiphuyen** [ModernMT/MMT#255]
I tried to supplement my own data (english to spanish) to docker container, but got this error in step 4:
```
INFO: (4 of 7) Aligner training...                                     DONE (in 2m 27s)
ERROR Unexpected exception:
	Command '/home/mmtuser/mmt/build/bin/fa_build -s /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.en -t /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.es -m /home/mmtuser/mmt/engines/default/models/align -I 4' failed with exit code -9
```

I can't seem to access /home/mmtuser so I have no idea what it means. Would be great if you could help. Thanks

**Comment by AndRossi** [comment]
Hi @chiphuyen,

I launched the last MMT version on a Docker container with command:  
```docker container run -it modernmt/master:latest```. 
This runs Docker in foreground, so my shell "landed" to folder ```/home/mmtuser/mmt```.
  
In that way I was able to reach the log file:   ```/home/mmtuser/mmt/runtime/<engine_name>/logs/training.log```.

That log file should contain more explicit information on what went wrong with your machine: could you please send me its content?
Thank you!

Andrea

**Comment by chiphuyen** [comment]
This is the content of the file:

```
2017-07-03 18:16:24,315 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 1
2017-07-03 18:16:24,322 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket 2
2017-07-03 18:16:38,604 [INFO] - Training step "Context Analyzer training" completed in 27s
2017-07-03 18:16:38,619 [INFO] - Training step "Aligner training" (4/7) started
2017-07-03 18:16:40,964 [DEBUG] - Shell exec: /home/mmtuser/mmt/build/bin/fa_build -s /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.en -t /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.es -m /home/mmtuser/mmt/engines/default/models/align -I 4
== Forward model training ==
Initial setup... 2017-07-03 18:19:06,494 [INFO] - Training step "Aligner training" completed in 2m 27s
2017-07-03 18:19:06,503 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/mmtuser/mmt/cli/engine.py", line 360, in _build
    delete_on_exit=delete_on_exit)
  File "/home/mmtuser/mmt/cli/engine.py", line 442, in _run_step
    result = step_function(*values, skip=skip, logger=logger, delete_on_exit=delete_on_exit)
  File "/home/mmtuser/mmt/cli/engine.py", line 515, in _step_aligner
    self._engine.aligner.build(corpora, working_dir, log=logger.stream)
  File "/home/mmtuser/mmt/cli/mt/phrasebased.py", line 154, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/home/mmtuser/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/mmtuser/mmt/build/bin/fa_build -s /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.en -t /home/mmtuser/mmt/runtime/default/tmp/training/aligner/merge.es -m /home/mmtuser/mmt/engines/default/models/align -I 4' failed with exit code -9
```
Thanks @AndRossi

**Comment by AndRossi** [comment]
Hello @ChipHuyen,
   
Thanks for the log information.
   
Can you please try to train a small default engine in your docker container?
You can use command ```./mmt create en it examples/data/train -e test```.
If the creation succeeds, the problem you’re experiencing is probably due to a RAM overload.
   
You can tell for sure by trying to create your en-es engine and checking the RAM usage as the creation progresses. To check the RAM usage you can use command ```free -h```.
  
You can find more information on MMT RAM requirements on [our install page](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#memory).
  
I hope this is helpful; please let me know if there are any updates.

Andrea

**Comment by AndRossi** [comment]
Hello, @chiphuyen, 

I'm closing this issue now.

If the problem remains, or if you have any doubts or remarks, don't hesitate to reopen it.

Best,

Andrea

**Comment by rptl** [comment]
Just for the records, I just faced a similar issue with server memory x training. I ended up creating a swap file with 8Gb to do the job.

# create dummy 8GB file
dd if=/dev/zero of /path/to/swap_tmp bs=1024 count=8000

# setup swap area on new created file
mkswap /path/to/swap_tmp

# activate new swap
swapon /path/to/swap_tmp

Cons: Since it uses the file as memory to read write/read,  Train will increase server IO and can cause some performance degradation. I do not advise to do it on Production servers,  during peek hours. Be careful. Also, as expected,  training will take some considerable amount of time. Here increased +7mins only (42 min against 35) for 5GB of training data on total.

**Comment by davidecaroselli** [comment]
Thanks @rptl , nice advice!
