### ISSUE TITLE
Slow with more than one model ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#257]
In my tests, it seems that, with more than one model running on a machine (with different ports), it's becoming very slow. Is this specific to my own side, or is this something you usually get ? Is there something to do ?

I guess all models are independent (different processes, with embedded database, on different folders). If yes, I don't understand why few models should be slow when launched together.

Remark : when starting an engine with "-e XXX" option, the translate URL get a "test" in its formulation:
> You can try the API with:
>	curl "http://localhost:8047/ **test** /translate?q=world&context=computer" | python -mjson.tool

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

As you said, different models are completely independent and you can run multiple engines on a single machine.
If you are employing large training sets, however, this may lead to a RAM overload, causing your OS to perform more and more page swaps and thus degradating your performances.
Depending on your hardware, it is also possible that your CPU is overloaded if multiple engines are running at the same time. 

As for the “test” default name appearing when you start an engine, we will solve this issue immediately. We’ll keep you updated.

If you need anything else, don't hesitate to write it down here.

Best,

Andrea

**Comment by EtienneAb3d** [comment]
It's not a problem of RAM and/or CPU overload. Both are far to be overloaded. 
I will try some new tests to validate conditions. But, as observed on few attempts, with only the default model, it takes few seconds for a sentence. When loading a second model, it can take minutes. When stopping the second model it takes again seconds.

**Comment by EtienneAb3d** [comment]
This issue can be closed. With more experimentations, I found it's rather a question of processing profiles persistence. When you are translating new sentences, it takes (much) less time if the new sentences/contexts are close to the previous viewed ones. When looping on similar sentences with similar contexts, translations are done in seconds. When trying with a very new kind of sentences and contexts, it can take minutes. When experimenting with new models launched in parallel, this profile persistence behaviour certainly mistaken me on the analyse.

**Comment by AndRossi** [comment]
Hello @EtienneAb3d,
The behaviour you noticed is probably due to the fact that when a part of a model needs to be accessed it is cached into RAM, making it much faster to read again if necessary, 

After you pointed out this issue, we proceeded to add to the [FAQS section](https://github.com/ModernMT/MMT/wiki/FAQs) a Q/A that explains how to perform an engine warm-up before starting it. This will force all the models of your engine into RAM, thus boosting the translation speed since the beginning.

As for your problem with the API URL showing root **test**: we were not able to replicate your problem in our environment. 
Can you please check if your engine configuration file contains a **root="test"** attribute in the "api" XML element under the "network" element? 
You can find your engine configuration file in path ```engines/<your_engine_name>/engine.xconf```.

Thanks,

Andrea

**Comment by EtienneAb3d** [comment]
Right ! This "test" parameter is there because, due to port conflicts between models, I was obliged to enrich the config file, and I did it with a copy/paste of your example here:
https://github.com/ModernMT/MMT/wiki/Advanced-Configurations

It would be nice if the "create" command would produce a config file with all ports defined. It would be much easier to change them after creation.

**Comment by davidecaroselli** [comment]
I'm closing this issue.
@EtienneAb3d thanks for the suggestion, we are currently working also on the configuration file and we will also include a stub config file that can be used as a starting point!

Thanks again!
