### ISSUE TITLE
Profile persistance and translation quality

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#258]
When testing MMT in a real situation, the translator had the sensation that the system was learning from her. It wasn't the case ! This can be explained by the fact that the translation was better at the end of the document, than at the beginning. This is possibly coherent with my observation about performance here:
https://github.com/ModernMT/MMT/issues/257#issuecomment-314370630

Is there a known remanence effect that could explain that translations are better after having translated similar sentences before ? If yes, is there a way to get better result from the beginning ? Should I translate the same document N times, to keep the latest, supposed to be the best ? Is this a result of MMT algorithms, or a secondary effect of the database cache management on partial data sets ?

**Comment by davidecaroselli** [comment]
Hi Etienne,

so if you're **not** using the MMT online-learning feature, sending back the post-edited segments with [Add to Domain API](https://github.com/ModernMT/MMT/wiki/API-Add-to-Domain), then MMT will output always the same translations.

The case of the issue #257 is in fact a problem of caching and warm-up (by the way, we're also answering that question right now :) ), so it's a matter of speed and not quality.

I believe that simply the end of the document looked more like the data indexed in the MMT engine, so the translation quality was better simply because the models were better in translating those sentences.
If you find out that a sentence is translated in two different ways when context and model are exactly the same, please open an issue with some indications on how to reproduce the case because that is not normal and should not happen.

**Comment by mzeidhassan** [comment]
@davidecaroselli Sorry Davide to post here after closing. Where can I find this online-learning feature in the API documentation? Clicking on "Add to Domain API' takes me to "Create new page" in the Wiki page. I could find though "[API Add to Memory page](https://github.com/ModernMT/MMT/wiki/API-Add-to-Memory)". Please let me know.

Thanks!
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan, 

The [API page you linked](https://github.com/ModernMT/MMT/wiki/API-Add-to-Memory) is the correct one. We have recently renamed "domains" into "memories", so the "domains" page that Davide referred to some months ago does not exist anymore :)

The new "Add to Memory" API perfectly corresponds to the old "Add to Domains" one.

However, please note that (even if the API page was removed) for the sake of backward-compatibility the old "domains" API is still working :) 

Have a nice day!

Andrea
