### ISSUE TITLE
Hanging Import

### ISSUE THREAD

**Issue by cettolo** [ModernMT/MMT#261]
Setup: I want to translate with just one specific TMX
Steps:
- deletion of previous TMXs:
rm engines/\<engineName\>/models/context/\*/\* engines/\<engineName\>/models/decoder/memory/\*

- import of the specific TMX:
mmt import -e \<engineName\> -d \<domainName\> -x \<specificTMX\>

Now the engine is supposed to work as expected; on the contrary, if I run:
curl "http://localhost:8045/translate?q=world&context=computer" | python -mjson.tool

I got this error:
{
    "error": {
        "message": "Could not open index directory: MMapDirectory@/hardmnt/hltmt1/data/ModernMT/engines/NETFLIX.en-id.ChesapeakeShores/models/context/index lockFactory=NativeFSLockFactory@/hardmnt/hltmt1/data/ModernMT/engines/NETFLIX.en-id.ChesapeakeShores/models/context/index",
        "type": "ContextAnalyzerException"
    },
    "status": 500
}

On the contrary, if, after the import step, I stop the engine and then I restart it, it works properly.

**Comment by davidecaroselli** [comment]
Hi @cettolo 

this is definitely not a bug. Removing the Lucene index while the index is running means corrupting the system. This is true both for the Context Analyzer and the TranslationMemory.

When you restart the system however, the Lucene engine re-create an empty index, that's why the system operates as expected.
