### ISSUE TITLE
Error while tuning

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#262]
I did a "create" and a "tune" on these data few weeks ago, without problem.

Having overwritten the engine by error, I just did a new "create" and a new "tune" on the same data. But, now, I get this error, in 2 "tune" attempts:

INFO: (1 of 4) Corpora tokenization...                                 DONE (in 6s)
INFO: (2 of 4) Merging corpus...                                       DONE (in 0s)
INFO: (3 of 4) Tuning...                                               DONE (in 336s)
ERROR Unexpected exception:
	Command '/home/dev8/mmt/cli/opt/mert-moses.perl /home/dev8/mmt/runtime/FREN/tmp/tuning/corpus.fr /home/dev8/mmt/runtime/FREN/tmp/tuning/corpus.en /home/dev8/mmt/cli/opt/mertinterface.py /tmp/tmp0lkgHL --threads 16 --mertdir /home/dev8/mmt/build/bin --mertargs '--binary --sctype BLEU' --working-dir /home/dev8/mmt/runtime/FREN/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --bleuscorer /home/dev8/mmt/cli/opt/mmt-bleu.perl --bleuscorer-flags "-nt" --early-stopping-value 1 --predictable-seeds --maximum-iterations=25' failed with exit code 2

The model is running, and works fine. It's just not tunable...

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

We have tried to perform an mmt create and tune on an en-fr corpus, but unfortunately we were not able to replicate your issue in our environment yet.

Could you please send me the content of your ```<your_mmt_root>/runtime/<engine_name>/logs/node.log``` file? It should contain more detailed information on the problem you have encountered.

Thanks for your patience.

Andrea

**Comment by AndRossi** [comment]
Hi @EtienneAb3d ,

Could you also try to perform tune with command ```./mmt tune -e <your_engine_name> --debug```?
This way you should also find in your logs folder the ```mert.log``` file, that is a specific tuning log.
It would be very helpful if you could sent me that log too.

Andrea

**Comment by EtienneAb3d** [comment]
It seems it failed when trying to translate a VERY long sentence. Certainly, for the tuning, the set of used sentences are randomly chosen in the "create" process ? This could explain that I didn't get this problem at the first create/tune. 

 ...
1) run decoder to produce n-best lists
params = --port 8045
decoder_config = -weight-overwrite 'Distortion0= 0.033556 Sapt= 0.027740 0.039156 0.004247 0.012173 InterpolatedLM= 0.088372 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0
.067011 0.030089 WordPenalty0= -0.075074 PhrasePenalty0= -0.137940'
Traceback (most recent call last):
  File "/home/dev8/mmt/cli/opt/mertinterface.py", line 178, in <module>
    translator.run()
  File "/home/dev8/mmt/cli/opt/mertinterface.py", line 119, in run
    translation = translation_job.get()
  File "/home/dev8/mmt/cli/libs/multithread.py", line 289, in process
    result = self._func(*self._args, **self._kwds)
  File "/home/dev8/mmt/cli/opt/mertinterface.py", line 56, in _get_translation
    translation = Api.translate(line, context=context_vector, nbest=nbest)
  File "/home/dev8/mmt/cli/cluster.py", line 131, in translate
    return self._get('translate', params=p)
  File "/home/dev8/mmt/cli/cluster.py", line 63, in _get
    return self._unpack(r)
  File "/home/dev8/mmt/cli/cluster.py", line 55, in _unpack
    raise Exception('HTTP request failed with code ' + str(r.status_code) + ': ' + r.url)
Exception: HTTP request failed with code 400: http://localhost:8045/translate?q=De+souligner+qu%27+il+importe+de+poursuivre+les+efforts+visant+%C3%A0+%C3%A9liminer+les+obstacles+%C3%A0+
la+promotion+et+au+d%C3%A9veloppement+de+la+coop%C3%A9ration+afro-arabe+et+d%27+organiser+les+r%C3%A9unions+de+ses+instances+comp%C3%A9tentes+dans+ce+domaine+%2C+compte+tenu+des+r%C3%A9
solutions+adopt%C3%A9es+par+le+Conseil+de+la+Ligue+%2C+et+de+prier+le+Secr%C3%A9taire+g%C3%A9n%C3%A9ral+de+maintenir+les+contacts+%C3%A0+cet+effet+en+vue+de+parvenir+%C3%A0+une+coop%C3%
A9ration+effective+et+mutuellement+b%C3%A9n%C3%A9.....[CUT BY ME]...

**Comment by EtienneAb3d** [comment]
Trying to do a new create+tune, I still got the same error...
:-/

**Comment by davidecaroselli** [comment]
Hi Etienne,

sorry for the delayed response, I'm out of office right now.

The data selection for tuning and evaluation is deterministic, this means that even after a complete re-creation the engine will select the same lines for tuning set.

What you can do is open the data inside "engines/<your_engine>/data/dev" e manually remove the problematic lines. Please remember also to remove the parallel line in the other language file.

You can also use your own dev set if you prefer, just invoke the tuning command like this:

./mmt tune --path /path/to/your/data

Please let me know if this solves your issue or if you need further support.

Best,
Davide

**Comment by rptl** [comment]
I am getting similar issue. Tune is dying here (mert.log)

decoder_config = -weight-overwrite 'WordPenalty0= -0.075074 PhrasePenalty0= -0.137940 Sapt= 0.027740 0.039156 0.004247 0.012173 InterpolatedLM= 0.088372 Distortion0= 0.033556 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089'
Traceback (most recent call last):
  File "/opt/datafs/ModernMT/cli/opt/mertinterface.py", line 178, in <module>
    translator.run()
  File "/opt/datafs/ModernMT/cli/opt/mertinterface.py", line 119, in run
    translation = translation_job.get()
  File "/opt/datafs/ModernMT/cli/libs/multithread.py", line 289, in process
    result = self._func(*self._args, **self._kwds)
  File "/opt/datafs/ModernMT/cli/opt/mertinterface.py", line 58, in _get_translation
    nbest_list = sorted(translation['nbest'], key=lambda hypo: hypo['totalScore'], reverse=True)
KeyError: 'nbest'
Exit code: 1

**Comment by rptl** [comment]
Looks like my issue was related to #253 
I have found a empty line on my dev set and removed. 
It always stopped on "run1. Now it 's on run2 already.

**Comment by AndRossi** [comment]
Hi @rptl,

is your tune working properly after removing the empty line?

Andrea

**Comment by rptl** [comment]
Hey @AndRossi, thanks for following up! 

Instead of removing, I have replaced it empty by a single word on both  source and TARGET. Worked fine.

**Comment by AndRossi** [comment]
I'm glad now it works fine!

Since this issue seems solved, I'm closing it now.
For any question or doubt, however, don't hesitate to reopen it.

Have a wonderful day!

Andrea

**Comment by davidecaroselli** [comment]
@rptl @EtienneAb3d 

We are going to solve both issues in the next days, thanks for your patience! :)

**Comment by davidecaroselli** [comment]
Both problems have been fixed and they are available in our **master** branch with commit https://github.com/ModernMT/MMT/commit/a448e9ef21f0a3feadcf1d7ff3e3ad4f9db4aa3a

Thank you for your support! I'm closing the issue right now but please, don't hesitate to re-open it if you need to.

Thanks

**Comment by mzeidhassan** [comment]
Hi Davide,

I am opening this because I am having a tune error. I thought it's better to keep everything related to this issue in one thread. Please let me know if I should create a new issue.

Here is the error I am getting:


> ============ TUNING STARTED ============

ENGINE:  default
CORPORA: /root/ModernMT/engines/default/data/dev (10 documents)
LANGS:   en > ar

INFO: (1 of 4) Corpora tokenization...                                 DONE (in 6s)
INFO: (2 of 4) Merging corpus...                                       DONE (in 0s)
INFO: (3 of 4) Tuning...                                               DONE (in 6s)
ERROR Unexpected exception:
        Command '/root/ModernMT/cli/opt/mert-moses.perl /root/ModernMT/runtime/default/tmp/tuning/corpus.en /root/ModernMT/runtime/default/tmp/tuning/corpus.ar /root/ModernMT/cli/opt/mertinterface.py /tmp/tmpQb1b7Y --threads 4 --mertdir /root/ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /root/ModernMT/runtime/default/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --predictable-seeds --maximum-iterations=25' failed with exit code 2



and here is the output of 

`Using SCRIPTS_ROOTDIR: /root/ModernMT/cli/opt
Asking moses for feature names and values from /tmp/tmpQb1b7Y
Executing: /root/ModernMT/cli/opt/mertinterface.py --port 8045 -config /tmp/tmpQb1b7Y -show-weights
exec: /root/ModernMT/cli/opt/mertinterface.py --port 8045 -config /tmp/tmpQb1b7Y -show-weights
Executing: /root/ModernMT/cli/opt/mertinterface.py --port 8045 -config /tmp/tmpQb1b7Y -show-weights > ./features.list 2> /dev/null
MERT starting values and ranges for random generation:
    DM0 =   0.015 ( 0.00 ..  1.00)
    DM0 =   0.018 ( 0.00 ..  1.00)
    DM0 =   0.042 ( 0.00 ..  1.00)
    DM0 =   0.020 ( 0.00 ..  1.00)
    DM0 =   0.262 ( 0.00 ..  1.00)
    DM0 =   0.127 ( 0.00 ..  1.00)
    DM0 =   0.067 ( 0.00 ..  1.00)
    DM0 =   0.030 ( 0.00 ..  1.00)
  Distortion0 =   0.034 ( 0.00 ..  1.00)
  InterpolatedLM =   0.088 ( 0.00 ..  1.00)
  PhrasePenalty0 =  -0.138 ( 0.00 ..  1.00)
   Sapt =   0.028 ( 0.00 ..  1.00)
   Sapt =   0.039 ( 0.00 ..  1.00)
   Sapt =   0.004 ( 0.00 ..  1.00)
   Sapt =   0.012 ( 0.00 ..  1.00)
  WordPenalty0 =  -0.075 ( 0.00 ..  1.00)
featlist: DM0=0.015334 
featlist: DM0=0.018113 
featlist: DM0=0.042342 
featlist: DM0=0.020316 
featlist: DM0=0.261833 
featlist: DM0=0.126704 
featlist: DM0=0.067011 
featlist: DM0=0.030089 
featlist: Distortion0=0.033556 
featlist: InterpolatedLM=0.088372 
featlist: PhrasePenalty0=-0.13794 
featlist: Sapt=0.02774 
featlist: Sapt=0.039156 
featlist: Sapt=0.004247 
featlist: Sapt=0.012173 
featlist: WordPenalty0=-0.075074 
run 1 start at Wed Sep  6 13:50:08 MDT 2017
Parsing --decoder-flags: |--port 8045|
Saving new config to: ./run1.moses.ini
Saved: ./run1.moses.ini
Normalizing lambdas: 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 0.033556 0.088372 -0.13794 0.02774 0.039156 0.004247 0.012173 -0.075074
DECODER_CFG = -weight-overwrite 'Sapt= 0.027740 0.039156 0.004247 0.012173 PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 InterpolatedLM= 0.088372'
Executing: /root/ModernMT/cli/opt/mertinterface.py --port 8045  -config /tmp/tmpQb1b7Y -weight-overwrite 'Sapt= 0.027740 0.039156 0.004247 0.012173 PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 InterpolatedLM= 0.088372'  -n-best-list run1.best100.out 100 distinct  -input-file /root/ModernMT/runtime/default/tmp/tuning/corpus.en > run1.out 
Executing: /root/ModernMT/cli/opt/mertinterface.py --port 8045  -config /tmp/tmpQb1b7Y -weight-overwrite 'Sapt= 0.027740 0.039156 0.004247 0.012173 PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 InterpolatedLM= 0.088372'  -n-best-list run1.best100.out 100 distinct  -input-file /root/ModernMT/runtime/default/tmp/tuning/corpus.en > run1.out
(1) run decoder to produce n-best lists
params = --port 8045
decoder_config = -weight-overwrite 'Sapt= 0.027740 0.039156 0.004247 0.012173 PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 InterpolatedLM= 0.088372'
Traceback (most recent call last):
  File "/root/ModernMT/cli/opt/mertinterface.py", line 178, in <module>
    translator.run()
  File "/root/ModernMT/cli/opt/mertinterface.py", line 119, in run
    translation = translation_job.get()
  File "/root/ModernMT/cli/libs/multithread.py", line 289, in process
    result = self._func(*self._args, **self._kwds)
  File "/root/ModernMT/cli/opt/mertinterface.py", line 56, in _get_translation
    translation = Api.translate(line, context=context_vector, nbest=nbest)
  File "/root/ModernMT/cli/cluster.py", line 129, in translate
    p['context_vector'] = self._encode_context(context)
  File "/root/ModernMT/cli/cluster.py", line 101, in _encode_context
    ) for el in context])
KeyError: 'domain'
Exit code: 1
The decoder died. CONFIG WAS -weight-overwrite 'Sapt= 0.027740 0.039156 0.004247 0.012173 PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 InterpolatedLM= 0.088372' 
`

**Comment by AndRossi** [comment]
Hello @mzeidhassan, 

I'm glad to help.
Which version of MMT are you using at the moment?
Furthermore, could you please send me the whole logs folder (`<your_mmt_home>/runtime/<your_engine_name>/runtime/logs`) as a zip file?  
That would help me a lot.

Thanks for your patience!

Andrea

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

on a second thought, it would be better to open a different issue because your problem, on a first glance, seems different from the original one. I will also rename this issue to better identify the problem.

Thanks for your comprehension!
Davide
