### ISSUE TITLE
Building empty engine and incrementing instead training it.

### ISSUE THREAD

**Issue by rptl** [ModernMT/MMT#263]
Imagine a scenario where I wanted to build an engine *ONLY* by importing TMX or Adding segments, instead training any corpora first. 

Would that be possible? 

If answer is yes, since that engine hasn't ever trained before, how it would work compared with an engine containing *same data* BUT properly trained? The final translation result would be the same?

**Comment by davidecaroselli** [comment]
This is not possible; the baseline data are necessary in order to create two models that do not change over time: a background language model (as opposite to the adaptive incremental one MMT also has) and the alignment model.

These two resources do not need to be incremental because the baseline data is always enough to ensure an excellent quality and thus they represent a baseline system that gives to the engine a more "stable" behaviour.

Good news are that for such task you can use public-available data (available for example here: http://opus.lingfil.uu.se/ ). Good baselines for MMT have usually ~100M source words of parallel text and ~2B of monolingual ones, but you can experiment a little in order to find out the perfect mix for your needs in terms of quality vs. hardware resources needed.

**Comment by rptl** [comment]
Thanks, I was expecting that. I have the baseline already, something like 150M source words. Estimating to grow up ~30M words per month. Do you recommend to run *tune* once a month ?

**Comment by AndRossi** [comment]
Hi @rptl,

It seems that you have a really good baseline!

Of course you can run tune once a month.  
Please note that the default tuning data only refer to the baseline models used during creation.
Therefore, in your tune command you may also want to explicitly specify the path to the data you want to tune your engine on (e.g. a mix of baseline data and your newly imported data, or just your newly imported data, depending on your needs).   
To do so, you can run the command ```./mmt tune --path <path_to_your_data>```
   
To use monolingual data in the training process, just place them in the same folder as the parallel data.

Have a nice day!

Andrea

**Comment by davidecaroselli** [comment]
I would also add that, even if it's perfectly ok to tune every once in a while, you can save lot of time just tuning once, after the engine creation.

I recommend to delete the file "engines/your_engine/models/decoder/weights.dat" with the engine stopped, replace it with an empty file, start the engine and then run the tune.
This way you will start tuning from all zeros weights.

Also run tuning with flag "--accuracy best", this way the tune process will take more time, but it will maximize the translation quality (if you do it once, don't be hasty! ;) ).

With these two advices you will have the best weights for your engine, and I'm confident that they will work very well also after adding new content to it. Maybe you can do a re-tuning after 6 months!

One last thing: having monolingual data can drastically improve your translation performance, so as Andrea said just add you monolingual content right next your parallel one, you can notice it has been recognized looking at the very beginning of the engine creation output: it will print the number of parallel and monolingual resources found.

Good luck!

**Comment by rptl** [comment]
Thank you both for all those tips. I will definitely try it. Quick question: How should be named monolingual data file to be recognized during training?

**Comment by davidecaroselli** [comment]
Like this:

whatever_name_you_like.target_language

I.e. if your engine is en > fr you can have monolingual files like this:

my_monolingual.fr
another_monolingual.fr

**Comment by rptl** [comment]
Thanks again!
