### ISSUE TITLE
Best way to update a binary installation ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#267]
Latest binary release is still 1.0.2, the one I installed previously.
I would like to update to the latest version. 
Getting the main master ZIP, it seems I get something I need to build. Folders, like "vendor", seem to contain very different sub-folders and files. When I enter "./compile" in the "vendor" folder, I'm getting errors.
Of course, I can investigate to understand how to rebuild all. But, before this, is there a known simple procedure that would enable me to update the binary installation ?

**Comment by AndRossi** [comment]
Hello Etienne

I’m happy to help. In ordet to use the **master** branch version, you need to download the sources and build them from scratch; you can do that by following [this guide](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

Please note that the master branch currently differs from the binary version only for some minor bugfixes. Therefore, unless you have encountered a specific bug that has been solved in the master branch, using the sources version is probably unnecessary.

I hope this is the information you needed!
Let me know if this solves your issue.

Andrea

**Comment by EtienneAb3d** [comment]
The problem supposed to be solved now is described in issue 262.
So... I need to investigate with the encountered building problems...
I didn't explore all the folders. But, if the binary version is very similar to the master version, why these folders seem to be so different ?

`~/mmt_2017-07-05$ ls vendor`
`cassandra-3.11.0  kafka-0.10.2.1`

`~/mmt_2017-08-22/MMT-master$ ls vendor`
`compile  opennlp  rocksdb`

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

I see why you need to use the **master** branch.

Can you please send me the errors you encounter while executing the _compile_ script?
This way I can investigate them.

However, the ```vendor``` folders you mention appear different because in the source code version the various modules are meant to be downloaded during the execution of the _compile_ script. 
In the binary version, on the contrary, Cassandra and Kafka are distributed together with MMT, while Opennlp and RocksDB do not appear in the vendor folder because in this case they do not need to be recompiled. 

Andrea

**Comment by EtienneAb3d** [comment]
I didn't follow the exact procedure. I just directly gave a try to the "./compile" command, thinking my dependencies would be ok from the binary installation. So, this is for what it is:

./compile 
Installing RocksDB...

make: *** Aucune règle pour fabriquer la cible "install-shared". Arrêt.

Traceback (most recent call last):
  File "./compile", line 350, in <module>
    run_all()
  File "./compile", line 313, in run_all
    install_rocksdb()
  File "./compile", line 222, in install_rocksdb
    exec_process(command, working_directory=rocksdb_home, working_environment=wenv)
  File "./compile", line 85, in exec_process
    raise Exception("Return code != 0; exiting now...")
Exception: Return code != 0; exiting now...

**Comment by AndRossi** [comment]
Hello @EtienneAb3d,

As you figured out that is a dependency error. 
It is raised because you tried to execute the _compile_ script without importing some required submodules before. Following the procedure "Install from Source" should fix that.

Let me know if you manage to use MMT from sources or if you need further assistance :)

Andrea
