### ISSUE TITLE
Is there a way to rename a engine/domain?

### ISSUE THREAD

**Issue by rptl** [ModernMT/MMT#269]
I am able to rename directories and engine is started using new name, but when I do GET /domains I still see the old one. Is there some reference on DB ?

**Comment by EtienneAb3d** [comment]
There is only one engine on a given port. If you ask for "/domains" on this port, you're getting it's content. Suppose you have an engine named EngineA containing domains Europarl and MultiUN. Renaming this engine to EngineB won't change the fact that it's domains are still Europarl and MultiUN.

**Comment by davidecaroselli** [comment]
Hi @rptl 

just like @EtienneAb3d said, renaming an engine does just that: renames the engine. It doesn't rename any of the domains, nor it changes the ports the engine runs on.

Not quite sure what you want to do, so here's some tips:
- If you want to run an engine on different ports, or you want to run multiple engines on the same machine, this is how you can do that: [How to - run multiple engines on the same machine](https://github.com/ModernMT/MMT/wiki/FAQs#q-how-can-i-run-multiple-engines-on-the-same-machine)
- If you want to just rename an engine, so that it changes its name in the `mmt start`,  `mmt stop`, `mmt status` and so on, you can (1)  stop the engine and (2) rename the folder inside `MMT/engines`.
- If you want to rename a single domain (i.e. "Europarl" into "European Parliament") unfortunately this is not available right now, but if you find it useful we can implement such feature.

If I could not understand what is your actual need, or if you have any doubts about the translation process and/or the architecture, please don't hesitate to ask it here.

Thanks!

**Comment by rptl** [comment]
Hey @davidecaroselli, thanks.
My ask was about how to rename a single domain. To be honest, I don't think it will be used often, I just wanted to adjust a typo on my current domain name.

**Comment by davidecaroselli** [comment]
@rptl got it!
I will work on this API in the next days; I'm going to push the code in the **master** branch asap.

Thanks for your patience.

**Comment by davidecaroselli** [comment]
Hi @rptl 

the new API and command is available in the latest commit () of **master** branch. You can update your distribution rebuilding it from source, here's the instructions: [Installing from source code](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors).

You can now use the `mmt rename` command like this:
```bash
./mmt rename "europarl" "NewName"
```

Or you can use directly the [API Update Domain](https://github.com/ModernMT/MMT/wiki/API-Update-Domain) like this:
```bash
curl -X PUT http://localhost:8045/domains/1?name=NewName | python -mjson.tool

{
    "data": {
        "id": 1,
        "name": "NewName"
    },
    "status": 200
}
```

Thanks for your support, we are closing the issue right now but if you have any other questions please don't hesitate to re-open it!

**Comment by rptl** [comment]
Thank you so much to take your time to create it. Really appreciated.
