### ISSUE TITLE
Tuning error 

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#271]
Hi Andrea and Davide,

I am opening a new issue for the tuning error. 

First, I upgraded to the latest release "1.0.3" to see if this would resolve the issue, but apparently it didn't. 

Here is the error again at step (3 of 4) Tuning.... The duration of each first 2 phases is also strange. "6s for tokenization" and '0s for merging corpus...."!!!!! Is this normal?

> `INFO: (1 of 4) Corpora tokenization...                                 DONE (in 6s)
> INFO: (2 of 4) Merging corpus...                                       DONE (in 0s)
> INFO: (3 of 4) Tuning...                                               DONE (in 5s)
> 
> ERROR Unexpected exception:
>         Command '/root/ModernMT/cli/opt/mert-moses.perl /root/ModernMT/runtime/default/tmp/tuning/corpus.en /root/ModernMT/runtime/default/tmp/tuning/corpus.ar /root/ModernMT/cli/opt/mertinterface.py /tmp/tmputq3Uv --threads 4 --mertdir /root/ModernMT/build/bin --mertargs '--binary --sctype BLEU' --working-dir /root/ModernMT/runtime/default/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table --bleuscorer /root/ModernMT/cli/opt/mmt-bleu.perl --bleuscorer-flags "-nt" --early-stopping-value 1 --predictable-seeds --maximum-iterations=25' failed with exit code 2`
> 

I have also uploaded the logs @

https://we.tl/VBxjWi7U5k

Please let me know how to resolve this issue.  Could this be a memory issue? 

One more thing: is there a way to know if my old engine is compatible with the latest release? If it's working fine after upgrade and grabs translations from the server, does this mean that it's compatible and it doesn't need porting? 

Also, what is the command to get the current installed version of ModernMT?

Thanks again for your support.

Kind regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

Thank you for the logs, they are really helping me to understand the issue.

As for the duration of the first two tuning steps, don't worry, they seems just fine to me.  
Those steps are usually really fast: using 10M words for training, when I perform tuning those steps take 2s and 0s respectively, so I think everything is OK there.

It doesn't look like a memory issue either. 

As for the compatibility, if your old engine was v1.0 or more recent, it is directly compatible with v1.0.3.
You can find more information on backwards compatibility [here](https://github.com/ModernMT/MMT/releases/tag/v1.0.3).

To check your MMT version, please check the README.md file in your MMT home folder: it should contain.

To give me even more information on the problem, could you please run `./mmt tune --debug -e <your_engine_name>` and send me the resulting log folder? It would be really useful.

Thank you for your patience!

Best,
Andrea

**Comment by AndRossi** [comment]
Hi again @mzeidhassan,

One more thing. In the logs folder that you have just sent me I can't find the `node.log` file. 
`node.log` is generated during the engine creation, and is updated with information on all the activities performed by the engine (so it would be quite useful for solving this issue).
  
Can you please double-check if that file is missing in your logs folder? It would be really weird, and it would be an important symptom of the issue you are experiencing.

Thank you again.

Andrea

**Comment by mzeidhassan** [comment]
Hi @AndRossi ,

Thank you so much for your prompt follow-up and support. Yes, the node.log was missing indeed. Sorry about that. I have uploaded the requested folders now 

https://we.tl/HCjsXmtL9w

Please let me know.

thanks,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan,

From the data you have sent me, it seems that corpus 10 in your tuning set only contains one line, that is " 0 ". Can you confirm this?
You can find your tuning set in path `<your_mmt_home>/engines/<your_engine>/data/dev`.

If this is the case, it is possible that this odd line has raised your issue.
To check if it has, you can try to temporarily remove both 10.ar and 10.en files from your tuning set and try to perform tuning again.

Please let me know if this works!

Andrea

**Comment by mzeidhassan** [comment]
Hi @AndRossi ,

Thanks for your support. 

You are right. The corpus 10 files have only one line. I removed them and ran the tuning again. This time, it worked for 723 seconds, but failed again. I tried it again, and the second time, it failed after 95 seconds. 

In the mert.log file, it seems that the issue is cuased by the decoder. I see this in the last line of the file:

`The decoder died. CONFIG WAS -weight-overwrite 'PhrasePenalty0= -0.137940 DM0= 0.015334 0.018113 0.042342 0.020316 0.261833 0.126704 0.067011 0.030089 WordPenalty0= -0.075074 Distortion0= 0.033556 Sapt= 0.027740 0.039156 0.004247 0.012173 InterpolatedLM= 0.088372' `

I uploaded all files again to you @
https://goo.gl/DECyw9

Thanks again Andrea for taking the time to look into this.

Best regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

It seems the same problem as before, so maybe there are some more weird lines to handle.

I have written a small script in order to find the problem lines.
Please download it and extract it in your MMT home folder. 
Then, with your engine running, go to your MMT home folder and run command `./contextTest -e <your_engine_name> -s ar`.
The script will generate a file named `result_file`; could you please send it to me?

Thanks a lot for your patience and cooperation!

Andrea

[contextTest.gz](https://github.com/ModernMT/MMT/files/1292024/contextTest.gz)

**Comment by mzeidhassan** [comment]
Hi @AndRossi,

I uploaded it to Dropbox at

https://www.dropbox.com/s/f9ippy0tg7td7dk/result_file.zip?dl=0

Thanks again Andrea for your great support and patience!

Kind regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

Sorry for keeping you waiting.
I have pushed a fix in our **master** branch with commit a51f2f0.

If you have installed MMT from source, to download the fix you can open a bash shell, go to your `<mmt_root>` folder and run `git pull origin master`.  
You can now try to perform the tune and it should not raise that problem.

Please let me know if the solves your issue!

Have a nice day

Andrea

**Comment by mzeidhassan** [comment]
No problem, Andrea! I know it must be very busy at your end. I appreciate your support.

I updated my instance, but unfortunately I got the error again after a while. 

I uploaded the logs and tuning folder again 

https://we.tl/0GQM1nwmIW

Please let me know if you want me to run contextTest script again.

Sorry for all the trouble this is causing, @AndRossi!

Thanks again!
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

This is really weird. I thought that my last commit would fix the problem. 
Could you please run this other script I have written, and send me the result as before?  
  
The steps to run it are the same as those of the previous script.
The only difference is that to execute you must type `./contextTest -e <your_engine_name> -s <your_source_language> -t <your_target_language>`.
It will generate a `result.txt` file. 

Thank you again for your patience!

Have a wonderful day,

Andrea

[contextTest.gz](https://github.com/ModernMT/MMT/files/1303873/contextTest.gz)

**Comment by mzeidhassan** [comment]
Hi @AndRossi,

Kindly find the result file at

https://www.dropbox.com/s/10h6mygvz7gmclg/result.zip?dl=0

Thanks again for your support and follow-up.  I hope we will finally be able to figure this out.

Thanks a million!

Have a great day and a wonderful weekend ahead!

Mohamed

**Comment by mzeidhassan** [comment]
Hello @AndRossi,

Sorry for bothering you again. Did you have a chance to look into this?

I would like to import more TMX files. Do you think I should wait till we resolve this issue? 

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 

Thank you for the script result.
Sorry for keeping you waiting. In these days I’ve been investigating your bug, and it seems that one of the domains in your DB is not working as it should. 

I’ve just committed on `master` a hot fix that should let you ignore the problem domain. This should allow you to perform the tune.

However, this is a strange issue indeed, and we would like to do further investigation on it.
Could you please compress and send us your folders:
`<your_mmt_root>/engines/<your_engine>/models/db` and `<your_mmt_root>/engines/<your_engine>/models/context`?

Please let me know if with this hot fix, everything goes well.
Once again, thank you for your patience and support.

Andrea

**Comment by mzeidhassan** [comment]
Thanks @AndRossi for your continuous support. I really appreciate it.

I have updated it and it's running now. I will let you know if I have any issues.

I compressed the context directory and it's almost 1 GB. I have a question though:

Would this contain any confidential content from customers, i.e. translations? 

Do you think it's better to install everything from scratch and start retraining? You told me that the neural engine will be ready soon. Do we need to do the whole training from scratch again once the NMT component is integrated? If this is the case, then I can just wait.

One last thing:
Does this recent fix have an impact on the tuning process, hence it will impact the MT output quality? 

Thanks again for your support!

Kind regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan 

I understand your concerns. 
The db folder only contains information on the names of your domains, so it should not be a problem.
The context folder contains the **source part** (not the full translation) of all the corpora you used for training or imported in your engine. It does not contain any data on the translations requested at run time. Is that a problem to you?
 
As for the neural engine compatibility, unfortunately yeah, in order to use it you will need to retrain your engine from scratch. We are aware that this is very unpleasant, but the neural models are just so different from the phrase-based ones that there is no way to make a porting.  
A the moment, I would not suggest you to install everything from scratch and start retraining: you can wait for the neural release to do that :)

The hotfix I have committed will let you perform tuning skipping the domains that raise your issue, so it will impact your translation quality – but it’s hard to tell how.

Your issue is extremely weird: your domains do exist in your DB and they are used in the first steps of tuning. However, when the program tries to use them, they suddenly behave like they are not there, in a sort of ghost-like fashion. That’s why we are so determined to investigate on it :)

I hope this answers your questions!

Kind regards,
Andrea

**Comment by mzeidhassan** [comment]
Thanks Andrea for your clear answer. OK, I will upload these directories and send you a link. Is there a way to send you a message directly and not posing the link here on github? Is this possible?

By the way, the hotfix worked and the engine was tuned. I got a Final BLUE score of 44.57.


Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

I'm glad the hotfix worked. 

You can send the link to my mail address: andrea@translated.net  
Thanks a million for your support. We really appreciate it! 

I'll keep you updated.

Kind regards,
Andrea

**Comment by mzeidhassan** [comment]
@AndRossi Email sent! Thanks again for your support!

Look forward to hearing from you.

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 

I apologize for the very delayed response. 
We've been quite busy with the new neural releases lately, so I haven't had much time for investigating this issue until now.

However I have good news :)
I believe that with the commits and fixes we have pushed in the last weeks this issue was solved.  

More in detail: I have replicated your issue on an old 1.0.3 engine using the context and db models you have sent me a while ago. I found out that the context analysis tried to use a domain (domain 14) that apparently was not contained in the `domains` table in the DB. 
That was the reason why the tuning failed.  

Having domains in the context analysis models and not finding them in the `domains` DB table should not be possible, so I'm not really sure about what has caused this; maybe a Cassandra inconsistency?

However, some of the our recent commits (and my old hotfix!) should definitely prevent situations like this. So, since this issue seems finally solved I'm going to close it.

Of course, if you need further support do not hesitate to re-open this issue :) 

Have a nice day, and thanks again for your patience!

Andrea
