### ISSUE TITLE
Handling of DNTs "DO NOT TRANSLATE" strings/text?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#275]
Hello MMT team,

Is there a way to tell MMT to protect some text and don't translate them whether this is text between tags or say "All CAPS", CamelCased, or concatenated text for example?  

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan ,

you can use any XML tag in order to specify DNTs. In fact XML is stripped out from the text and projected back after the translation untouched. For example you can translate the sentence:
```
Gilmour is the leader of the <dnt text="Pink Floyd" />
```
the translation is:
```
Gilmour è il leader dei <dnt text="Pink Floyd" />
```
At this point it should be very easy to parse the result and unwrap all the <dnt> tags replacing them with the inner text.

Hope this helps!

**Comment by mzeidhassan** [comment]
Thanks Davide for your answer! This is what I was looking for. I appreciate it. I am closing this issue.
