### ISSUE TITLE
Neural training: out of memory

### ISSUE THREAD

**Issue by ya5an** [ModernMT/MMT#280]
$./mmt create en it examples/data/train --neural
[...]
INFO: (6 of 7) Preparing training data...                              DONE (in 18s)
INFO: (7 of 7) Neural decoder training...                             /home/mmt/mmt/build/lib/pynmt/nmmt/NMTEngineTrainer.py:177: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()
/home/mmt/mmt/build/lib/pynmt/nmmt/NMTEngineTrainer.py:177: UserWarning: self and mask not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  num_correct_t = pred_t.data.eq(targ_t.data).masked_select(targ_t.ne(Constants.PAD).data).sum()
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
ERROR Unexpected exception:
	RuntimeError('cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66',)

I use the GeForce GTX 760 with 2 GB of RAM
What are the minimum and normal memory requirements?

Thank you.

**Comment by EtienneAb3d** [comment]
You may hope starting doing something interesting with, perhaps, 6G. 
The best cost/performance solution, today, is certainly to get a GTX1080Ti with 11G.
;-)

**Comment by AndRossi** [comment]
Hi @ya5an, 

Thank you for trying our neural MMT!
During development, in training phase RAM usage is typically between 2 and 4 GB. (of course, it greatly depends on your dictionary and training corpora).
On the contrary, during translation the RAM usage is definitely smaller.

In our tests we tried several GeForce GPUs.
The GTX1080Ti suggested by @EtienneAb3d is certainly an excellent choice.
During development and testing we also tried the GTX1080 (sort of its "little brother"), that has 8GB of RAM, and we did not encounter any issues.

**Comment by EtienneAb3d** [comment]
Can you explain in what kind of conditions you got 2GB to 4GB at training time?
In my case, I'm training with 16M sentences pairs (well known sets: Europarl, MultiUN, Wikipedia, ..).
What is the main factor for memory usage? Number of sentences ? Size of sentences ?

**Comment by AndRossi** [comment]
Hi @EtienneAb3d, 

we got those values while training an en-it engine with 100M words on a GTX1080.
As long as we observed the memory usage, it always stayed between 2GB and 4GB; it is possible of course to have higher (temporary) peaks, but we are confident that in average the memory usage did not "explode" like in your case.

However, according to our tests the required memory mostly depends on the vocabulary, and not on the training set size, so it is really hard to make estimates before training the engine.

**Comment by EtienneAb3d** [comment]
In my log, I don't find any word count. Here is what can be noticed:
`2017-10-10 14:27:35,275 [INFO] - Prepared 16634611 sentences (0 ignored due to length == 0)`
`2017-10-10 14:29:25,442 [INFO] - Vocabulary size. source = 93740; target = 84020`
`2017-10-10 14:29:25,442 [INFO] - Engine parameters: 139740020`
`2017-10-10 14:29:25,443 [INFO] - Engine metadata: {'layers': 2, 'rnn_size': 500, 'tuning_optimizer': 'sgd', 'dropout': 0.3, 'context_gate': None, 'tuning_max_learning_rate': 0.2, 'word_vec_size': 500, 'input_feed': 1, 'tuning_max_grad_norm': 5, 'brnn_merge': 'sum', 'tuning_max_epochs': 10, 'brnn': True, 'rnn_type': 'LSTM'}`
`2017-10-10 14:29:25,443 [INFO] - Trainer options: {'report_steps': 100, 'log_level': 20, 'steps_limit': None, 'learning_rate': 1.0, 'max_generator_batches': 32, 'early_stop': 10, 'batch_size': 64, 'lr_decay_start_at': 50000, 'checkpoint_steps': 10000, 'validation_steps': 10000, 'n_avg_checkpoints': 5, 'max_grad_norm': 5, 'optimizer': 'sgd', 'lr_decay': 0.9, 'lr_decay_steps': 10000}`

Counting words by myself:
`wc -w *.fr`
`543414278 total`

On this card, I usually train 2x1000 ONMT models, with batch_size 100, word_vec_size 200, a 50K vocab for each language, and it takes about 10GB.
Reducing the batch_size and/or the layer size drastically reduce the memory load. Of course, word_vec_size and vocab size should certainly also have an important impact.

**Comment by AndRossi** [comment]
Hello again @ya5an and @EtienneAb3d, 
after this issue I have added a new constraint check for the Neural engine: if your GPU has less than a fixed, minimum GPU threshold (2GB at the moment), MMT now warns you that you may have trouble with your training.
This is a small feature but I hope it makes the system a little more user-friendly.

I am closing this issue now, but for any doubt do not hesitate to reopen it.

Thank you for your support!

Andrea
