### ISSUE TITLE
Neural MMT : how to tune the tokenizer ?

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#286]
In some sentences, I'm replacing some parts with codes like "Code5e". When translating these sentences with a neural MMT engine, it is certainly tokenizing on it, providing an altered result "Code?", or "Code5" or "Code?e" in the translation.

How to avoid this ?

In fact, for the moment, my sentences, in both training time and translation time, are already tokenized. Is it possible to simply ask MMT to tokenize on spaces ?

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

I think that the easiest solution is to take advantage of the fact that MMT recognizes and does not translate tags.

Is it possible to you to use tags like `<Code5e>` instead of normal strings like "Code5e"?

For instance, using an engine with language pair en -> fr, "This is not an <code5e> example." should translate to "Ceci n'est pas un <code5e> exemple".

**Comment by EtienneAb3d** [comment]
A tag would be possible, but won't be handle like an unknown word, isn't it ? This could make a difference in the way the sentence is translated. 
For example, suppose the code is a date (that will be translated with a rule-based translator to ensure the result to be correct). With a tag in place of the date, the sentence will be translated as if the date was simply deleted. This is not the same as translating the sentence with a unknown word/code in place of it.
Remark : your example is strange, perhaps a tag is badly displayed.

**Comment by EtienneAb3d** [comment]
Of course, I could use a letter-only-code, or even a neutral code to be removed afterward near a tag.

But, more generally, it's not a good behaviour to alter such letter combinations, and not handle them as single words. They could be some important acronyms to be kept unchanged.

**Comment by AndRossi** [comment]
Whoops, there was a display problem with `<code5e>` tag. I have now fixed it.

I now understand what you meant: your code parts are still part of the sentences, so they must be considered as "words" anyway (even though they must not be processed and translated).

In this case replacing those parts with tags, as you pointed out, would change the source sentence, and it would affect the translation output. 

Unfortunately, at the moment there is not a way to skip tokenization (that is, you can choose to skip some steps in the training phase, but you can not avoid that in translation and tuning, so this would not be useful in your case).

We will work on this feature and let you know as soon as it is ready.

In the meantime, as a temporary solution I think that you can build untranslatable "words" as pseudo-randomic sequences of letters.
(I think this might suit your case if you have a limited, pre-defined set of codes).

Of course, as you said, this is not a best practice due to the possibility to interfere with acronyms, but for the time being it can be a hotfix (and using pseudo-randomic strings of the right length should minimize that risk). 

If you choose to use this temporary solution, just make sure that not even substrings of your pseudo-randomic strings make sense in the source language (i.e. sdab**get**saifb contains "get"). Otherwise, in neural engines the BPE system might try to translate just that substring.

**Comment by EtienneAb3d** [comment]
I think, the best solution is certainly to use single a neutral keyword, like XXXX, and put near it a tag with the code in it. The neutral keyword will be deleted afterwards in the translation, and the tag replaced by the wanted final text.

But, this won't solve the problem of BPE sub-tokenization, and certainly bad translation, of acronyms and formulas. Except if I also replace them in a pre-processing...

**Comment by AndRossi** [comment]
Hi @EtienneAb3d, 

Since you found a workaround using neutral keywords, I am closing this issue now.
The tokenization skip feature, however, is still to be implemented; you can follow updates on that topic [here](https://github.com/ModernMT/MMT/issues/248).

Thank you for your patience and support. 

Have a nice day!
Andrea
