### ISSUE TITLE
Neural MMT stop criterion...

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#287]
I first trained a FR->EN model. It took 3 days, and stop with these small variations:
![image](https://user-images.githubusercontent.com/25932245/31788011-ad4633a0-b50d-11e7-817b-4bf813c6ae6a.png)

Here is the end of the LOG file:
![image](https://user-images.githubusercontent.com/25932245/31788357-bb561090-b50e-11e7-90b7-fd7b52e3345e.png)

Now, I have the same data training the EN->FR model, still running after 6 days, with these values. I don't understand why it doesn't stop like the previous one:
![image](https://user-images.githubusercontent.com/25932245/31788585-72a96eea-b50f-11e7-972d-558113a4df19.png)

PS : bad screen copy updated

**Comment by nicolabertoldi** [comment]
the termination policy is the following:
at each validation point, which is every 10000 steps by default, the perplexity is taken into consideration. If, at a given validation point, the  perplexity does not improve with respect to the best perplexity ever, the learning rate is decreased and the status of the training is set to stalled, otherwise (i.e. if the perplexity improves) the learning rate is maintained and the status is set to not-stalled. If the status of the training is stalled 10 (by default) consecutive times, the training terminates.

In other words, training terminates whether ten consecutive reduction of the learning rate cannot improve the perplexity on the validation set

You can understand this behavior by checking the line "Validation perplexity"  (immediately after "Validation Set" in your log.

In my current training:
on perplexity at step 70000 (epoch 0.78): 8.647378; new best: 8.647378
2017-10-20 02:17:38,990 [INFO] - Validation Set at step 80000: loss = 2.10317, perplexity = 8.19211, accuracy = 64.4031
2017-10-20 02:17:38,990 [INFO] - Validation perplexity at step 80000 (epoch 0.89): 8.192110; new best: 8.192110
2017-10-20 03:20:20,502 [INFO] - Validation Set at step 90000: loss = 2.11602, perplexity = 8.29805, accuracy = 64.3118
2017-10-20 03:20:20,502 [INFO] - Validation perplexity at step 90000 (epoch 1.01): 8.298047; current best: 8.192110; stalled 1 times
2017-10-20 04:23:14,165 [INFO] - Validation Set at step 100000: loss = 2.01682, perplexity = 7.51437, accuracy = 65.2953
2017-10-20 04:23:14,166 [INFO] - Validation perplexity at step 100000 (epoch 1.12): 7.514372; new best: 7.514372
2017-10-20 05:27:11,948 [INFO] - Validation Set at step 110000: loss = 2.05047, perplexity = 7.77156, accuracy = 64.7318
2017-10-20 05:27:11,949 [INFO] - Validation perplexity at step 110000 (epoch 1.23): 7.771560; current best: 7.514372; stalled 1 times

and actually it is still running because it has been stalling for 1 time only



feel free to ask more clarifications

**Comment by EtienneAb3d** [comment]
Your method seems very elaborated. The problem a see, is that, if the validation set selected at the beginning is very close to the training set, it could take a very very very long time to reach the criterion. On the contrary, if the validation set is very far from the training set, it can terminate very early.

**Comment by nicolabertoldi** [comment]
I agree that if the validation set is very similar to the training data the training could continue long long time. However, I am not totally sure that you are right in the other case, when validation set is far from the training.

Said that, I forgot to mention that there is an additional termination policy to stop the training after a fixed number of step. Its default is infinite, but it could be changed in the command line using the parameter "--step-limit".
Or if needed there is always the much more drastically possibility to kill the training process "mmt create" by means of the signal "2". In this way the training process terminates and the engine is well created exploiting the last checkpoint.

**Comment by EtienneAb3d** [comment]
Good news ! First, I will perhaps use the killing solution.. and later, certainly I will add a step limit..

For the question about the far validation set, the logic is quite simple. The system is optimizing the PPL on the training set, thus the function Y=PPL(X) is constrained by the training set, and is not really constrained outside of the training set (except by the regularisation). So, it's an evidence that a very close validation set will possibly also improve their PPL for a very long time, making the criterion hard to reach. On the contrary, on a far training set, the PPL function has a random behaviour, because not really constrained. On the principle, the farther it is, the more random it can be. With a highly random behaviour, a far validation set will possibly reach the criterion very quickly.

**Comment by EtienneAb3d** [comment]
Knowing your training strategy, rather than a criterion "stop for N steps max", I would prefer to have a "stop for LR min". It would be much more coherent. Your strategy can produce either a low LR decreasing, or a fast decreasing one. The number of steps is not really the best way to describe a given learning situation. The LR is much more accurate. 

Rather than looking at the validation PPL for your criterion, I would prefer looking at the validation accuracy. The PPL is an evaluation of the confidence of the network. It can produce a bad translation with a good PPL (good confidence), or produce a good translation with a bad PPL (bad confidence). The best way to know if something is really improving or not, is the validation accuracy.

The way you are choosing your validation set is really important. It must not be too close to the training set. The bad thing is that there is often very similar sentences in many corpus. Here is the strategy I'm using with my ONMT training: 
1) randomly select a validation set
2) remove from the training set all sentences pairs colliding with a validation pair when applying a transformation of the text to a key form. If the key form is indexed in a hashmap, it's trivial to do on the fly.
To obtain the key form of a sentences pair:
1) put all in lower case
2) remove accentuations
3) replace all "1234" numbers by a single "8"
4) remove all punctuations, and some other chars like currencies
5) you may also remove all stop words
6) you may also lemmatize or stemmatize

**Comment by AndRossi** [comment]
Hello again @EtienneAb3d, 

Thank you for your suggestions. We will definitely take them into account in our next MMT neural engine improvements!

For the time being I am closing this issue. Of course, if you want to share with us further contributions or if you need more details do not hesitate to re-open it.

Thanks again for your great support :)

Andrea

**Comment by EtienneAb3d** [comment]
Yes, I was just re-thinking at this, this morning.

Of course, the training set filtering, according to the validation set is important for a more pertinent evaluation.

But in fact, none of the possible evaluations is really perfect, neither to control the learning rather, nor to have a good stop criterion. In my own ONMT learning, I'm using a much more deterministic way of doing. It would be nice to add it in your options. It works by epochs ranges, for example 3:
1) first, do N1 epochs, starting with LR1, decreasing it by a X1 factor at each epoch (I'm using: N1=10, LR1=1, X1=1)
2) then, do N2 epochs, starting with LR2, decreasing it by a X2 factor at each epoch (I'm using: N2=15, LR2=1, X2=0.8)
3) finally, do N3 epochs, starting with LR3, decreasing it by a X3 factor at each epoch (I'm using: N3=25, LR3=1, X2=0.8)

Remark : often, I use to stop the whole training before the end of range 3. If this is not possible, I would use a shorter final run.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d ,

in the latest MMT release it is possible to start a training from an existing model. With this option it should be possible to achieve the kind of "training" you are suggesting.

1. Start a training from scratch with `step_limit = steps_per_epoch * N1 `,  `learning_rate = LR1` and `learning_rate_decay = X1`.
2. Start a second training from Model1 with `step_limit = steps_per_epoch * N2 `,  `learning_rate = LR2` and `learning_rate_decay = X2`.
2. Finally start a third training from Model2 with `step_limit = steps_per_epoch * N3`,  `learning_rate = LR3` and `learning_rate_decay = X3`.

You can interrupt the training at any step with Ctrl+C (or equivalent `kill -2 <pid>`), the training will copy the latest checkpoint to the `<engine>/models/decoder` folder.

Hope this helps!

**Comment by EtienneAb3d** [comment]
I would enjoy to discuss this a bit more.
For me, all your complex calculation with the validation set, to control the learning rate, is of no pertinence.
What is the justification for this ?

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

here's the idea. During the training of the neural net there are two phenomena that we want to monitor: the convergence of the model (with the perplexity) and the overfitting.

During the training the model keeps improving its ability to translate the training set, the more samples it sees, the higher the translation quality on both training set and validation set. There is however a moment in the training when the model has seen the same samples so many times that it starts to to overfitting, so even if the training perplexity decrease, the actual ability of the engine to translate unseen text become worse.

We control the overfitting constantly measuring the perplexity on an "external" set, that is not contained in the training set that is the validation set. It is in fact a "sample" of the actual content the engine will be requested to translate when in operation. If, for N times in a row (N=10 by default), the neural net keeps decreasing the translation quality on the validation set, we stop the training and we keep the last "good" checkpoint.

Now, if I understand correctly, you suggest that the perplexity on the validation set is not a good choice to measure the translation quality. I have not a strong research background in order to argument on that (I ask @nicolabertoldi or @mfederico to help me on that), however we made some tests in the past, and I also read this in other forums/github repos, and we saw ourselves that the perplexity is coherent with the BLEU score for example, so we've chosen to simply use the perplexity.

Have a nice weekend!

Davide

**Comment by EtienneAb3d** [comment]
Of course, the PPL is the way to learn : by increasing the PPL on the training set, the result is (normally) that the network will more likely produce the good translations on this training set. But, you can have a good translation with a bad PPL, or a bad translation with a good PPL. 

In my experiments, it's false that the PPL is correlated with the BLEU score on the validation set. It's perhaps true on the training set, of course, is your are properly learning it. But, I always observe that the BLEU score (or TER, or WER, ...) on the validation set is converging, not diverging. Of course you can get random variations, but it is mainly converging (and in fact, you can also argue that the BLEU evaluation is not the best way to evaluate, but this is an other discussion).

On the theory, overfitting has nothing to do with the single learning curve itself. It is linked to the bias/variance tradeoff. Thus, it has to be handle through several learning curves, and linked with 2 main thinks:
1) the complexity of the modelling function, thus the size of the network. If you have too much freedom degrees, the random behaviour of the function outside of the constraining learning set produces bad results on the validation set.
2) the regularization applied to the function that can enforce it to be smooth, thus limiting the random behaviour mention in the first point.

To control the overfitting, the validation set is only useful to choose the size of the network, or the regulation hyper-parameter:
1) given several size N of the network, and several regularization R, train several networks TILL THE BEST on the training set
2) choose N and R having the best evaluation, with their resulting fully converged model, on the validation set

What you are doing when decreasing the LR is a simulated annealing : just a way to find the best point. The animated gif on this page is really a good visualization : the better the point, the longer the time spent in the zone, the higher the probability to stay in it.
https://en.wikipedia.org/wiki/Simulated_annealing

Having this in mind, the only think you have to do is to choose the best decreasing rate according to the kind of system you are annealing. Several successive annealing can also be useful to get the better result.

**Comment by mfederico** [comment]
Hi

Theory is ok but we need also practical methods to train networks, which boils down to different possible
recipes. The fact that there are different recipes tells that the problem is not solved yet. However, the fact
that these recipes are quite similar to each other also suggests that there is quite some consensus 
about best practice to approach the problem. Told this, I encourage everyone to explore and test new 
methods. We did not really develop ourselves the recipe we are using in MMT. It is based on others’ work. 

The rationale: 
- PPL is really equivalent to the loss function used to train the model (=cross-entropy). 
- The method implements a plain cross-validation method, i.e. regularly validate the model on external data.
- Check points are done after model updates that covered the training data only partially
- The stopping criterion looking at N check-points considers: 
	- possible random fluctuations due to the SGD procedure
	- possible local minima to escape from (sort of simulated annealing?)

The stopping criterion is clearly not perfect nor definitive. Cross validation is a very well know method to avoid
a NN overfitting the training data, together with drop-out and regularisation. We do not aim at model selection 
mainly because it is computationally too expensive. Last but not least, the trade-off between generalisation and 
overfitting is rather flexible in machine translation. There are tasks with very repetitive texts, hence 
overfitting becomes rather natural,  while others require to adhere to a precise style and terminology, hence
some overfitting is even requested. 


Marcello

**Comment by EtienneAb3d** [comment]
Early stopping is a fake solution. Either in the theory, or in my own experiments, a learning system (like NMT) is not good at one time of its training, and bad afterwards in this same training. The validation curve (for example BLEU score) is quite monotonic, correlated with the training curve. You don't need a complex way of calculating the LR and the stop criterion. A simple deterministic way of managing it is sufficient, with a few pragmatic tests to adjust the details. Managing a simulated annealing is something quite simple. Your complex calculation is just introducing uncomfortable uncertainty on the time it will takes to reach the final solution, with a risk that it stops so early that you will stop on a really not optimal one.

**Comment by mfederico** [comment]
Quoting you: 
"A simple deterministic way of managing it is sufficient, with a few pragmatic tests to adjust the details." 
Could  put down the method you are referring too or give us a reference?  Thanks.

**Comment by EtienneAb3d** [comment]
Just above, something like this (with parameters that can be tuned):
https://github.com/ModernMT/MMT/issues/287#issuecomment-342811721

**Comment by EtienneAb3d** [comment]
You said:
"Cross validation is a very well know method to avoid a NN overfitting the training data"

Yes, of course. But, as I explained in a previous post above, the cross validation is made to choose the good size of the network and its hyper-parameters (like a drop-out regularization factors). The cross-validation is not made to stop the training before the end of the convergence.

Take a very simple illustration: suppose your are trying to build a parabola over 2 training points. There is an infinite number of ways to have a parabola exactly matching over 2 points. Due to the fact that there is too much parameters to choose in the model, the model behaves randomly outside of the training points, where there isn't any constraints. During the training, you can get whatever form to the parabola, while monotonically decreasing the distance to the 2 training points. It's not because you are stopping your training before reaching the 2 points, with a criterion detecting you are going away from a third point at one moment, that this stopping is pertinent. You can be very very far from the best solution at this moment, and a much more better solution can occur afterwards in the training.  The more pertinent way of doing this training is to reach the convergence, thus build a parabola exactly matching the 2 points, and use the third point to decide that a linear model is (certainly) much better than a parabola (supposing the 2 points are significant for the function you want to build). Considering only one training curve, the third point can also inform you that a given converged parabola is certainly very bad solution, and thus, that you have to reduce the size of your model, or increase its regularization hyper-parameter to make it more 'smooth' (more linear, in fact, in this extremely simplified case).

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d ,

I find interesting what you're proposing: it's simpler, and you're saying is the best solution to increase translation quality. I still have some doubts or details I would like to discuss.

**Training steps vs. epochs**
In my experience I found two main schools of thought. The first bases the training upon epochs, so that the "clock" is in fact the number of epochs: every parameter is changed, every condition is evaluated when an epoch ends. OpenNMT, for example, uses this logic.
On the other hand, there are tools (TensorFlow for example) where the number of updates (or epoch) is used as a reference for the training status.

The difference, I think, is deep: the first puts accent on the data, saying that the net needs to read the same data at least X times (epochs) to learn them properly; the second on the contrary put accents on the net itself, saying that a net with a certain size needs to look at X samples (not necessary the same samples) before being properly trained.

Of the second approach I personally appreciate that the training time does not increase linearly with the size of the training set, but it's a "property" of the net (given the net, you need X updates to training it).
Your process however is based on epochs, do you think this is a key aspect of the process you suggested? Do you think that the epoch-based approach is the only valid method?

**Adapting parameters to context**
With MMT, we always wanted to create a tool that makes the ease of use a fundamental aspect of its functioning. So we want to have (1) reasonable default values and (2) change the behaviour automatically without requiring the user knowledge of the training process.
The process you explained is quite "fixed": once you found the best N(i), LR(i) and X(i) the training process will always be the same regardless the training set size, content or diversity.

Our procedure aimed to implement a _feedback_ from the network during the training (with the validation set) and to behave accordingly. Do you think that this aspect can (or should) be implemented in your process?

Davide

**Comment by EtienneAb3d** [comment]
**Training steps vs. epochs**
I would rather agree with the your "training" point of view : for each epoch, my training set is always nearly of the same size, thus my ONMT epochs are always equivalent to the number of times the network is seeing sentences. But, I'm training ONMT in-domain models, mixing in-domain data with generic ones. The size of my epoch-training set is large enough to contains at least 1 time the in-domain data I want to train, being a least 20% of the volume. In fact, my way of doing can be thought as an intermediate point of view... but much more near the "training" than the "epochs" one.
**Adapting parameters to context**
You can be adaptive. But, keep in mind that, what you want, before all, is to learn the training data. In the idea of a simulated annealing, you need to do this adaptation looking at the training results, not the validation ones: 1) as long as the mean value of the training PPL, calculated on last N steps (for example), is enough decreasing, keep the same LR, 2) when you no more really gain on the training PPL, decrease the LR. There is just a good formula to find, taking into account that the PPL is in different kinds of ranges on each part of the curve. An idea would be: each time you have a new LR, calculate the PPL progression on the first N steps, and use it as a reference to decide when to change to a lower LR. Stop all when the LR is under a given value. 
Of course, the validation scoring is also an interesting value that can be calculated and shown. Especially, the final values are interesting, for the overfitting evaluation of the final converged model.

**Comment by EtienneAb3d** [comment]
To build an adaptive method, I would rather use an evaluation like WER to control the LR, rather than PPL. The real goal that should control the learning system, is the way it is gaining on the translation quality, not the confidence it uses internally to build the translations.
In the same way, since you are changing the training set at each step, I would build each training set with a lower probability to choose sentences already well translated (but never a null probability, you need to check they are always well translated). 
Be careful, lowering the probability of the best translated sentences is not the same as increasing the probability of bad ones. Often, training sentences that are (very) badly translated by the model, are really bad sentences that would rather need to be eliminated from the training set.
http://forum.opennmt.net/t/automatic-training-corpus-filtering/429

**Comment by mfederico** [comment]
Hi, 

this is actually similar to what we do. You can find the description in our paper:

http://www.statmt.org/wmt17/pdf/WMT13.pdf <http://www.statmt.org/wmt17/pdf/WMT13.pdf>

**Comment by EtienneAb3d** [comment]
Nice paper, that really clearly explains how MMT is working, especially at the translation time.
Is there a place where all such papers can be found ?
:)

**Comment by EtienneAb3d** [comment]
@mfederico, in your above paper, what about the drop-out parameter used at the model live update time ? As far as I read it, you don't explain something about it.

**Comment by mfederico** [comment]
Hi, the drop-out parameter is set to 0.0.

**Comment by EtienneAb3d** [comment]
Since one of your your major problem is overfitting, wouldn't it be better to set it to a quite high value ?

**Comment by mfederico** [comment]
When try to avoid overfitting the selected instances by controlling the LR and the number of iterations. 
I guess these are enough hyper-parameters to control.

**Comment by EtienneAb3d** [comment]
You even didn't tried with a drop-out ? Perhaps, with this parameter set, at least, to a commonly used value (for example 0.3), you would have much less problem to control the others.

**Comment by mfederico** [comment]
I don't think is s good idea. With such little training data (1 sentence pair) it would just introduce annoying random effects. 


-------
Short from my mobile phone

**Comment by EtienneAb3d** [comment]
It worth a try ! The drop-out, especially in the encoder side, would show the model how to behave even with small variations in the entry. And the sentence you want to translate is supposed to be a variation of the reference one. Rather than pulling the network on one single point, that would hardly induce overfitting, it would smoothly influence it on a blurred set of distributed points, thus possibly less hardly enforce it to bend on a too local place.

**Comment by EtienneAb3d** [comment]
Why not using more than 1 sentence pair? With, for example 3 or 5, the network re-training would then play the role of a kind of KNN-interpolator. This would be a radical change in the spirit of the game..
My 5 euros guess would be: use the 5 nearest neighbours, with drop-out 0.3... and your other hyper-parameters choices will possibly become of very secondary importance.

**Comment by mfederico** [comment]
Hi, sure we tried many different options, also including those you are mentioning. 
The paper presents what finally worked best. However, we have further and significant 
improvements of the method of the paper that we are submitting to a journal paper
and that I cannot reveal for obvious reasons. Once the paper is submitted we will add 
them to the MMT implementation too.

**Comment by EtienneAb3d** [comment]
Thinking a bit more at this I would add one more element: use fixed input/output embeddings.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

we have some important updates on the termination policy. After a very large range of experiments (14 translation directions) we have tested many options and we decided to change our termination policy: we confirmed some of your suggestions!
- The training process saves the last 20 checkpoints (you can change this with `--checkpoints` option)
- The training process stops based on validation perplexity: if the new checkpoint does not improve the average validation perplexity of the last 20 checkpoints, the training is interrupted. More in details the training is stopped at *ith* checkpoint if 
`PPL_AVG(checkpoint[i-21] ... checkpoint[i-1]) - PPL_AVG(checkpoint[i-20] ... checkpoint[i]) > 0.0001 `
- The final checkpoint is calculated as the average of the last 20 saved checkpoints.

We didn't changed the learning rate decay algorithm: learning rate is reduced only if the validation perplexity increased.

This configuration gave us the best and more robust results on all our tests.

**Comment by davidecaroselli** [comment]
Hi all,

I'm closing this issue for now. As always: if you have any other issue, or want to discuss more, don't hesitate to re-open the discussion.
