### ISSUE TITLE
advice for local hardware setup for cluster of 2 nodes (for 20 neural engines)

### ISSUE THREAD

**Issue by mindaugasDEV** [ModernMT/MMT#290]
Hi, @AndRossi 

I have tested Neural MMT with a decent Desktop configuration:
Intel i7 CPU; SSD 125; 16 GB RAM; GPU GF 1080.

Training time: to training one engine from 1gb parallel data it took 1,5 days. Really not bad, considering that you don`t need to train so often. Is it because of SSD disk? I did not expect such speed.
Translation time: 5 min for 2000 words (200 segments) XLF file . Not so impressive, we need better speeds.

Please advise what MMT cluster configuration shall we create for 20 neural engines:
- 6 engines - constantly used 
- 14 engines can be started manually as they will be used on weekly, but not daily basis.

Every engine will be trained from 1gb of data, therefore we might need 1 gb*20= 20 gb HDD as per documentation.

I am thinking of cluster setup to achieve:
- 2-3 days time for training an average neural engine with 1 gb of data
- 5-10 min for translating of modest 200-10000 words XLF files (even when there is a constant training of neural engine in background as we will have 20 engines, they will require training time to time)

Let me know whether the following setup would help me to achieve above goals.
- a decent server with 100 Gb HDD (not SSD) and with 32 GB RAM (shared with other processes, Virtual machines)
- a cluster of 2 MMT instances (virtual Ubuntu machines) 
- 2xGPU (1 for each MMT instance):  Geforce 1080, 8 Gb RAM (NOT Ti edition)

My question:
1. Will the above cluster improve TRAINING time? What is the percentage is the time savings, in comparison to single Virtual Machine? 20%?
2. Will the above cluster improve TRANSLATION time? What percentage is the time savings, in comparison to single Virtual Machine? 20%?
3. Do 2 GPUs help to achieve translation speed while engine is being trained in the background?
4. Are 2 GPUs 1080 better than 1 GPU 1080 Ti?

Thanks,
Mindaugas

**Comment by davidecaroselli** [comment]
Hi @mindaugasDEV 

first of all, the current version of MMT supports only single-GPU, single-node training: add more GPUs to the same machine, won't speed-up training time; add more node to the cluster won't speed-up training time.

Please consider also that training is a quite expensive process in terms of resources: a training uses almost all GPU resources, so you need to have a dedicated CPU-card for training. You can stop MMT and start training, or you can choose to dedicate an entire GPU only for training, but you cannot share a GPU for translation and training.

What I personally suggest is to train a "baseline" neural model once and then upload new data with the [Add to Memory API](https://github.com/ModernMT/MMT/wiki/API-Add-to-Memory). You can also setup a multilingual-engine, so that you will be able to use a single MMT Cluster for all the language directions you need.

Let me now answer your questions:
>Will the above cluster improve TRAINING time? What is the percentage is the time savings, in comparison to single Virtual Machine? 20%?

No, as I said, MMT can only use one GPU for training.

>Will the above cluster improve TRANSLATION time? What percentage is the time savings, in comparison to single Virtual Machine? 20%?

It will improve the **throughput**, not the single-translation speed. In fact, adding more nodes to the cluster, allows MMT to load-balance the inbound translations, but the time needed for the single request will be the same.

So, you said that a single instance of MMT can translate 200 sentences in 5 mins; if you add a node to the cluster you will be able to translate 200 sentences in (roughly) half the time, ~2m 30s, because you have now 2 workers, but every single translation request will still require 1.5s to be executed.

>Do 2 GPUs help to achieve translation speed while engine is being trained in the background?

As I said, you will need to dedicate an entire GPU to the training process, and if you want to continuously train engines in background, I suggest you to reserve a virtual instance only for that purpose.

>Are 2 GPUs 1080 better than 1 GPU 1080 Ti?

Faster GPU means faster translation, more GPUs means more throughput. It really depends on your needs, if you have batch of translations that must be done as quick as possible, I'd say go for more GPUs. If you have a realtime process where a user is waiting for a translation, you want to speed-up the translation speed, so go for a faster GPU (you **won't** of course get twice the speed).

Hope this helps! :)

**Comment by mindaugasDEV** [comment]
Thank you!
