### ISSUE TITLE
NeuralDecoder does not support N-best.

### ISSUE THREAD

**Issue by ya5an** [ModernMT/MMT#295]
Hello!
http://localhost:8045/translate?q=world&source=en&target=it&context=computer&nbest=5
Decoder 'NeuralDecoder' does not support N-best.

Does this have something to do with specifics of the technology?
How difficult it is to realize?

Thanks!

**Comment by davidecaroselli** [comment]
Hi @ya5an ,
it should not be that difficult to add NBest-feature for Neural Decoder, we will definitely work on it!

**Comment by davidecaroselli** [comment]
Hi @ya5an 

starting from commit https://github.com/ModernMT/MMT/commit/294b21365c4ce2fb30c9c319e4300252928e6af5 (available in **master** branch) NeuralEngine too supports NBest.

Moreover you can get more details from Translate API by specifying URL parameter `verbose=1`.
Enjoy! :)

**Comment by ya5an** [comment]
Thank you very much!
In response I often see a lot of duplicate. 
Is it possible to do something with this?

**Comment by davidecaroselli** [comment]
I see, we can fix that.
However for Neural Engine the only option is to filter the nbest list once the translation is computed, for this reason you could end up with less nbest than requested.

I will let you know as soon as the fix is available in master branch!

**Comment by davidecaroselli** [comment]
Hi @ya5an 
I made some further analysis and I noticed that sometimes two look-alike hypotheses have in reality different alignments, so for this reason we should not remove it, because it is indeed a different n-best.

On the other hand, we actually prefer to simply report the Neural Engine output, because, as already said in the last comment, we cannot enforce this option at low-level.

For the moment we will keep this functionality as it is: because the filtering really depends on what you need to do with it, we suggest to implement a filter in your UI for example (it should simple).

I'm closing this issue for the moment, if you're having any other issue please don't hesitate to re-open it.

Cheers,
Davide
