### ISSUE TITLE
"--gpus N" option must be at the end of the command line

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#297]
If the "--gpus n" option is in the middle of the command line, the parameter next to "N" is also taken as a part of the gpus option.. that complains about a bad argument. With this functioning, to make it working, it must be at the end of the command line.

**Comment by AndRossi** [comment]
Hi @EtienneAb3d, 

Yeah, I confirm that if an argument can contain multiple values, it must be at the end of the command line.

This is required by the `argparse` Python library that we use for parsing command line arguments.

Andrea

**Comment by EtienneAb3d** [comment]
If this is a comma-separated value, wouldn't it be possible to handle it as a single value: no space in it, only one token.

**Comment by AndRossi** [comment]
Hello @EtienneAb3d, 

I'm just writing to add some more details on this.  
You can actually use an argument with multiple values in the middle of your command.  
The only constraint is that arguments with multiple values must occur after all positional arguments.  

For instance, you can run something like this:  
`./mmt create en it examples/data/train/ --neural --gpus 0 1 2 3 --steps clean_tms preprocess --debug`  

But you can not run something like this:  
`./mmt create en --gpus 0 1 2 3 it examples/data/train/ --neural`  
because the parsing library can not understand if positional arguments `it` and `examples/data/train/` are 
a part of the `–gpus` argument or separate arguments.  

Your suggestion would be a good alternative. For the time being, however, we would like to keep the syntax as it is, since it is the `argparse` default behaviour (and it is quite a standard convention).  
However, thank you for your feedback and your great support!

I am closing this issue now. As usual, if you need more details on this topic, feel free to re-open it :) 

Andrea
