### ISSUE TITLE
Cannot find the saved checkpoint at the path mentioned in training.log

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#300]
Hello MMT team,

According to my training.log, the saved checkpoint should be located at:

`Copying checkpoint at /home/mlearner/ModernMT/runtime/default/tmp/training/onmt_model/checkpoint_610000`

but actually, no files or directory exist at this path at all. It's empty. 

Searched even in terminal, and it cannot locate such file. 

So, I don't know what happened exactly.

Also, is it possible to load the engine/model even if there is no checkpoint?

One more thing:

Can you please let me know what command to use to resume the training from a saved checkpoint? I couldn't seem to locate it in the Wiki pages.

I tried this command,  but it doesn't work.

`sudo ./mmt create en ar examples/data/train --neural --resume --checkpoint_610000`

It throws this error:

'mmt create: error: unrecognized arguments: --checkpoint_610000'

Is there  a way to resume the training from where it stopped? Or do I need to restart from scratch? 

Not sure, but it could be the swap file that created this issue, because it was a temp swap file and I didn't make it permanent. 

Please let me know what you think.

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

if the training end successfully (even if Ctrl+C) the temporary training files are removed from the `runtime` folder. If you want to avoid deleting temporary files, you can specify the `--debug` flag to the `create` command like this:
```
./mmt create en ar examples/data/train --neural --debug
```
If you train an engine like that, you will always be able to resume an interrupted training by simply adding `--resume` flag to the previous command: MMT will automatically restart from the last checkpoint saved.
```
./mmt create en ar examples/data/train --neural --debug --resume
```

In your case you probably don't have temporary files anymore. This is not a big issue, it is in fact possible to start a brand new training **from an existing model**:
```
./mmt create en ar examples/data/train --neural --debug --checkpoint /path/to/existing/neural/model
```

So to wrap things up, I suppose you have your "default" engine and you want to make some more iterations on it; from your `ModernMT` folder just run:
```
mv engines/default engines/default_bak
./mmt create en ar examples/data/train --neural --debug --checkpoint engines/default_bak/models/decoder
```

This will re-create `default` engine starting from your old one. Let me know if this procedure worked in your case!

Davide

**Comment by mzeidhassan** [comment]
Thanks a million, @davidecaroselli ! I will test this out when I get home and I'll keep you posted. Thanks again for the great tips, sharing of information, and amazing support! Grateful!

Thanks,
Mohamed

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli .

I have a question about the TM import process with the new neural decoder. 

When you import a TMX file to NMT, how does it process this file? Does it build on the current model and start training from there? 

In case there is a saved checkpoint, can this be used during the TMX import? Or do you simply import the TMX files and after importing you start retraining as you explained above? Or do you simply use the tune command? It's not clear to me how this works with the new neural decoder. 

One last question about monolingual data.

Can I add monolingual data to an existing engine after the fact? If this is not possible:

If I add monolingual data right now in my current engine, when I use this command:

`./mmt create en ar examples/data/train --neural --debug --checkpoint /path/to/existing/neural/model`

Would it pick it this time and use it during training? or do I need to start the engine creation process from scratch?

Thanks again for your support!

Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 
Glad we solved the issue! Now let's see the questions:

> When you import a TMX file to NMMT, how does it process this file? Does it build on the current model and start training from there?

So Neural Engine it's basically made of two main components: the neural model and the translation memory manager. The first, the neural model, is built during the training and after that moment, it won't change anymore: it is the baseline static model.

However when you import a TMX file, it is added to only to the translation memory manager and used for the adaptation. We use the sentence pairs contained in each TM to adapt on the fly the neural baseline-static model in order to improve the translation quality.

> One last question about monolingual data.

Neural engine does not need, and it does not use, monolingual data. It is helpful only for old phrase-base engine. If you add monolingual data to the training folder, it will simply ignored by the Neural Engine training.

Hope this helps! I'm closing the issue because the original  problem seems to be solved, if you need more info about MMT process, please, don't hesitate to open a different issue with that purpose: this way we'll keep issue content consistent and it will be much easier for other users to search for the content!

Thank you,
Davide

**Comment by marcotrombetti** [comment]
Thanks Davide,

Please consider adding this to a FAQ page in github.

Marco
Il giorno mar 21 nov 2017 alle 22:33 Davide Caroselli <
notifications@github.com> ha scritto:

**Comment by AndRossi** [comment]
Hi @marcotrombetti, 

I have added this to the [FAQ page](https://github.com/ModernMT/MMT/wiki/FAQs).

Andrea

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli and @AndRossi,

 I am sorry to reopen this, but I thought it's better to keep everything related in one single thread.

I followed the instructions above to iterate over an already built engine, but I am getting this error:

`IOError: [Errno 2] No such file or directory: '/engines/default_bak/models/decoder.bpe'`

I see that under "/engines/default_bak/models/decoder", the bpe file is called 'model.en__ar.bpe'

Before doing that, I tried to use a saved checkpoint in the temp folder, but I got 'IOError(2, 'No such file or directory')' error again and I think this happened because during this iteration phase, all temp files are deleted and recreated form scratch. I think it would be better if the --debug command saved the checkpoints to another folder other than temp so the saved checkpoint won't be deleted later on. This way, we will have access to these saved checkpoints and they can be used as a starting point for another iterative training. What do you think?

To retrain my engine, I used this command:

`sudo ./mmt create en ar examples/data/train --neural --debug --checkpoint /engines/default_bak/models/decoder`

I also tried this one, but it didn't work either:
`sudo ./mmt create en ar examples/data/train --neural --debug --checkpoint /engines/default_bak/models/decoder/model.en__ar.bpe --resume`

Please let me know what I am missing here. Maybe, there were some changed introduced in the latest version.

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

> I followed the instructions above to iterate over an already built engine, but I am getting this error:

As you suggested, this is due the fact that the temporary files have been removed from the previous training. In fact it is not possible to `resume` a training that has successfully completed.

>  I think it would be better if the --debug command saved the checkpoints to another folder other than temp so the saved checkpoint won't be deleted later on.

If you specify the `--debug` option during the training those files won't be removed. You can verify yourself with a fast training with `examples/data/train`. Be careful that if you re-run a training from scratch, the folder will be empty in order to run the new training. I suggest to backup your runtime/default folder after a training if you want to do some testing with the previous checkpoints.

> To retrain my engine, I used this command: [...]

You are absolutely right, I was misleading;  try with the following command:
```
./mmt create en ar examples/data/train --neural --debug --checkpoint /engines/default_bak/models/decoder/model.en__ar
```

In fact MMT just adds the suffix to the base-path passed with `--checkpoint`. I just pushed a fix in `master` that improves the help message for `./mmt create --help` including an example for the option `--checkpoint`. Thanks for the report!

Let me know if the command above solved the problem!

Davide

**Comment by mzeidhassan** [comment]
@davidecaroselli Thanks for your reply.

> If you specify the --debug option during the training those files won't be removed. You can verify yourself with a fast training with examples/data/train. Be careful that if you re-run a training from scratch, the folder will be empty in order to run the new training. 

I used --debug during the initial training and the checkpoints were saved, but once I entered that other command - as you said - everything was removed. Next time, I will make sure I make a copy of my runtime folder.

I will try your new command when I get home and I will report back here if there is any issues with it.

Thanks again @davidecaroselli for your continuous support.

Mohamed

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

Just to confirm that the updated command works just fine 👍 

One last thing before we close this issue again:

When you iterate over an already built engine using the base engine itself as a checkpoint (our scenario here), is the newly training data being added to the model and the engine is incrementally built/trained? Or does it start from scratch again? 

I am asking because my initial engine had really huge data (UN corpus plus more medical/technical data), but the training stopped after the third epoch for some reason. That's why I thought I will iterate over the engine one more time with some more technical/medical data only thinking this will improve the overall quality of the technical/medical domain as well. I am not sure if this is the right thing to do. 

What do you think? Is this a good strategy or is there is a better way of doing it?

I understand that MMT will stop further training if the accuracy and perplexity didn't improve for a couple of epochs, but I am not sure if this is the right approach/workflow when you train millions of rows.  What do you think?

Thanks again Davide for your amazing support!

Regards,
Mohamed

**Comment by davidecaroselli** [comment]
Great!

> When you iterate over an already built engine using the base engine itself as a checkpoint (our scenario here), is the newly training data being added to the model and the engine is incrementally built/trained? Or does it start from scratch again?

Unfortunately data can't be simply "added" to a neural model. So what MMT does is to start a fresh training with the new training data, but instead of choosing a random-generated network to start, it uses the network of the checkpoint you passed. Of course also the network metadata and the BPE plus vocabulary are kept intact.

This can be useful if you want to "tune" the network towards a specific set of data, in your case medical. I also suggest to start with a lower learning rate (default is 0.9) in order to keep a sort of inertia from the previous checkpoint. But this is totally up to you, you will probably find yourself the best settings depending on the amount of old data and new data.

I'm re-closing the issue but as always, don't hesitate to re-open it if you need further clarifications!

Cheers,
Davide
