### ISSUE TITLE
gpus="none" is not working when starting a neural model

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#302]
In a first step, I launched a neural model without any properly configured GPU card. With a small error displayed at screen, it started in CPU mode. This proves that the CPU mode is working properly for a neural model.

Then, on this machine, I installed properly the card, with a driver, and cuda libs. Of course, this card is very small, and this machine isn't really made to do GPU calculation in this configuration. With **gpus="none"** I got a OutOfMemory when loading the model. I also tried to set **gpus="-1"**, without success...

**Comment by EtienneAb3d** [comment]
Here is the solution, remove this line, like this:

![image](https://user-images.githubusercontent.com/25932245/32954851-9272906a-cbb4-11e7-8481-59d05968beb2.png)

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

I think to understand why that fix solved your issue, but unfortunately that has some very unpleasant side-effects: if you skip that line the engine won't use available GPUs by default anymore. For example during training it will run on CPU unless you explicit assign the GPUs by command line.

However I'll verify this issue as soon as I can, thanks for the tip!

Davide

**Comment by EtienneAb3d** [comment]
You need a way to make a difference between this explicit "None" set in the parameters file, and the default "None" value occurring when nothing is set. Perhaps, a "-1" value in the parameters file would be a good choice. 
Apart from this, now that I re-read the code above, I see that you are pruning the gpus argument according to available cards. I think this is not a good behaviour. If something is wrong in the parameters, you rather need to send an error...

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 
this issue has been solved with MMT v2.1. Now wrong configurations do not silently pass anymore, instead an error is thrown.
We have also added the `thread` parameter to the `<decoder>` element in `engine.xconf` configuration file in order to limit the number of CPUs used if no GPU is specified. More infos are available here: [Decoder configuration](https://github.com/ModernMT/MMT/wiki/Advanced-Configurations#decoder).

Thanks for your patience, as always if you need more support or you have other questions please feel free to re-open the issue.

Davide
