### ISSUE TITLE
If a XML tag starts with a number, it is translated as text

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#303]
In my process, as discussed in an other issue, to avoid BPE cuttings, I'm replacing mixed codes by a tag before a neutral code substitute. If a tag is starting with a number, MMT is translating it as if it was a text, rather than a tag. This makes it impossible to retrieve afterwards (and provides with strange wrong artifacts in the translation).
In my own process, I fixed this problem by adding a prefix starting with letters. But, perhaps this could be change in MMT.

**Comment by AndRossi** [comment]
Hello @EtienneAb3d, 

I do remember the issue you refer to :)
I think that the problem depends on the fact that that XML explicitly disallows numbers as the first character of an element name.

This is a regex listing the allowed characters:

```regex
NameStartChar ::= ":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] |
                  [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] |
                  [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] |
                  [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] |
                  [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
```

To solve the problem, I think it is necessary to prepend a letter to names that would otherwise start with numbers.  For instance, changing`5XXXX` into `N5XXXX`

You can find more details about the official XML naming conventions here: https://www.w3.org/TR/xml/

I hope this was helpful!
Thank you again for your support :)

Andrea

**Comment by EtienneAb3d** [comment]
OK. As said, in my case I added a prefix.
:)

**Comment by AndRossi** [comment]
Great!
I'm closing this issue, then.

As usual, don't hesitate to reopen it if you need more details or clarifications :)

Have a nice day! 

Andrea
