### ISSUE TITLE
GPU performance at training time

### ISSUE THREAD

**Issue by frdg** [ModernMT/MMT#309]
Hello!

My setup was recently updated with a second GPU card (lucky me, dual GTX 1080). I tried to create a new engine to check the gain in performance.

Using one GPU, on average 7000 tokens/sec (average between source and target) were processed during training. Using both GPU, performance drops to around 2000 tokens/sec. I checked that both GPUs were indeed in use and made sure my setup and drivers were properly configured and/or up-to-date.

I checked in the tickets if something related was put forward and found a one month old ticket (#290) stating (this could be outdated now):
> MMT can only use one GPU for training.

Meanwhile, the help section for the create command clearly states that you can use several GPUs (default being using all available GPUs).

Still, that does not really explain the harsh drop in performance. Anyone having the same issue?

**Comment by AndRossi** [comment]
Hi @frdg,

Unfortunately MMT still uses one single GPU for training.
This limitation is caused by the fact that the OpenNMT.py framework that we employ does not allow to use multiple GPUs yet (we are waiting for their multi-gpu release too :D ).  

The `create` command accepts multiple GPUs, but at the moment it just chooses and uses one of them. So the GPUs that you pass are actually the ones that MMT will consider "available", but then MMT employs only one among them.

The description of the `--gpus` argument was definitely not clear about this.
I'm sorry about that; I have now updated it to make it more detailed. You can find the new version in our `master` branch. 

On translation , on the contrary, MMT does use multiple GPUs; more in detail, it uses the same GPUs that you have passed in your `mmt create` command (unless you alter the configuration file manually). 

I hope it is clearer now :)
Thanks for your great support and patience!

Have a nice day,

Andrea

**Comment by frdg** [comment]
Hello @AndRossi,

Thank you for the information.

One thing remains unclear to me, as during the training using all available GPUs, both GPUs were under load. This seems to contradict what you stated, that only one GPU was picked up for training (and could explain the drop in perf if somehow the data was hauled back and forth between the two GPUs, but this just wet finger hypothesis).

Thanks again for your hard work, this is a great project.

**Comment by davidecaroselli** [comment]
Hi @frdg 

to be honest, because multi-gpu training is not supported, we have done our best in order to avoid strange, crashing situations; but we have never accurately inspected the side-effects.

So being multi-gpu training not supported for the moment I think that the best option is to raise and error if such situation occurs, that should prevent MMT to silently operate with unexpected consequences.

Thanks for your report!
Davide

**Comment by frdg** [comment]
Thank you @davidecaroselli, no problem :)
