### ISSUE TITLE
Question: Multilingual Engines in 2.0.2

### ISSUE THREAD

**Issue by nonsequitir** [ModernMT/MMT#314]
Am I correct in understanding that multilingual support in MMT is confined to neural engines, or can multilingual also be supported with phrase-based models?

**Comment by AndRossi** [comment]
Hi @nonsequitir,

Basically you are correct: a single engine can be multilingual only if it is neural.  

There is, however, a way to create a multilingual phrase-based MMT installation in the form of a _cluster_ of MMT engines.

Would this suit your needs?

Andrea

**Comment by nonsequitir** [comment]
Thanks @AndRossi    That's perfect.  I'll configure a cluster (that would make sense in a production environment anyway).  In parallel to this, we're training some large neural engines by way of comparison.  Will keep you posted!

**Comment by davidecaroselli** [comment]
Hi @nonsequitir 

sorry to disappoint you, but phrase-based multi-lingual engines are not supported by MMT: so I strongly discourage you to setting up a cluster with mixed phrase-based language directions.

This option is fully supported and maintained only for Adaptive Neural engines.

Thanks,
Davide

**Comment by davidecaroselli** [comment]
Please let me clarify a bit the previous post: as reported at the beginning of the [Multilingual Engines -
 Wiki Page](https://github.com/ModernMT/MMT/wiki/Multilingual-Engines) it is in theory possible to create a cluster of phrase-base engines with different languages.
However again, because this is a sort of "hacky" configuration that can lead to problems and may not be supported in the future, our advice is to avoid setting up a cluster with this setup.

Hope I've been more precise in describing the issue :)

Davide

**Comment by nonsequitir** [comment]
Thanks @davidecaroselli   I'll look to switch to the neural model instead.  This is more about getting familiar with the various deployment options between pbmt and neural. Appreciate the feedback!
