### ISSUE TITLE
Questionable translation results from neural engine using example data

### ISSUE THREAD

**Issue by jogleasonjr** [ModernMT/MMT#315]
Hello,

I have built this application from source (master) and created a phrase based engine using the following:

`$ ./mmt create en it examples/data/train`

This yields the expected results according to the documentation:

```
$ ./mmt translate --context computer "hello world"

ModernMT Translate command line
>> Context: ibm 98%, europarl 2%

>> hello mondo
```

However, when creating a neural engine using the following:

`$ ./mmt create en it examples/data/train --neural`

translation results are quite different:

```
ModernMT Translate command line
>> Context: ibm 98%, europarl 2%

>> cavato del seminario
```

Do I have something configured incorrectly, or is this the expected result given the neural engine and training data size? A different result for neural vs. phrase based isn't mentioned in the documentation so I have to question if what I'm seeing is correct.

I followed the installation instructions to the letter and everything appeared to build and run without problems. This is a fresh install of Ubuntu 16.04 and an NVIDIA GTX 1080 for CUDA. Please let me know if there's any other information or logging files I can provide.

Thanks!

**Comment by EtienneAb3d** [comment]
A statistical model can be more accurate than a neural one on a very short sentence not really in the main kind of formulations of the training data. Perhaps, try with a longer sentence, choosing it more according to the domains of the training data.

**Comment by davidecaroselli** [comment]
Hi @jogleasonjr 

following your advice I've updated the README.md including a note that explains the differences between the two cases. Short version is: your engine is perfectly ok! For Neural engines, 6000 lines of training date are simply not enough for being able to learn actual translations. 

This is the paragraph I've added to the readme file:

**Note**: the following quickstart example is run with a phrase-based engine for practical reasons. Neural training and Phrase-based training are two deeply different processes and if, for phrase-based engines, it is possible to achieve decent quality (under certain conditions) even with tiny datesets, Neural engines require more data and much more time in order to achive good performance.

**Comment by nicolabertoldi** [comment]
I would suggest to prepare a  "example/train/data" for the neural engine, maybe augmenting the data or reducing the dictionary; We could add this benchmark to the one for PB, or replace it. This way, the trained engine will produce reasonable translation.

**Comment by mfederico** [comment]
Hi, I guess one of the IWSLT benchmarks would perfectly work.

**Comment by nicolabertoldi** [comment]
I think we would need a benchmark on which the training takes only few (tens) of seconds.

Nicola

**Comment by jogleasonjr** [comment]
Thank you @davidecaroselli, good to know my engine is running correctly. I'll play around with larger training sets. Case closed!
