### ISSUE TITLE
How does Context really work?

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#318]
Hello MMT team,

I am a bit confused on how Context works in MMT. 

From the [wiki page](https://github.com/ModernMT/MMT#start-translating):

> Start translating
> 
> Let's now use the command-line tool mmt to query the engine with the sentence hello world and context computer:
> 
> $ ./mmt translate --context computer "hello world"
> 
> ModernMT Translate command line
> >> Context: ibm 87%, europarl 13%
> 
> >> hello mondo
> 

The [training data](https://github.com/ModernMT/MMT/tree/master/examples/data/train) that ship with MMT has the following files:

Europal, IBM and Microsoft.

What I am confused about is this part '--context computer':

./mmt translate --context computer "hello world"

My question is:
Based on what, you passed this context? From where you get the 'computer' context parameter? 

Also, I believe there was a wiki page about domains, but I cannot find it anymore. It still shows up in github search, but when you click on it, it doesn't take you anywhere.

https://github.com/ModernMT/MMT/search?q=domain&type=Wikis&utf8=%E2%9C%93

localhost:8040/domains. returns the memory names. So, I assume Domain is now replaced with Memory, right? 

Also, calling http://localhost8045/domains get the exact same results as calling http://localhost8045/memories

So, is there a difference between 'domains' and 'memories'? Or are they the same and they can be used interchangeably? 

I also came across [this post](https://github.com/ModernMT/MMT/issues/215) which is very useful, but adds to my confusion as well. 

What is context_weights vs context vector? Is 'context_weights' still usable? Is it now replaced with 'score' under 'ContextVector" endpoint in the REST API? 

When I run this at my end:

`http://localhost8045/translate?q=world&context_weights=10%27%20|%20python%20-mjson.tool
`
I see that it gets the translation from the 'memory' with id# 10.

Using the same exact call, but changing 'context_weights=' to 'contextVector=', I get the same result.

http://localhost8045/translate?q=world&contextVector=10%27%20|%20python%20-mjson.tool

 
Based on this paragraph, I understand that Context Vector is automatically calculated. 

> When MMT analyzes a context (i.e. the string you pass to /translate API), it outputs the Context Vector that is, a vector containing the scores for the best-matching domains given the context text.

I am sorry for bothering you with this, but I am confused about context handling and passing in MMT. 

Please let me know the logic behind '--context computer"' parameter in your command `./mmt translate --context computer "hello world"` and what is the correct command to use to pass a particular context?

Say, I have an engine with medical, automotive, marketing domains/memories? How can I make MMT use for example the automotive context when translating a particular document?

Thanks in advance for your support!

Kind regards,
Mohamed Zeid

**Comment by AndRossi** [comment]
Hello Mzeidhassan, 

I'm glad to help.

First of all: yeah, `memory` is a new name for `domain`. 
We have renamed it because `domain` was too overloaded - and probably not as clear as `memory`.

As for the example with `./mmt translate --context computer "hello world"`:
the `context` field is just a plain string that conveys some information on what the sentence to translate is about :)

For instance, since "hello world" is the output of the typical programming language tutorial, "computer" looks like a good context; "programming language tutorial" would have probably been just as good.
As you have found in #215, it is possible to send whole sentences, text blocks, or even files as context.

This having being said, when you specify a context in a translation request MMT analyzes it and compares it to the data that have previously been stored in all of your `memories`. 
More in detail, MMT computes values of similarity between the context text and each of your memories.
The output of this process is a `context vector` containing these similarity values, also called `scores`.

For instance: `1:0.34, 3:0.4` means that your context has a score of 0.34 with the memory with id 1 and a score of 0.4 with the memory with id 3.

The context vector plays a vital role in how MMT builds the translation.  
In order to provide the best translation, MMT adapts to your memories based on the score: the higher is the score of a certain memory, the more MMT will adapt to it to build your translation.

It is also possible to tell MMT to avoid context analysis, and just pass it the context vector directly, forcing MMT to use it intead of compute a context vector by itself. You can use the HTTP parameter `context_vector` to do this.
I believe this is what you want to do with your medical - automotive - marketing engine, right?
Let's say your automotive memory has id `2`, you can force a context vector like this:

```bash
curl "http://localhost:8045/translate?q=world&context_vector=2:1"
```

You can find more information on the `translate` API on its [wiki page](https://github.com/ModernMT/MMT/wiki/API-Translate).

I really hope this was helpful! :)

Have a nice day!

Andrea

**Comment by letconex** [comment]
Thank you for your answers!
Is it a good practice to send the entire segment / sentence as context?
http://localhost8045/translate?q=sample_sentence&context=sample_sentence

**Comment by davidecaroselli** [comment]
@mzeidhassan 
just to briefly recap what Andrea has perfectly explained:
- `context`: it is a free text, a sentence or even a single word that identifies the context of the translation.
- `context_vector`: it is a vector obtained once the ContextAnalyzer has processed the `context`. You can manually specify it or let the ContextAnalyzer do its job. In a very old version of MMT this could have been referred as `context_weights`; this parameter is **no longer accepted**.
- `memory`: it is a container for parallel data, it is the fundamental block of the MMT Adaptivity feature. This was previously referred as `domain`, we kept the old API for backward-compatibility, but you should always use `memory` for new development.

As suggested by Andrea, I've just changed README in order to use `"programming language tutorial"` for the example instead of `computer` that seems like a keyword of some sort.

@letconex 
Yes, that is definitely a good choice! We usually use the whole document we are about to translate, but even a single sentence, if you don't have more context, it is still a good choice. That is the case, for example, of a Web UI where the input you have is just the sentence you're about to translate.

**Comment by mzeidhassan** [comment]
As usual, very clear and detailed answers! Thanks @AndRossi and @davidecaroselli for taking the time to explain the concept clearly. I appreciate it.

**Comment by mzeidhassan** [comment]
One last thing @davidecaroselli and @AndRossi 

Since you are working on the translate xliff script "extras/translate_xliff", I believe it would make sense to be able to pass these parameters when you use the script. What do you think?

**Comment by EtienneAb3d** [comment]
@letconex asked:

> Is it a good practice to send the entire segment / sentence as context?
> http://localhost8045/translate?q=sample_sentence&context=sample_sentence

@davidecaroselli said:

> Yes, that is definitely a good choice!

I would rather answer "no". This will work only if the sentence is not ambiguous according to domains/memories. But, unambiguous sentences would be certainly well translated even without context. The context is made to help choosing the right translation when there is an ambiguity for the sentence to be translated. So, you need to provide a pertinent context for the domain/memory you are expecting.

**Comment by AndRossi** [comment]
Hi again @mzeidhassan,

With our latest commits in `master` branch, the `extras/translate-xliff` also supports `--context`, `--context-vector` and `--context-file` arguments :)

As I wrote in another issue, after updating MMT from commits older than 09981f7 you will need to upgrade your older 2.x engines; you will find all the infos you need in #322 :)

Have a nice weekend!

Andrea

**Comment by mzeidhassan** [comment]
Thank you so much @AndRossi for this great addition/update. I really appreciate it. 
Have a wonderful weekend!
Best regards,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 

Were you able to check the context features for the `extras/translate-xliff` script? 
If so, did they meet your needs?
I do hope so! :)

Andrea

**Comment by mzeidhassan** [comment]
Hi @AndRossi ,

I tested it yesterday, but without using the context features. I will test it again and report back here.

I noticed something though and I was going to report, so I am glad you followed up with me.

I noticed that a space is added to in the translation for strings that are usually untranslatable.

So, if you have a model name like 'CS5000" which is a standalone string, the script adds a space and make it "CS 5000".

You may test it at your end and let me know if you have the same issue.

I will test the context feature and report back later today.

Thanks again for your great support, @AndRossi ! Really appreciate your follow-up!

Thanks,
Mohamed

**Comment by EtienneAb3d** [comment]
@mzeidhassan, have a look at #286.

**Comment by mzeidhassan** [comment]
@AndRossi I tested the --context with one word and it works fine. If I use multiple words though, it throws an error, although you can pass multiple words or even a sentence through the API. I tried to put them in parenthesis, but it doesn't work either. So, I am not sure if this is OK or there is a way to pass a whole sentence as --context parameter.

I even tested it with the one you used above `--context computer "hello world"`, but I got this error message:

`translate_xliff.sh: error: unrecognized arguments: hello world`


As for the --context_file, I am not sure how it is used. Can I pass a sdlxliff or xliff file through this parameter? I searched the wiki, but couldn't find info. 

It would be great if you can give examples on how to use these different parameters. Also, I believe thi wiki page should be updated accordingly. 

Thanks again Andrea for all your efforts. 

Mohamed

**Comment by mzeidhassan** [comment]
@AndRossi Here is also a screen shot of the space issue. @EtienneAb3d referred to that other issue about tokenization. Is there a workaround to avoid this? It does this with any text that has mixed numbers and letters. For example:

S108xxxx-001 becomes `S 108 xxxx-001`

Maybe, the tokenizer shouldn't run on conactenated texts that have mixed numbers and letters. Not sure if you can tweak it at your end or use regex in the translate_xliff script to skip such strings and just copy them as is in target language.

![space](https://user-images.githubusercontent.com/7589948/33978673-92a10440-e0a9-11e7-9749-fa958b084a32.PNG)

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 

I'm glad it seems to work fine now!
As for using a string with multiple whitespace-separated words, I have pushed right now a fix in `master` that should do the trick :)

As for the tokenization problem: yeah, our tokenizer often separates numbers from text (not always: as you see, in S108xxxx-001 xxxx-001 is still a single token, probably because there's a hyphen there ).
This is the behaviour that has generally given the best results in our tests; unfortunately, edge cases are always possible. 

If this feature matters heavily in your scenario, though, you may want to develop yourself a simple postprocessor that finds text followed by numbers and erases the whitespace between them.
You can find some infos about that in this old issue: #294

Since the context problem seems solved I'm closing this issue now.  
Of course if you have further problems with it don't hesitate to re-open it; if you need more support for the post-processing problem, feel free to ask in issue #294 (that I have just re-opened).

Have a nice day!

Andrea

**Comment by mzeidhassan** [comment]
Thanks @AndRossi for the update. I appreciate it.

I noticed the other day that if you have a folder with files that has spaces in its names, the script fails to translate them and throws an error. Is there a workaround for this issue?

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 
You can find in `master` branch a fix for that too :) 
Now if you want to use a sentence with whitespaces (e.g. "lorem ipsum dolor sit amet") as a context, or a path with whitespaces for context-file or input path, just use double quotes around them.

Here are some examples: 

```bash
$ extras/translate_xliff --context "lorem ipsum dolor sit amet" <path_to_your_xliff>
```

```bash
$ extras/translate_xliff --context-file "/home/ubuntu/te st/my_context.it" "/home/ubuntu/sdl xliff/"

Translating /home/ubuntu/sdl xliff/te st.sdlxliff into /home/ubuntu/sdl xliff/xliff_out/out_te st.sdlxliff...
```

Thanks you for your great support!

Have a nice day :)

Andrea

**Comment by mzeidhassan** [comment]
Thanks a million, @AndRossi ! You really never cease to amaze me.
Have a great weekend ahead and Happy Holidays!

Kind regards,
Mohamed
