### ISSUE TITLE
Iterative Training

### ISSUE THREAD

**Issue by nonsequitir** [ModernMT/MMT#319]
Hello MMT'ers

We've trained a large engine with content from various sources.  Obviously, doing a big-train-up-front can take some time, even with a powerful GPU (we're looking at neural).  My question is, are there any best practices around training a large engine such that we might break up our corpora into chunks and train iteratively, allowing earlier use of the engine with some of the content, but that we might then add more content to specific memories over time?

And further to this, if we front-end MMT into a full translation/post-edit workflow via a traditional CAT tool, is the recommended approach to import the TMX resulting from this post-edit exercise (which easy over the API), or is it better to retrain the (neural) engine in some other way? 

Thanks in advance!

**Comment by AndRossi** [comment]
Hi @nonsequitir, 

I apologize for the delayed answer - it has been really busy around here lately. 

I do understand your point about the time that neural trainings can take :) 
To mitigate this problem, during training MMT stores in a temporary folder the latest 20 checkpoints, so at any moment you can decide to use the last checkpoint as an intermediate model for a new engine.
Of course, the translation results will not probably be as good as they would after a complete training. 
This practice, however, is extremely useful to study how the training is affecting the models without waiting the whole training. 

Here's how you can do that: let's say you have a bash open where you are are training a `my_engine` engine for language direction `en -> it`.

First of all you should copy your `engines/my_engine` folder to another location in engines, say `engines/my_engine_2`. This way you can keep `my_engine` training and you can use `my_engine_2` as a new engine with intermediate models.
You can do this opening a bash in your mmt home and running:

```bash
cp -R engines/my_engine engines/my_engine_2
```

Now you need to manually copy some intermediate `my_engine` model files into the new `my_engine_2` engine:
- check your `runtime/my_engine/tmp/training/onmt_model` and choose the last checkpoint (it is the one with the biggest number). Let's say it is checkpoint 512.
- go back to your mmt home
- copy and rename the model files into your my_engine_2 decoder models folder:
```bash
$ cp runtime/my_engine/tmp/training/onmt_model/checkpoint_512.bpe engines/my_engine_2/models/decoder/model.en__it.bpe
$ cp runtime/my_engine/tmp/training/onmt_model/checkpoint_512.dat engines/my_engine_2/models/decoder/model.en__it.dat
$ cp runtime/my_engine/tmp/training/onmt_model/checkpoint_512.meta engines/my_engine_2/models/decoder/model.en__it.meta
$ cp runtime/my_engine/tmp/training/onmt_model/checkpoint_512.vcb engines/my_engine_2/models/decoder/model.en__it.vcb
```

Finally you need to create from scratch a new model.conf file for your new `my_engine_2` engine.
You can do that by running:
```bash
nano engines/my_engine_2/models/decoder/model.conf
```

and write the `model`.conf file content:
```bash
[models]
en__it = model.en__it
```

Done! Your `my_engine_2` engine can now be started and tested.
Please note that this new engine should be started and tested *on a different machine, or at least on a different GPU than your training engine*. This is necessary in order to avoid having out-of-memory errors that could make your training process crash!

As for re-training after collecting data (e.g. through CAT tools): it really depends on the data you collect.
If the data you gather in this way are big and generic, I believe that re-training once in a while is the best way. As a rule of thumb, re-training may be convenient if your data have at least doubled :)

I apologize again for answering so late.

Thanks for your patience!

Andrea

**Comment by nonsequitir** [comment]
@AndRossi  This is awesomely helpful Andrea, thanks so much for the terrific detail! I'll try to experiment with this over the coming days.
