### ISSUE TITLE
MMT didn't use all available TMX files due to different language codes

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#323]
Hello MMT team,

I am creating an English>Simplified Chinese engine and I found out later that there were different TMX memories with different language codes.

`EN>zh_CN` vs. `en-US>zh-CN`

MMT picked the files with the second language codes only, but during the engine creation of my enzh engine, MMT displayed the following:

> Engine: enzh
> BILINGUAL CORPORA: 18 documents
> LANGS: en > zh

So, I  assumed it picked up all 18 documents.

I only found out alter that it used only 5 memories that has this language code: en-US>zh-CN

My question is:

Either MMT should have warned me that there are different/mixed language codes and your engine will use the following 5 files only ...... 

Or at least, the number of files next to "BILINGUAL CORPORA:" should have been 5 only, not 18 and still it should throw a warning that not all memories will be used. 

I think this could be an enhancement request. What do you think? 

One last question:

Does this mean that if I put English Arabic files with different language codes, it won't pick all files. Say, 
EN-US > AR-SA
EN-UK > AR-EG
etc...

In such scenario, which language combinations will be picked up? Or MMT will pick up all language codes as long as they are ISO-compliant? 

Thanks in advance for your support!

Best regards,
Mohamed Zeid

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

I apologize for the delayed answer.

As for the first question, MMT will only use segments that are both ISO compliant and that match the engine language direction.
If any of these two conditions are not matched, MMT will just skip the segment.

For parallel files (e.g. a pair of files like `corpus.en` and `corpus.zh`), MMT can immediately know how many files it is going to use, with no surprises at runtime.
This is possible because the language direction can be inferred from the files extension itself, and it is the same for all the segments in these files.

For TMX files, however, the situation is a bit different: the same TMX file can contain segments for different language directions, so some segments might be "valid" whereas some others might not be. In the worst case, which is the one you have experienced, a TMX can contain only invalid segments for the current training.

MMT has no way to know this before opening the TMX file and scanning it all.
Performing such a "full check" before starting the training, however, would not be acceptable efficiency-wise. So for the time being I don't think that MMT can tell you that it is using 5 files only instead of 18.


As for the second question:
EN-US and EN-UK are considered as subcategories of EN; likewise, AR-SA and AR-EG are considered as subcategories of AR.
So let's say that you have a TMX file with some EN-US > AR-SA segments and some EN-UK > AR-EG ones.

If you are training an EN->AR engine, both your EN-US > AR-SA and your EN-UK > AR-EG will be used.
Otherwise, if you are training, for instance, an EN-UK -> AR engine, only the segments with EN-UK source language will be employed (EN-US ones will be skipped). 
The same goes for the target languages of course :)

I hope this was helpful!

Andrea

**Comment by mzeidhassan** [comment]
No problem, @AndRossi ! I thought you were busy with the new release :-) 

Thanks for the info about subcategories of language variances. This is good to know.
