### ISSUE TITLE
en-ko Translation Issue

### ISSUE THREAD

**Issue by rau2000** [ModernMT/MMT#327]
When translating English into Korean, the following phenomenon occurs.

ex) 'The first communications processor' -> '제 ? 통신 프로세서'

The word 'first' is being translated into '?'.

What is the problem?

**Comment by AndRossi** [comment]
Hi @rau2000, 

Thanks for trying MMT!

I see what is the cause of this issue. It is a problem that rarely occurs, depending on how MMT handles numbers in relation to the content of your training set.

This is how MMT usually handles numbers:
- In an initial preprocessing phase, numbers are stripped away and replaced with placeholders.
- Then MMT proceeds to translate the source sentence (that now contains placeholders instead of numbers), and returns a target sentence (containing placeholders instead of numbers as well).
- Finally, a postprocessor finds the original numbers and uses them to replace the translation placeholders.

This is what is probably happening in your case:
- `first` is not recognized as a number, so the preprocessor does not strip it away. This happens both in training and in translation!
- so, during training, how does the engine learn to translate  "first communications"? It depends on the content of your training set. 
Your set probably contains something like this: "first communications" -> "1° 연락".
In this case, the `1°` in your target sentence *is* recognized as a number, so it is stripped away and your engine learns to translate "first communications"" with "<NUMBER_PLACEHOLDER> 연락".
- Therefore, in translation, the post-processor looks for a number in the source sentence, it does not find it and, now knowing what to use to replace the <NUMBER_PLACEHOLDER> in the target sentence, it just uses `?`. 

This problem, unfortunately, can not be solved easily. We have some ideas, but currently we are not so close to find a good implementation. In the meantime, I really hope that this problem does not affect your translations too badly!

Thanks for your patience and support.

Have a nice day!

Andrea

**Comment by rau2000** [comment]
Thank you for your reply.

We will also perform various tests to solve the problem.

Hava a nice day!

rau2000

**Comment by Heeyoung-Ahn** [comment]
rau2000님 안녕하세요.
혹시 한국분이신가요?
MMT 구축관련해서 몇 가지 여쭤보고 싶은 게 있는데, 한국분이시면 ahynest@gmail.com으로 메일 부탁드립니다.
감사합니다.
