### ISSUE TITLE
MMT 2.1 neural trainning is using more card memory

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#330]
I'm currently testing the latest version. The new version is nearly saturating the card memory, while the previous one was using half of it. I just wonder if this is the expected behaviour of the new version. There is perhaps a small risk to overload the card...
![image](https://user-images.githubusercontent.com/25932245/34196960-a17e076e-e564-11e7-8e41-ab48bcf5b234.png)

**Comment by AndRossi** [comment]
Hi @EtienneAb3d, 

From version 2.0.2 to version 2.1 there were no relevant changes in the internal structures we save in the GPU RAM, so it is hard to figure why your GPU card appears more heavily loaded. 
In our tests, updating CUDA drivers and PyTorch did not affect the GPU RAM load. 

However note that during training the GPU RAM usage is very unstable (it has a sort of irregular sinusoid pattern), so you may be experiencing a very temporary peak. 

A way to be completely safe from GPU overloading in any case is to use a smaller batch size.
You can choose manually the batch size to use in our training with option `--batch-size` in `./mmt create` command (default is 64 lines).

I hope this helps!

Have a nice day :)

Andrea

**Comment by EtienneAb3d** [comment]
In exactly the same conditions, when training on the other languages sens, after 2 checkpoints, it is still using only 5G, like with the previous version. Waiting to see if the amount is increasing at some time..

**Comment by EtienneAb3d** [comment]
After 1 epoch, it is using 6G. A bit more, but far from the 10G above.

**Comment by EtienneAb3d** [comment]
Doing again a training in the first sense, with very small modifications in the data set, after 1 epoch, it is now using 8.5G. It's very strange that is is using a so random amount of RAM on the card, from one run to an other.

**Comment by AndRossi** [comment]
Hi @EtienneAb3d,

I'm closing this is issue due to inactivity now. 

Thanks for sharing these reports with us: they are really precious, because they provide a feedback on how the MMT VRAM usage behaves on different platforms from ours :)

I do not think that your VRAM values depend on a bug; it just looks like a "normal" irregular behavior, with high temporary peaks.  

For any doubt or problem, however, feel free to re-open this issue :)

Thanks again for your great support.

Have a nice day!

Andrea
