### ISSUE TITLE
CAT tool integration

### ISSUE THREAD

**Issue by dursunarif05** [ModernMT/MMT#337]
Hello NMT team,
- I'm a technical translator and I'd like to use your technology to increase the translation productivity.
Q1: Is this technology available for installation by end-users? Or should some developer need to build it first and deliver to the end-user?
- Like others in the industry, we work with CAT tools for post editing purposes.
Q2: Do you have a CAT tool (for my case Trados) plug-in, such as OpenNMT project, as below?
http://appstore.sdl.com/language/app/opennmt/818/

Regards
Arif

**Comment by AndRossi** [comment]
Hi @dursunarif05, 

we're glad you are willing to try MMT!

Our technology is available to end users indeed.  
If you have some knowledge of UNIX environment (e.g. basic bash commands), I suggest you to follow [this guide](https://github.com/ModernMT/MMT/blob/master/INSTALL.md) to install it.
Please note that MMT currently requires an Ubuntu 16.04 environment.

As for the CAT tools, we do have a partnership with the free CAT Tool [MateCAT](https://www.matecat.com).
MateCat allows translators with an MMT License to interact with our neural-based production engine. The production engine has been trained with over one billion words from high quality parallel corpora, and it can learn from your uploaded data too, in order to provide the highest quality translations.  

If you need any help with the MMT installation on your own machine, or with the MMT-Matecat interaction, please don't hesitate to ask! :)

Have a nice day!

Andrea

**Comment by dursunarif05** [comment]
Thanks for the info, @AndRossi,

Will be following your work.

**Comment by letconex** [comment]
You may pretranslate the .sdlxliff file(s) with MMT and postedit.

**Comment by davidecaroselli** [comment]
I'm closing this issue for now. As always, let us know if you need further assistance! :)
