### ISSUE TITLE
URL rendering issue in Japanese

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#351]
Hi Davide and MMT team,

Hope it's all well with you. 

Have you experience such issue in Japanese when it comes to URL rendering?

Here is the English string in question:

`Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>`

Sending this through the REST API, I get this:

` Web ブラウザを開いてフレッシュ・クラウド」 Web サイトに移動します: <codeph>http :// freshe. cloud. com</codeph>`

As you can see above:

1. Spaces were added to the URL.
2. 'fresh' became 'freshe'

Sometimes, the tag is even misplaced like this:

`<codeph>http :// fresh. cloud</codeph>. com`

As far as I know, anything between tags should be preserved as is. Any idea why this is happening here? 

Thanks.,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan ,

This is strange.. First things first: content **between** tags have always been translated. In fact MMT is able to translate something like:
```
You should <b>translate</b> this!
```
into
```
Devi <b>tradurre</b> questo!
```

What MMT ignores is the tag itself and its attributes. So for example you in:
```
This is my picture <img src="..." alt="This is an example" />
```
The system won't translate "This is an example", because it's an XML attribute value.

Now, let's talk about the problem of the broken translation, and that is strange. As far as I understand you are translating EN > JA, so the source sentence is pre-processed by an EN  tokenizer that, just tested right now in my installation, should produce:
```
Open your web browser and go to the Fresh Cloud website : http://fresh.cloud.com
```
So the URL is not tokenized. In your report the URL is broken because the system has tokenized it first, and then it attempted to translate its tokens. So I would like to ask you to run some tests to see what's going on.

First, let's be sure about the tokenization, from within the MMT folder run:
```
extras/javamain.sh PreprocessorMain -s en -t ja <<< "Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>"
```
The output should be:
```
Open your web browser and go to the Fresh Cloud website : <codeph> http://fresh.cloud.com </codeph>
```

Now let's check what the decoder receives. Start mmt and try to translate that sentence:
```
./mmt translate <<< "Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>"
```

What is the output? What is the content of the log file `node.log`?

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

Thanks for your reply.

Yes, you are right. I meant to say 'any URL between tags'. 

Now, back to the real issue:

Running:
` extras/javamain.sh PreprocessorMain -s en -t ja <<< "Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>"
`
returned:

`Open your web browser and go to the Fresh Cloud website : <codeph> http://fresh.                                   cloud.com </codeph>
`

This looks fine. it added a space after the opening tag and one before the closing tag though. 

Trying the second command is a bit tricky in a Multilingual engine setup. 

I am not sure if I can pass -s and -t parameters in a Multilingual engine. Is this possible? If not, then I think this should be added to the translate command.  I tried, and it didn't work though.


I used this one instead though:

`curl -X GET http://localhost:8045/translate \
     -d "source=en" \
     -d "target=ja" \
     -d "q=Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>" \
     -d "engine=multilingual" \
     | python -mjson.tool
`

The output in node.log is:
`2018-02-28 17:10:28,499 INFO  eu.modernmt.rest.RESTServer$Router [qtp41465-657] "GET /translate?source=en&target=ja&q=Open your web browser and go to the Fresh Cloud website: <codeph>http://fresh.cloud.com</codeph>&engine=multilingual" 200 89`

Here is also a screen shot of the terminal output as well. In the terminal, the URL is malformed in Japanese. 

Thanks again Davide for taking the time to look into this issue.

Kind regards,
Mohamed
![japanese_url_issue](https://user-images.githubusercontent.com/7589948/36801912-88877a7c-1c70-11e8-8ec1-83523d3d357c.PNG)

**Comment by mzeidhassan** [comment]
@davidecaroselli 
I found more serious issues that were not visible in MMT 2.3. Please let me know if you want me to open a new issue for these, but I believe they are still relevant.  The issues are Japanese and Chinese (ZH).

URL issues in Chinese - ZH:

In ZH, a lot of URLs are being replaced, with the same pattern (us-phoenix-?.oraclecloud.com) e.g.

1) Source: export  FTM_AUTH_URL =https://foo.storage.oraclecloud.com

**MMT 2.4 output:**

导出Fmtm_AUTH_URL = https://foo.storage.us-phoenix-?.oraclecloud.com

**MMT 2.3 output:**

export FTM_AUTH_URL = https://foo.storage.oraclecloud.com

In **Japanese**, the same source URL is malformed and it displays as follows:

**MMT 2.4:**
export FATM_auth_URL = https :// foo. storage. oracve. comのエクスポート

**MMT 2.3:**
エクスポート・FTM_AUTH_URL = https :// foo. storage. oraclecloud. com


2) Some name corruption that was not seen before in Japanese
Source: Ubuntu 14.04 LTS

**MMT 2.4:**
Uightu ??. 14.04 Lts

**MMT 2.3:**
Ubuntu 14. 04 LTS

Another example for Japanese:

Source: Mac OS X 10.7 or later
**MMT 2.4:**
Mac OS X 10.7. ?以上
**MMT 2.3:**
Mac OS X 10.7 或更高版本

I hope you find this useful and I hope there is a fix for them.

Thanks again!
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan !

So I tested a little more and I have and idea on what's happening.

Regarding the **original issue**:
While the EN tokenization is perfectly ok, in Japanese the tokenizer we are using does not keep together URLs. This means that MMT has been trained on examples like this:
* source: `website` `:` `http://fresh.cloud.com`
* target: `し` `ま` `す` `:` `http` `://` `freshe` `.` `cloud` `.` `com`

So the translation is some-how coherent, but the problem is that the de-tokenizer expects URL not to be tokenized, and it fails in regroup it.

**Solution**: we must modify the JA tokenizer in order to prevent the tokenization of the URLs. This however *will require a re-train of the JA engine*.

On the **latest issue**:
With MMT 2.4 we fixed an important bug on the CJKV chars tokenization that was causing a lower translation quality and it could even break UTF-8 encoding. Now the problem is that, due to the fact that we changed the pre/post-processing components, *engines from MMT 2.3 with a CJKV language are no longer compatible with MMT 2.4*, but they need a re-train.

So my advice is: keep MMT 2.3 until you could run a re-train for your CJKV engines with the new MMT 2.4. We are currently re-train EN-ZH also for our production engines for the same reason.

Hope this helps a bit. Let me know if I can help you further!

Best,
Davide

**Comment by mzeidhassan** [comment]
@davidecaroselli Thank you so much, Davide for your prompt follow-up on this. Glad to know that there is a fix for the JA tokenizer. Can you please let me know when this is fixed.

As for the latest issue, actually, it was trained from scratch with 2.4 and I didn't use the 2.3 engine.

**Comment by davidecaroselli** [comment]
@mzeidhassan  no problem!
I'll post here any updates on this topic.

Regarding the second issue is very difficult for me to debug because I can't access the training data. However let's try to search inside the pre-processed data in `runtime` folder during the training for something like "oraclecloud.com" and let's see what it's written in the chinese side. I want to check if this is a pre-processing problem or a learning issue.

Cheers,
Davide

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli ! I will check this out and get back to you. Can you let me know in which file I should search exactly? I don't have access to the engine now and I am using a multilingual engine and there is no data in the runtime folder for some reason, but I believe I have a backup of the JA engine before merging it into a multilingual one.

**Comment by nicolabertoldi** [comment]
the pre-processed data are stored in the directory runtime/<YOUR_ENGINE>/tmp/training/preprocessed_corpora/

**Comment by mzeidhassan** [comment]
Thanks @nicolabertoldi !

We checked it out. 

The source has "cloud.oracle.com", but the target has "cloud . oracle . com".

**Comment by mzeidhassan** [comment]
Another example: 
EN: `http://www.oracle.com/pls/topic/lookup?ctx=acc&id=info
`
JA: `http :// www . oracle . com / pls / topic / lookup ? ctx = acc & id = info
`

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli and @nicolabertoldi ,

I hope it's all well with you. Is there any progress on this issue?

One more thing:
Is there a way to avoid the tokenization step during training?
For Arabic, I may want to use a different tokenizer offline to tokenize the Arabic text. Can I then use this already-tokenized text in training?

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

we've been very busy in the past week due to our presence at AMTA 2018 :)

Regarding your question on the tokenization of Arabic: yes, this is possible. You have to edit the file [preprocessor-default.xml](https://github.com/ModernMT/MMT/blob/master/src/textprocessing/src/main/resources/eu/modernmt/processing/preprocessor-default.xml#L26).

Instead of `eu.modernmt.processing.tokenizer.corenlp.CoreNLPTokenizer` you can put your custom version of Arabic tokenizer. If you have already tokenized text, you can create a generic "WhitespaceTokenizer" so that you will simply obtain tokens by splitting by space.

By the way, if you think you have a good (open-source) Arabic tokenizer implementation (better than the current one in MMT) please consider the option to let us implement it directly in MMT :) We would be happy to improve MMT with your suggestions.

Cheers,
Davide

**Comment by mzeidhassan** [comment]
@davidecaroselli Nice to hear from you. Good luck with AMTA :-) !

What tokenizer do you use for Arabic in MMT? Is it CoreNLP?

I came across this one and I tested the online demo and it looks great and better than CoreNLP.

http://qatsdemo.cloudapp.net/farasa/

Thanks Davide for continuous support!

Kind regards,
Mohamed

**Comment by davidecaroselli** [comment]
@mzeidhassan just downloaded the software and I will give it a try for sure. The problem I see is that is intended to be used only for research purposes... I sent an email to the team, let's see what options they have for open source projects!
(By the way, let's move this discussion in another issue: we are a bit OT :) )

Cheers,
Davide

**Comment by mzeidhassan** [comment]
You are right :-) Do you want me to create a new topic titled "Arabic Tokenizer"?

**Comment by mzeidhassan** [comment]
@davidecaroselli Is there any update on the Japanese tokenization fix? It was much better in 2.3. I hope you have some time to get this fixed. Any update?

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

I plan to work on this in the next days, I'll keep you updated!

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli and good luck! You must have been very busy recently. Thanks again for taking the time to fix this issue.

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan ,

I just pushed into master a fix for this issue. Now on the Japanese part an URL is properly kept intact. In order to see the fix, you need to re-run a training because the issue was in the pre-processing step.

I just made a test with the sentence of your example, and everything seems to work just fine!

As always, feel free to re.open this issue if you still encounter this problem.
Best,
Davide
