### ISSUE TITLE
LM Training Speed

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#37]
Similar to #29 Language model training can be parallelized much more.
Using only 19% of CPU on a 16 core machine, 0% iowait
Using only 9% of CPU on a 32 core machine, 0% iowait

How do we choose the num of parallel process for build-sublm.pl and gzip?

see below
```
top - 18:39:28 up 19:38,  1 user,  load average: 5.52, 22.65, 27.02
Tasks: 556 total,   4 running, 552 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.7 us,  0.1 sy,  0.0 ni, 91.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  61836572 total, 47466540 used, 14370032 free,    19964 buffers
KiB Swap:        0 total,        0 used,        0 free. 45557656 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                       
 74022 ubuntu    20   0   53676  36872   2060 R 100.0  0.1  11:51.93 build-sublm.pl                                                                                                                                
 74181 ubuntu    20   0   22412   5652   2060 R  99.9  0.0  11:24.79 build-sublm.pl                                                                                                                                
 75204 ubuntu    20   0    4596    812    416 S  35.2  0.0   0:40.14 gzip                                                                                                                                          
 75210 ubuntu    20   0    4596    808    416 S  33.2  0.0   0:29.85 gzip                                                                                                                                          
 75211 ubuntu    20   0    4596    808    416 R  27.9  0.0   0:24.36 gzip                                                                                                                                          
 75205 ubuntu    20   0    4596    808    416 S  17.3  0.0   0:19.86 gzip                                                                                                                                          
 75201 ubuntu    20   0    4728    680    488 S   7.0  0.0   0:07.77 gzip                                                                                                                                          
 75206 ubuntu    20   0    4728    680    488 S   6.3  0.0   0:05.37 gzip                                                                                                                                          
 75207 ubuntu    20   0    4728    684    488 S   4.0  0.0   0:05.85 gzip                                                                                                                                          
 75200 ubuntu    20   0    4728    684    488 S   3.3  0.0   0:04.20 gzip                                                                                                                                          
   478 root      20   0       0      0      0 S   0.3  0.0   0:20.51 kworker
```

**Comment by davidecaroselli** [comment]
@nicolabertoldi is there already an option to the scripts for LM training to specify the number of threads? Would you take this challenge?

**Comment by nicolabertoldi** [comment]
In IRSTLM, the training of the LM is not multithreaded.
However it is possible to train the lm on sub-portions of the corpus and then to merge the sub-models in one LM. For some kind of smoothing, the smoothing is approximated with respect to the "correct" one.

hence, either:
if MMT system employed the "tlm" command to train the LM, there is no way to use multi-threading
if MMT system employed the "build-lm" command, there is the possibility to train the model on sub-parts, and then merge the probs

Nicola

**Comment by mfederico** [comment]
To be more clear:  

- if the corpus is large you can use build-lm which is multi-threaded and fast
- if the corpus is small tlm is nevertheless fast
- if you have many small corpora we could  train more LMs in parallel. 

Marcello

**Comment by nicolabertoldi** [comment]
one further clarification on this claim

> - if the corpus is large you can use build-lm which is multi-threaded and fast

Actually build-lm   is not multithreaded, but multi-process; i.e. multiple processes work in parallel to compute probs on portions of the corpus.
Indeed, it is fast 


Nicola

**Comment by marcotrombetti** [comment]
I confirm we are testing on large corpus (>300M words)

Either threads or process will work. The important is using the resources of the machine well.

The alignment, for example, is very CPU efficient: with 36 cores it uses on average 34

```
top - 07:39:30 up  9:32,  1 user,  load average: 35.83, 34.45, 33.33
Tasks: 543 total,   3 running, 540 sleeping,   0 stopped,   0 zombie
%Cpu(s): 93.5 us,  1.4 sy,  0.0 ni,  5.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  61836572 total, 61548824 used,   287748 free,    62332 buffers
KiB Swap:        0 total,        0 used,        0 free. 35675164 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                       
 38964 ubuntu    20   0 23.929g 0.023t    964 R  3379 39.7   4880:36 fast_align                                                                                                                                    
 39394 ubuntu    20   0   23960   2072   1168 R   0.7  0.0   0:00.98 top                                                                                                                                           
   449 root      20   0       0      0      0 S   0.3  0.0   0:20.25 kworker/0:1                                                                                                                                   
   463 root      20   0       0      0      0 S   0.3  0.0   0:19.45 kworker/2:1                                                                                                                                   
   465 root      20   0       0      0      0 S   0.3  0.0   0:19.37 kworker/4:1                                                                                                                                   
   470 root      20   0       0      0      0 S   0.3  0.0   0:23.71 kworker/9:1                                                                                                                                   
   471 root      20   0       0      0      0 S   0.3  0.0   0:22.76 kworker/10:1                                                                                                                                  
   472 root      20   0       0      0      0 S   0.3  0.0   0:22.55 kworker/11:1
```

**Comment by nicolabertoldi** [comment]
to this purpose, I suggest to use build-lm to train a LM
setting the number of portions (i.e. one of the parameters)
close to the number of available cores


Nicola

**Comment by marcotrombetti** [comment]
Good to me. How can we test?

@davidecaroselli are you independent for this or do you need help?

**Comment by davidecaroselli** [comment]
I run some tests, first of all I checked and the multi-process parameter (-k) is already used and set to # of CPUs. I run the tests on a 4-cores machine, and I set "k" to 4 (I've also tried with 8, but I could not see any difference). I can recognize 6 phases of build-lm.sh:

* add-start-end.sh **[CPU 30% - Duration: short]**: can we skip this phase? I think it should be possible to change the training script in a way that the build-lm itself add the start/stop symbols just in time.
* build-lm.sh, process ngt **[CPU 100% - Duration: short]**: perfect
* build-lm.sh, processes ngt and gzip **[CPU 35% - Duration: normal]**: what's happening here? Why the training is not at 100% CPU ?
* build-lm.sh, processes build-sublm.pl and gzip **[CPU 100% - Duration: very long]**: perfect
* merge-sublm.pl **[CPU 30% - Duration: short]**: is there a way to run it multithread?
* compile-lm **[CPU 20% - Duration: normal]**: is there a way to run it multithread?

@marcotrombetti what you were observing in your first post seems to be the end of the 4th phase where all the build-sublm.pl processes terminate before starting the next step. In this timeslice the CPU usage start decreasing but this period only lasts few seconds, so there's no real problem.

@nicolabertoldi I would focus on phases 1, 3, 6 and optionally 5. Do you know how to speed them up?

**Comment by nicolabertoldi** [comment]
Hi Davide,


below I try to discuss and comment about the LM training, 
but before I would like to ask you if you can report the actual times taken from each of the LM training steps.


I am not sure which version of build-lm.sh are you considering
I discuss below that available in IRSTLM Github repo
https://github.com/irstlm-team/irstlm/blob/master/scripts/build-lm.sh


The main goal of build-lm.sh was to avoid a large use of RAM. No big attention was paid for time efficiency .
For this reason a vast used of disk I/O was used instead of RAM and CPU.


Actually the phases of the LM training by means of build-lm.sh are a bit more

phase 1: add start and end symbols (SE symbols) to the input 	[main command: add-se-symbols.sh]
phase 2: create a dictionary on the input (including SE) 	[main command: dictionary]
phase 3: split the dictionary into portions		[main command: split-dict.pl]
phase 4: create ngramtable for each portions; the ngramtables are created as gzipped files      [main command: ngt]
phase 5: estimate LM  for each portions; the ngramtables read as input are gzipped files      [main command: build-sublm]
phase 6: merge all sublm into one    [main command: merge-sublm]
phase 7: transformation of iARPA format into binary IRSTLM format   [main command: compile-lm]


Some comments about my phases 1-7

phase 1: the addition of SE symbols is non mandatory when training a LM, but it should be a free choice of the user.
However in the machine translation scenario (especially with Moses), this addition is always done, because the SE symbols are always used when translating.
The reason why SE symbols are added in advance (before build-lm.sh) is to avoid to do this action  twice; indeed, build-lm.sh reads the input twice: once for creating the dictionary, once for collecting ngrams counts.
I am not sure whether performing this addition twice (within build-lm.sh) is faster than doing once in advance.

phase 2: could be run in cascade with phase 1 (in case do the same in phase 4)

phase 3: must follow phase 2

phase 4: could be run in cascade with phase 1 (in case do the same in phase 2); we can avoid the usage of gzip/gunzip

phase 5: we can avoid the usage of gzip/gunzip

phase 6: we can avoid the usage of gzip/gunzip


Other comments:
- it is possible to improve time efficiency if we do not use zipped files (phases 4 and 5 and 6); obviously will required more disk space.
- sincerely, I have no idea why your step 4 do not use 100% CPU (but only 35%); maybe this is because the large I/O and zipping which are performed
- merge-sublm.pl can not be made multithreaded because it has to concatenate all single files created in phase 5 into one single file
- it is not easy to make compile-lm multi-threaded or multi-process

cheers,
Nicola

**Comment by davidecaroselli** [comment]
@nicolabertoldi thanks for the explanation, I think we've found some good points to work on.
First of all, the script I'm using is available from the 0.11 release package ( https://github.com/ModernMT/MMT/releases/download/v0.11/mmt-0.11-ubuntu14_04.tar.gz ).

I'll suggest to proceed in this way:
* First remove gzip/gunzip usage, in this way we can evaluate the tradeoff between RAM used and speed gained.
* Secondly can you change the bins that requests start and stop tags in a way that they automatically add them to the input (one line at time) just before being processed? In this way we save the time needed to completely read and write the entire corpora just to add <s> and </s> and, of course, disk space. This could be a command line option (something like --add-start-stop ?)

If you want to discuss more deeply we can have a call as well.

Cheers
- Davide

**Comment by mfederico** [comment]
Hi, notice that add-start-end.sh can work in pipeline with other commands. 
<

**Comment by davidecaroselli** [comment]
@nicolabertoldi  worked on a new version of the training scripts without the gzip command. We run some tests and the CPU usage is reported in the attached image (blue is the old version, red is the new version).

![Comparison](https://cloud.githubusercontent.com/assets/1674891/12329816/6707f56c-bae2-11e5-84b5-6ee923c5f5a7.png)

With the new process we gain **1.2x** in speed on a 4-cores machine. @nicolabertoldi have you some statistics on the space needed in this step with and without zipping the temp files?

**Comment by nicolabertoldi** [comment]
> With the new process we gain 1.2x in speed on a 4-cores machine. @nicolabertoldi have you some statistics on the space needed in this step with and without zipping the temp files?
> 
> 

No, you are welcome to measure it.

**Comment by ugermann** [comment]
Did you drop page caches before measuring (sync; echo 3 >
/proc/sys/vm/drop_caches)? If unzipped files are still in the fs cache,
yes, using unzipped files is faster, but if you have to load the data from
disk, disk performance may become the bottle neck, especially on disks
accessed via NFS.

- Uli

On Thu, Jan 14, 2016 at 4:21 PM, Davide Caroselli <notifications@github.com>
wrote:

> @nicolabertoldi <https://github.com/nicolabertoldi> worked on a new
> version of the training scripts without the gzip command. We run some tests
> and the CPU usage is reported in the attached image (blue is the old
> version, red is the new version).
>
> [image: Comparison]
> <https://cloud.githubusercontent.com/assets/1674891/12329816/6707f56c-bae2-11e5-84b5-6ee923c5f5a7.png>
>
> With the new process we gain *1.2x* in speed on a 4-cores machine.
> @nicolabertoldi <https://github.com/nicolabertoldi> have you some
> statistics on the space needed in this step with and without zipping the
> temp files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/37#issuecomment-171688741>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by davidecaroselli** [comment]
@ugermann I've also tested the script in brand new virtual machine, and I had the same results.

@nicolabertoldi I've checked the disk space required: turns out that without zipping, temporary files require 4 times more than zipped version. Please note, however, that it's 4 time the disk space of only the largest input domain, because temp files are removed after every iteration.

The final decision is to introduce an option to the **mmt create** command, --lm.zipping that can be set to 1 to enable temporary files zipping. Default is now set to 0.

e.g.
`
./mmt create en it examples/data/train --lm.zipping=1
`

**Comment by davidecaroselli** [comment]
This feature is currently **disabled** due some problems found on systems with more than 8 CPUs.
