### ISSUE TITLE
MMT 3.0 training - when will it stop ?

### ISSUE THREAD

**Issue by philippehenri** [ModernMT/MMT#396]
Hi
I am doing a training since a week. I notice that logs are completely different from MMT 2.5 (no more perplexity...)

Can you please let me know when it will stop. Can we stop it, evaluate and resume training if not satisfactory?
thanks

currently last lines of my log are : 

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-08-27 19:42:37.505728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-27 19:42:37.505763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-27 19:42:37.505769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-27 19:42:37.505774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-27 19:42:37.505876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7707 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/ubuntu/mmt/runtime/frnl/tmp/training/neural_model/model.ckpt-1144000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1144001 into /home/ubuntu/mmt/runtime/frnl/tmp/training/neural_model/model.ckpt.
INFO:tensorflow:loss = 0.70003885, step = 1144000
INFO:tensorflow:global_step/sec: 2.67082
INFO:tensorflow:loss = 0.6209078, step = 1144100 (37.442 sec)
INFO:tensorflow:global_step/sec: 3.11626
INFO:tensorflow:loss = 0.6314922, step = 1144200 (32.090 sec)
INFO:tensorflow:global_step/sec: 3.12672
INFO:tensorflow:loss = 0.71939456, step = 1144300 (31.983 sec)
INFO:tensorflow:global_step/sec: 3.09593
INFO:tensorflow:loss = 0.77452344, step = 1144400 (32.300 sec)

**Comment by nicolabertoldi** [comment]
In MMT 3.0 the only stopping condition is the number of "train-steps" which is unlimited by default, i.e. the training continues forever.

You can monitor the trend of the training by greping lines containing the string "Saving dict for global step", which reports several metrics including perplexity and loss on the  validation set. By default the validation is computed every 5000 steps.

**Comment by philippehenri** [comment]
thanks.

and which values should i look for, which are considered good enough to stop please? can i resume if stopped and results are not good?

i got these last lines from grep:

INFO:tensorflow:Saving dict for global step 1140000: global_step = 1140000, loss = 0.8813926, metrics-translate_mmt/targets/accuracy = 0.79710984, metrics-translate_mmt/targets/accuracy_per_sequence = 0.109, metrics-translate_mmt/targets/accuracy_top5 = 0.9362138, metrics-translate_mmt/targets/approx_bleu_score = 0.5400281, metrics-translate_mmt/targets/neg_log_perplexity = -0.9533308, metrics-translate_mmt/targets/rouge_2_fscore = 0.6141006, metrics-translate_mmt/targets/rouge_L_fscore = 0.7205059
INFO:tensorflow:Saving dict for global step 1141000: global_step = 1141000, loss = 0.88628525, metrics-translate_mmt/targets/accuracy = 0.7972115, metrics-translate_mmt/targets/accuracy_per_sequence = 0.112, metrics-translate_mmt/targets/accuracy_top5 = 0.93622833, metrics-translate_mmt/targets/approx_bleu_score = 0.54020756, metrics-translate_mmt/targets/neg_log_perplexity = -0.9531698, metrics-translate_mmt/targets/rouge_2_fscore = 0.6145789, metrics-translate_mmt/targets/rouge_L_fscore = 0.72062117
INFO:tensorflow:Saving dict for global step 1142000: global_step = 1142000, loss = 0.8893292, metrics-translate_mmt/targets/accuracy = 0.7969937, metrics-translate_mmt/targets/accuracy_per_sequence = 0.111, metrics-translate_mmt/targets/accuracy_top5 = 0.9354586, metrics-translate_mmt/targets/approx_bleu_score = 0.5395844, metrics-translate_mmt/targets/neg_log_perplexity = -0.9572926, metrics-translate_mmt/targets/rouge_2_fscore = 0.6141151, metrics-translate_mmt/targets/rouge_L_fscore = 0.72059435
INFO:tensorflow:Saving dict for global step 1143000: global_step = 1143000, loss = 0.88409007, metrics-translate_mmt/targets/accuracy = 0.7977634, metrics-translate_mmt/targets/accuracy_per_sequence = 0.11, metrics-translate_mmt/targets/accuracy_top5 = 0.9356619, metrics-translate_mmt/targets/approx_bleu_score = 0.53940755, metrics-translate_mmt/targets/neg_log_perplexity = -0.95406073, metrics-translate_mmt/targets/rouge_2_fscore = 0.61364555, metrics-translate_mmt/targets/rouge_L_fscore = 0.719994
INFO:tensorflow:Saving dict for global step 1144000: global_step = 1144000, loss = 0.8826237, metrics-translate_mmt/targets/accuracy = 0.7968485, metrics-translate_mmt/targets/accuracy_per_sequence = 0.109, metrics-translate_mmt/targets/accuracy_top5 = 0.93557477, metrics-translate_mmt/targets/approx_bleu_score = 0.5409114, metrics-translate_mmt/targets/neg_log_perplexity = -0.95345736, metrics-translate_mmt/targets/rouge_2_fscore = 0.61535597, metrics-translate_mmt/targets/rouge_L_fscore = 0.7214207

**Comment by nicolabertoldi** [comment]
It is difficult to answer to your question, because it depends on the size and type of your training data and setting as well as your hardware architecture (number and type of GPUs) and, last but not least, money and time you can use for the purpose.
By the way, the "loss" is a reasonable trigger to understand the trend of the training; it can fluctuate a lot, but its moving average over several points does no increase anymore (or enough), you can consider the convergence has been reached.
In our training on 1B words, we usually run for about 1 week on a 4-gpu machine, which correspond to about 800K steps.
I am pretty sure that your training has reached the convergence.

For big/huge training I would suggest to set "--eval-steps 5000"  in order to reduce the evaluation steps. The default, which you are using, is 1000 (not 5000 as I wrongly said in my previous post).

If you are interested, you can have a visualization of the status of the training by using Tensorboard
https://www.tensorflow.org/guide/summaries_and_tensorboard.
Please refer to its documentation to learn how to use it.

**Comment by LoekvanKooten** [comment]
I'm afraid that pointing Tensorboard to the MMT directory doesn't visualize anything. See my other thread about this.

**Comment by nicolabertoldi** [comment]
Actually I just tried (with a toy example) and I succeeded to visualize plots as expected and as you can see from picture attached.

basically I run tensorboard as follows
tensorboard --logdir=./runtime/default/tmp/training/neural_model

and visualize via browser accessing the page
http://URL:6006/

where URL is the IP of the machine where tensorboard is running


<img width="291" alt="screen shot 2018-08-29 at 12 36 57" src="https://user-images.githubusercontent.com/1104476/44782672-4ec16800-ab88-11e8-8378-7bd8cce995b6.png">
<img width="906" alt="screen shot 2018-08-29 at 12 36 35" src="https://user-images.githubusercontent.com/1104476/44782674-4ec16800-ab88-11e8-8137-4d72a951a61f.png">

**Comment by LoekvanKooten** [comment]
I will test this again when retraining a new model using ./runtime instead of ./mmt/runtine. As for now you can close this!

**Comment by nicolabertoldi** [comment]
The last part of the thread is related to issue #394,
which has been closed just now.

**Comment by philippehenri** [comment]
thanks Nicola for the details to check in the log, will try .About  tensorboardi could install and run, but http://localhost:6006/ does not work, i guess because i have to forward the port to the containing running the training (that i dont want to stop now)...

**Comment by nicolabertoldi** [comment]
you have to use the "numeric" IP (probably 127.0.0.1) instead of "localhost"
this assume that you can access the machine from the browser

if both browser and tensorboard run on the same machine no problem should occur.

Nicola

**Comment by LoekvanKooten** [comment]
I was able to solve this issue by uninstalling and reinstalling Tensorboard via pip. This seems to have been an issue in older versions.

**Comment by davidecaroselli** [comment]
Anyway, it would be a great feature to have ModernMT automatically detect when it's time to halt because the perplexity is not improving so much anymore.

Also it would be helpful to start automatically Tensorboard during training. We will focus on these features for the next release!

**Comment by nicolabertoldi** [comment]
We will advertise all our users, when we will introduce any new features proposed by @davidecaroselli .

At the moment, we close this issue.

**Comment by EtienneAb3d** [comment]
In your help pages, I read:
`By default this process will run forever, until a Ctrl+C command is sent or the corresponding command kill -2 <process-pid> is run in a shell.`
Training is step 5/6. I think, with a CTRL+C, step 6 won't run. What does this step 6 ? (pack_model, in the -h infos ?)
Will the obtained model be ready to work ?

**Comment by LoekvanKooten** [comment]
If you wait for a while, the program will continue to step 6. Once that step is finished, you can use your build.

**Comment by nicolabertoldi** [comment]
Loek is right.

CTRL-C does not kill the full training process; It just sends a signal which interrupts step 5 only and let step 6 continue until the end.
The engine created is ready-to-use.

**Comment by EtienneAb3d** [comment]
First, I searched for the process id:
```
lm-dev8@dev8:~/MMT32$ ps aux|grep mmt
lm-dev8   9034  179  7.0 42964340 4620492 pts/12 Sl+ oct.25 45452:12 /usr/bin/python /usr/local/bin/t2t-trainer --t2t_usr_dir /home/lm-dev8/MMT32/build/lib/t2t --data_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_train_data/data --problem=translate_mmt --model=transformer --hparams_set=transformer_base --output_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_model --local_eval_frequency=50000 --train_steps=100000000 --worker_gpu=1 --hparams batch_size=3072
```
As said, I killed it:
```
lm-dev8@dev8:~/MMT32$ kill -2 9034
```
The process stopped with this error, without running step 6:
```
INFO: (1 of 6) Corpora cleaning...                                     DONE (in 47m 8s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 22m 57s)
INFO: (3 of 6) Aligner training...                                     DONE (in 2h 7m 44s)
INFO: (4 of 6) Preparing data...                                       DONE (in 1h 59m 26s)
INFO: (5 of 6) Training model...                                      
ERROR Unexpected exception: None

Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 143, in main_create
    builder.build()
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 556, in build
    self._build(resume=False)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 629, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 428, in __call__
    self._f(*args, **kwargs)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 768, in _train_model
    n_train_steps=self._n_train_steps, n_eval_steps=self._n_eval_steps)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 189, in train_model
    raise ShellError(' '.join(command), return_code, None)
cli.libs.osutils.ShellError: Command 't2t-trainer --t2t_usr_dir /home/lm-dev8/MMT32/build/lib/t2t --data_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_train_data/data --problem=translate_mmt --model=transformer --hparams_set=transformer_base --output_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_model --local_eval_frequency=50000 --train_steps=100000000 --worker_gpu=1 --hparams batch_size=3072' failed with exit code 1
```
What should I do now ?

**Comment by philippehenri** [comment]
you should hit CTRL-C to stop it, then it runs step 6 properly... (and not kill the process)

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 

if the directory ``runtime/ENGINE/tmp/training`` is still present and not empty, you have not lost your training.
You can run the following command to "finalize" the training
```
mmt create -e ENGINE --steps pack_model
```

This is not fully tested, so please backup your training directory ``runtime/ENGINE/`` before running the command above


If you prefer I can make this test, but I need to know exactly, the script you run and the way you kill the process.

**Comment by EtienneAb3d** [comment]
In your command, it lacks the languages and corpus path that seem to be mandatory.

There is then a "already exists" question, a bit suspicious. Answering yes, it seems to really launch the good step.. but fail with an error.

Checking the data, the runtime was effectively reset. I have now to restore from the backup.

Is this a bug to be fixed, or is ther something lacking in the command ? The "resume" option ?

**Comment by davidecaroselli** [comment]
Etienne you are right: you have to use the --resume option, not the "steps" one. Just type the full original command plus the --resume flag.

**Comment by nicolabertoldi** [comment]
@EtienneAb3d 
probably it was my fault, and the "--resume" option is mandatory

Let me test the exact procedure.
I will report with the correct solution asap.

**Comment by EtienneAb3d** [comment]
Using the exact original "create" command, and adding "--resume --steps pack_model" at the end seems to work.

**Comment by nicolabertoldi** [comment]
I summarise this discussion.


Suppose you are training a system, by running the following command:
```mmt create en it data ```

In order to correctly stop the engine and get a working (finalised) system before it stops autonomously, you have to:

- CTRL-C the process "mmt create" ( neither t2t-trainer or a shell script which runs "mmt create")
- `kill -2 proc_id` (equivalent to CTRL-C) the process "mmt create" (with process id is ``proc_id``)


If for any reason, the training failed or the training process is killed in a wrong way, you can resume the training by running
```mmt create en it data --resume```
which will stop autonomously when the maximum number of training steps is achieved.


If you do not want to resume the training, but simply "finalise" the engine without the maximum number of training steps is achieved, you have to run
```mmt create en it data --resume --steps pack_model```

Note that, you can finalise an engine only if at least one checkpoint is stored.

**Comment by EtienneAb3d** [comment]
In my case, a simple "--resume" didn't work. I got an error. But, not sure if this is because of my special conditions. I will check this again later, because I would like to test this procedure:
- train to a special point, with a quite short delay, and stop the training
- duplicate all data, in order to be able to finalize a first prod model
- resume to continue the training, in order to possibly get a better prod model later

**Comment by nicolabertoldi** [comment]
I imagine you got a message that the engine is already existing, right?
Actually, you should find your engine in ``engines/default``.
In this case your engine should be formally fine; you could try to start it and test it.
The performance depends on how much it was trained.

Assuming that the engine is formally fine, but you would like to continue training. This is possible if you run the first command `` mmt create``  with the ``--debug``  flag.
Otherwise, there is no easy way to resume. It is still possible, but in an approximated way and with several manual actions. Hope you do not need it.

**Comment by mzeidhassan** [comment]
Thanks @nicolabertoldi ! I hope this would work and I won't lose almost 4 days of training. By the way, I see saved checkpoints in the tmp directory and the last one was saved later today. Can I resume the training from the last saved checkpoint, then kill it properly to build the engine?

**Comment by nicolabertoldi** [comment]
hi @mzeidhassan 

You can resume training as you have this checkpoint.

To be extremely sure, I would suggest to backup the whole ``runtime/default/tmp/`` directory.

Could you please look at ``runtime/default/tmp/training/checkpoint.json``, which represent the training steps already performed?
The content should be the following:
```
["clean_tms", "preprocess", "train_aligner", "write_config", "prepare_data", "train_model"]
```
If you see also an additional step ``pack_model``, your training is completed and the engine is ready to use.
In this case the ``--resume`` does not work (because the training is considered finished); to actually resume the training you have to edit the file and remove the step ``pack_model``.

**Comment by mzeidhassan** [comment]
Thanks @nicolabertoldi ! It ended all well and the training was finished. Thanks for providing more info. 
Any plans for automatic termination of training once engine reaches convergence? Cannot you use the same script used in 2.5?

**Comment by nicolabertoldi** [comment]
Hi @mzeidhassan,
good to know!

Regarding the automatic termination policy,  we decided to not implement it in the transformer-based. However, we can re-think about this in the future.
I open a new "feature-request" issue. Please follow it to keep update

Please feel free this issue if you do not have any further questions.

**Comment by davidecaroselli** [comment]
Done, thanks @mzeidhassan ! :)
