### ISSUE TITLE
DNT tokens are removed in translations

### ISSUE THREAD

**Issue by robertBrnnn** [ModernMT/MMT#414]
Hi MMT team,

I have a question / possible bug report In relation to #385, and the addition of the ${DNTX} tokens.
I've noticed in some cases that MMT isn't preserving the ${DNTX} token in the output translation. (Also another observation which really isn't an issue is the casing of the token gets modified)

I assume that when training engines, the training content should have these ${DNT} tokens, we train engines with these tokens in the training content.  (If they don't need to be there do let me know)

Regardless, I have been able to reproduce the issue against both our engines and your public engines.

Take for example:
EN: 

> Same as ${DNT1}, however, if the Authorization header is not ${DNT2}, ${DNT3}, or ${DNT4}, then the ${DNT5} considers the authentication method as ${DNT6}, and then passes the browser request.

ZH_CN: 

> 然而，如果授权标题不是${Dnt2}、${dnt3}或${dnt4} ，则${dnt5}将认证方法视为${dnt6} ，然后传递浏览器请求。

As you can see the ${DNT1} token has been completely removed.

 If I look at MMT source code as I did in #385, I see that `${DNT%d}_` is the token that gets added in `/src/decoder-neural/src/main/python/nmmt/t2t/problem.py make_reserved_tokens(self)`. If I translate with ${DNTX}_ the tokens seem to be preserved, against our engines and your engines, see below:

EN: 
> Same as ${DNT1}_ , however, if the Authorization header is not ${DNT2}_ , ${DNT3}_ , or ${DNT4}_ , then the ${DNT5}_ considers the authentication method as ${DNT6}_ , and then passes the browser request.

ZH_CN:
> 然而，与${Dnt1}_ ，如果授权标题不是${dnt2}_ 、${dnt3}_ ，或${dnt4}_ ，则${dnt5}_ 将认证方法视为${dnt6}_ ，然后传递浏览器请求。

Is this just a coincidence or should the tokens we put in the source text actually be `${DNTX}_` instead of `${DNTX}`?

Thanks,
Rob

**Comment by robertBrnnn** [comment]
Hi again,
Expanding on the above, in `src/textprocessing/src/main/jflex/eu/modernmt/processing/tokenizer/jflex/annotators/CommonTermsTokenAnnotator.pyflex` you have a rule for DNT tokens of the format `${DNT_X}` where the `_` is optional. 

It's quite hard to figure out what DNT token format should actually be used.

Could you enlighten me?

Rob.

**Comment by nicolabertoldi** [comment]
We will double-check as soon as possible.

**Comment by nicolabertoldi** [comment]
1.  It is correct that the input must contain   ``${DNTX}``  and not   ``${DNTX}_``
2. ``${DNTX}_`` is an internal representation of the bpe subtokens, which close of original tokens
3. The regular expression in ``CommonTermsTokenAnnotator`` would allow to match both ``${DNTX}``  and ``${DNT_X}``, but the system actually handles ``${DNTX}``

With the transformer model it is actually possible that some tags are not translated. In fact, it is not mandatory for the decoder to "cover" (translate) all source tokens, but it can choose to not translate some (portions of) words. This is due to the attention mechanism.

In the second scenario, when you use ``${DNTX}_`` it is basically by chance that they occur in the translation.


By the way, in next days we will double-check to definitely confirm the above-mentioned behaviour.

**Comment by nicolabertoldi** [comment]
The presence of tags of type ``${DntX}`` or ``${dntX}`` (instead of the expected ``${DNTX}``) is much likely a signal that the ModernMT version used is too old and/or that the system was trained with an old and incompatible version.

The DoNotTranslate facility was introduced in release 3.0.

I would remind that:
- the usage of DNT tags is effective only if the system has been trained on a training corpus containing such tags;
- the system interprets DNT tags as any other "standard" tokens; so, it translates them correctly if the system is trained reasonably well; but however it is still possible that DNT tags are wrongly translated or even not translated at all, like any other tokens;
- the system is trained well if the training corpus contains a reasonable amount of sentence pairs with DNT tags;
- the correct format of the DNT tags is ``${DNTX}``, where ``X`` ranges from 0 to 9.

**Comment by robertBrnnn** [comment]
Hi @nicolabertoldi 

> The presence of tags of type ${DntX} or ${dntX} (instead of the expected ${DNTX}) is much likely a signal that the ModernMT version used is too old and/or that the system was trained with an old and incompatible version.
The DoNotTranslate facility was introduced in release 3.0.

The engines in question were trained with ModernMT 3.0.

> the system is trained well if the training corpus contains a reasonable amount of sentence pairs with DNT tags;

The corpus did contain DNT placeholders. In fact before training the engines, we pre-processed the entire corpus inserting these DNT tokens where applicable. 

The token format we used was ${DNTX}. 

>  it is still possible that DNT tags are wrongly translated or even not translated at all, like any other tokens

So, there is no guarantee that DNT tokens in the source text, will actually exist in the translation. We have already designed some validation around this, but it is quite a common occurrence.

Would there be any way to always make the engine preserve the placeholders, otherwise it is a lottery as to whether the translation will be in any way valid?

Rob

**Comment by nicolabertoldi** [comment]
Hi @robertBrnnn,

could you please provide us a subset of your training corpus, and the exact versions (commit number) of the code you used?
I would like to replicate the behaviour you observed, because in my test I always see the expected outputs.

**Comment by robertBrnnn** [comment]
Hi @nicolabertoldi 
The training corpus is proprietary data, I am unable provide even a subset of it.

As for the exact version number, we used the 3.0 docker image release, which I assume corresponds with the one from your releases page https://github.com/ModernMT/MMT/releases/tag/v3.0 

When you are running tests, are you checking CJK languages or European languages? There seems to be very little if any issues with European from our experience, it's the CJK languages that tend to have issues.

Thanks,
Rob

**Comment by nicolabertoldi** [comment]
Hi @robertBrnnn 

actually I tested on Western languages
I will debug CJK asap

Nicola

**Comment by nicolabertoldi** [comment]
Hi @robertBrnnn 

thanks to your help, I identify a small problem with DNT protected tokens and CJK languages.

I am working to implement the solution, which will be available very soon.

**Comment by nicolabertoldi** [comment]
solved in commit 40a29dc9032ee78cc323c34b2abb4decfa8877ab
