### ISSUE TITLE
Return source and target tokens with attention table

### ISSUE THREAD

**Issue by sdlmw** [ModernMT/MMT#423]
Hi MMT team,

Whether MMT can also output attention content. If yes, what parameters should I use?

Thanks

**Comment by nicolabertoldi** [comment]
Hi @sdlmw,

currently, we do not expose the attention table in any way, although we compute it.

We will discuss soon whether to insert this feature in next release.
Please stay tuned to know enhancement about this and other features.

**Comment by sdlmw** [comment]
hi @nicolabertoldi 

thanks for your reply.  I'm looking forward to the arrival of new features

**Comment by EtienneAb3d** [comment]
Just a little thing that can be done: add a tag like <TOK0001/> <TOK0002/> in front of each input word. In the output, you will get reported tags giving an idea of what is the attention table / token to token alignment.

**Comment by davidecaroselli** [comment]
Hi @sdlmw 

because attention model is very low level feature, we won't expose it in the APIs. Moreover, the attention model refers to sub-tokens (after BPE), so it even hard to link that data with the actual translation result in a such high level response. So if  you want to implement some low-level feature, you should operate directly at the low-level python code.

If you are interested into **alignment** instead, we have that option in the APIs right away! Just add the `verbose=true` parameter to the [Translate API](https://github.com/ModernMT/MMT/wiki/API-Translate) and it will output the alignment together with the tokens of both source and target text.

**Comment by sdlmw** [comment]
Hi @davidecaroselli 

If you can add the relevant parameters to enable this feature. I think it's faster than I can change the code myself.Please add this feature.

Thanks

**Comment by davidecaroselli** [comment]
Hi @sdlmw 

as I said, if you are interested into alignments and tokenization, it's all already there: no need for further development. Just add `verbose=true` parameter to the API.
For Attention Model, we won't expose that info in the API because it's about consistency: we will end up adding super low-level info mixed with very high-level ones, without even them correlating correctly (because of different tokenization). In other words we will end up with a messy API response (and architecture).

**Comment by sdlmw** [comment]
@davidecaroselli 

I understand. Thank you for your support. I'm going to try this parameter.  Is this parameter something I need to specify when I start the engine? or need to append to the HTTP request

**Comment by davidecaroselli** [comment]
Just append that parameter to the HTTP request, i.e.:
```bash
curl -X GET http://localhost:8045/translate \
     -d "source=en" \
     -d "target=it" \
     -d "q=This+is+an+example" \
     -d "verbose=true" \
     | python -mjson.tool
```

**Comment by sdlmw** [comment]
@davidecaroselli 

Good，Thank you!
