### ISSUE TITLE
Training from an existing model

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/MMT#433]
Is there a way to launch a training on a new set of data, using an already trained model as starting point ?
It could be very useful, to specialize a generic model, or simply enrich the process explained in #426.

**Comment by davidecaroselli** [comment]
Not at the moment. However our training process is calls the tensor2tensor `t2t-train` command under the hood. So if there is a way for doing so in t2t, we can easily replicate this in our tool.

**Comment by mzeidhassan** [comment]
I came across this one. It could be useful https://github.com/tensorflow/tensor2tensor/issues/588

**Comment by davidecaroselli** [comment]
Hello,

in `master` branch I have just merged a branch from @nicolabertoldi that implements this feature. You can now use `mmt create` and specify an initial model (instead of random initialized net) with the option `--from-model`.

It is now possible to specialize a pre-trained generic model just like @EtienneAb3d 's use case!

**Comment by EtienneAb3d** [comment]
Great news opening a lot of possibilities !
:+1:
