### ISSUE TITLE
Add option 'resume' to 'create' command

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#52]
I have a model that crashed at step TM, out of memory
I started a new machine with more ram and run

```
./mmt create en fr ../data -e BIG -s tm
```

I expected it was resuming, but it did not work. 

And as far as I understand TM is getting the original corpus as input instead of the tokenized corpus as it should, because that data has been deleted.

We have 2 options:
1 - We warn the user that the **-s** option is not able to resume and it is for designed for debug only.
2 - Do not delete the files after a crash to allow resume. Which make more sense to me. I understand that we loose the possibility of going quickly to point 4 without doing the previous but that less frequent than the need of resume.

**Comment by davidecaroselli** [comment]
I've changed the title because what we're going to do is to add the --resume flag to the 'create' command. The option '-s' works in a totally different way. I suggest to point out in the help message that '-s' is used basically for debug, or very advanced, purpose.

**Comment by davidecaroselli** [comment]
(sorry, I didn't mean to close it!)

**Comment by marcotrombetti** [comment]
@davidecaroselli I agree and moving to 0.13

**Comment by nicolabertoldi** [comment]
My two cents as developer

It could be useful in the development phase
having the possibility to store the processed files created at the end of each training steps
so that we can re-use them for next steps, without re-running the previous


This is my case  for instance:
I need to create different staticLM (step ‘static_lm’) with different settings
but I do not need to re-preprocess all data

So I propose to have
- a flag to enable/disable the output of each step; the current '--debug' could be fine
- two parameters to setting the initial and final steps of the training process, we want to actually perform
- a way to check whether all data/models required to run a given step are available; if yes run that step, if not stop with a description of the error


Just to inform that on a m4.4xlarge instance of AWS
the preprocessing step took   1736 seconds (~1/2 hour)
on the full “benchmark-1.0”.

**Comment by memoday** [comment]
Hi Davide,

Sorry to jump in. Is the resume option available in the latest build? I was training a huge corpora "UN" and for some reason, I lost internet connection to the server. Can I resume from where it stopped? When I type:

`./mmt status`

I get the following message:

> No engine could be found.
> You can create a new engine with the ./mmt create command.

It stopped at phase (4 of 7). Here is what I see in the terminal.

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ar

INFO: (1 of 7) TMs clean-up...                                         DONE (in 4m 17s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 27m 41s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 2m 5s)
INFO: (4 of 7) Aligner training...

Does this mean that I have to recreate it from scratch? Is there a command that can make the engine creation process running permanently on the server if I lost connection on the terminal on my laptop? Most importantly, do we have resume option available? I assume not since this issue is still open, but I thought I just double check. Please let me know.

Thanks in advance for your support.

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @memoday,

We currently don't have a "resume" command, but we are working to add that feature to the next MMT release.

As for the command to run the engine creation process permanently on the server, i suggest you to use
```
nohup ./mmt create <your_params> &
```
and **press Enter twice** to start the command. 

This way you can run a command or script in background, without need to keep an active connection with the remote machine. The command stdout is redirected to a nohup.out file that is automatically created if not existing.

I suggest you that, after starting the program, you try to execute ```tail -f nohup.out```, so you can check if the program has actually started and is writing some messages in the nohup file. 

Let me know if this works :)

Andrea

**Comment by memoday** [comment]
Thanks a million, Andrea, for the great tip. I appreciate it. I look forward to the resume feature in the next release.

**Comment by AndRossi** [comment]
Hi everyone, 

The resume option is now available.

After trying to create an engine with the usual command:  
```./mmt create <src_lang> <trg_lang> <parallel_corpora_path> -e <engine_name>```
if the engine creation was not successful you don't have to re-launch it from scratch anymore: you can just resume the previous attempt and skip all the steps that were performed successfully.

The resume option syntax is:
```./mmt create <src_lang> <trg_lang> <parallel_corpora_path> -e <engine_name> --resume```

so you just have to pass the same params you used for the failed creation attempt and add the --resume option.

If no creation attempt was performed, the command will behave exactly as the basic create.

I hope this feature lets you save time and avoid some frustration!

**Comment by AndRossi** [comment]
I'm closing the issue now, feel free to re-open it if something goes wrong.
