### ISSUE TITLE
nbest in server outputs

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#59]
the nbest are put on stdout regardless the verbosity value.

**Comment by davidecaroselli** [comment]
I solved this issue on branch direct-server. I've removed the line:

`manager.OutputNBest(cout, nBestList);`

There's no need to output all the nbest list anymore, because these results are going to be passed programmatically to the upper layers, instead outputting them on standard output.

**Comment by nicolabertoldi** [comment]
I will check if this change do not cause any problem in the xmlrpc server version

If ok, I will commit the change in mmt-dev as well.

Does anyone have objections?


Nicola

**Comment by davidecaroselli** [comment]
This change has been made on code that replaces XMLRPC, so there 's no backward compatibility issue. If you want to look at the code, it's available here: https://github.com/ModernMT/MMT/tree/direct-server/src/Decoder/native

**Comment by davidecaroselli** [comment]
Update @nicolabertoldi : I decided to skip for now the new server implementation  in branch direct-server because it's becoming too expensive in terms of time and effort.

Anyway, you could apply the same fix to the XMLRPC server here: https://github.com/ModernMT/mosesdecoder/blob/mmt-dev/moses/server/TranslationRequest.cpp#L220

I'm going to close this issue for now because it is actually a Moses issue, not MMT.
Please let me know if you have any questions.
