### ISSUE TITLE
mosesdecoder be git submodule to MMT

### ISSUE THREAD

**Issue by ugermann** [ModernMT/MMT#68]
.. so that developers don't need to figure out which version of one plays nicely with which version of the other.

**Comment by davidecaroselli** [comment]
Hi Uli,
you're right, even IRSTLM should be a submodule. The reason why this has not been done is that, during the next CoDev in Trento, one of the goals is to unify all the source code of MMT inside one repo (MMT).

While what you're saying is correct, we accepted this little friction between the two/three projects because is really a temporary state, and we're going to solve it really soon.

I close this issue for now, if you have any other questions please feel free to reopen it.
