### ISSUE TITLE
Testing - Generalize Testing

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#78]
I reviewed the Test.md in the testing branch.

Before writing my recommendation I would like to ask some questions that I had as a user at first glance:

- I want to write a test in python to test the integration of the full chain. 
create engine, start, translate, evaluate, stop with a fixed dataset. I don't understand  how to do it. Can you please change the documentation so that it is more clear how to do it and that I am pushed to do it? 

- I have seen that there is a test for CA, how do I know what the test does?

- I want to test the precision of the CA on my 100 domains. How can I do it?

**Comment by marcotrombetti** [comment]
After a few discussion (Marcello, Marco, Luca, Davide) we decided to assign this to a future sprint.

Adding @cattoni to the discussion.

**Comment by luca-mastrostefano** [comment]
> I want to write a test in python to test the integration of the full chain. 
create engine, start, translate, evaluate, stop with a fixed dataset. I don't understand how to do it. Can you please change the documentation so that it is more clear how to do it and that I am pushed to do it?

I have changed the documentation in order to better explain the new test infrastructure.
It is located here: [TEST.md](https://github.com/ModernMT/MMT/blob/develop/TEST.md)
Can you please read it now and provide some feedback? Thank you.

> I have seen that there is a test for CA, how do I know what the test does?

You can read detailed description of each test inside the file 'info.json' located under
`ModernMT/test/tests/<TEST_NAME>/`

In your case it is located at 
`ModernMT/test/tests/context_analyzer_precision_and_recall_test/info.json`

It reports the following information:

> It creates an engine named 'context_analyzer_test_engine' with the training data and binds it on a free random port.
The only steps done during the creation of the engine are 'preprocess' and 'context_analyzer'. 
When the context analyzer is ready, it reads portion of text from the testset and queries the context analyzer in order to compute the precision and the recall of the system.
When the test ends, it stops the engine and outputs the results. 

> It computes: 
- Precision: number of times that the right domain is in first position divided by the total number of queries. 
- Recall: number of times that the right domain appears in the results divided by the total number of queries. 
- Average position: the sum of the positions in which the right domain appears (first position is 1) divided by the number of queries in which it appears in the results.
- Average score gap: the sum of the gap between the score of the right domain and the domain next in the results divided by the number of queries in which it appears in the results.
- Average query time [s]: the average query time in seconds.

Soon a command will be added to the run_tests.py script in order to read the description without opening the info.json

> I want to test the precision of the CA on my 100 domains. How can I do it?

If you want to run a test with a custom input you can move under its folder with:
`cd ModernMT/test/tests/<TEST_NAME>/`

And launch:
`./launch.sh -h`

To launch the context analyzer on your data, move under its directory with:
`cd ModernMT/test/tests/context_analyzer_precision_and_recall_test/`

and launch it with:
`./launch.sh --training-dir <path_to_training_dir> --test-dir <path_to_test_dir> -l <lang_code>`
