### ISSUE TITLE
Evaluate - Performance and Threads

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#93]
On a 36 cores machine (c4.8xlarge) I cannot get more than 50% of CPU used during evaluate. (1500%)
I tried different parameters in 

scripts/evaluation.py
```
pool = multithread.Pool(multiprocessing.cpu_count() * 2)
```

**Comment by davidecaroselli** [comment]
This problem seems to appear also in during Tuning. It seems that MMT won't use more than 16 cores no matter what it's written in configuration files.

I'll run some tests today and I will report results asap.

**Comment by mfederico** [comment]
Before digging into this, why not writing two lines to Hieu asking if this is a limitation of Moses?

**Comment by davidecaroselli** [comment]
The first test I'm going to do is try to translate directly with our version of Moses. If I have the same limit, than I can assume that is a Moses-side problem, otherwise it is a more MMT-side problem.

This test should take me really few minutes, so if the results will confirm that is a "Moses-side" problem, I agree we can send Hieu an email.

**Comment by bhaddow** [comment]
You might be interested in this long discussion on the scalability of Moses
https://github.com/moses-smt/mosesdecoder/issues/39

The bottom line is that there have been improvements (I think!) since 
Matt made those graphs, but it's hard to eradicate all locking, 
especially as some is buried in the C++ standard libraries.


On 07/03/16 10:42, Davide Caroselli wrote:
>
> The first test I'm going to do is try to translate directly with our 
> version of Moses. If I have the same limit, than I can assume that is 
> a Moses-side problem, otherwise it is a more MMT-side problem.
>
> This test should take me really few minutes, so if the results will 
> confirm that is a "Moses-side" problem, I agree we can send Hieu an email.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ModernMT/MMT/issues/93#issuecomment-193199858>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ugermann** [comment]
This is a known bottleneck in moses due to some global locking in the
current version of Moses. The quick fix is to use multiple moses instances
and distribute the load among them.

- Uli

On Mon, Mar 7, 2016 at 11:25 AM, Barry Haddow <notifications@github.com>
wrote:

> You might be interested in this long discussion on the scalability of Moses
> https://github.com/moses-smt/mosesdecoder/issues/39
>
> The bottom line is that there have been improvements (I think!) since
> Matt made those graphs, but it's hard to eradicate all locking,
> especially as some is buried in the C++ standard libraries.
>
>
> On 07/03/16 10:42, Davide Caroselli wrote:
> >
> > The first test I'm going to do is try to translate directly with our
> > version of Moses. If I have the same limit, than I can assume that is
> > a Moses-side problem, otherwise it is a more MMT-side problem.
> >
> > This test should take me really few minutes, so if the results will
> > confirm that is a "Moses-side" problem, I agree we can send Hieu an
> email.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ModernMT/MMT/issues/93#issuecomment-193199858>.
> >
>
>
> The University of Edinburgh is a charitable body, registered in
> Scotland, with registration number SC005336.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernMT/MMT/issues/93#issuecomment-193212923>.
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by marcotrombetti** [comment]
Got it. 

Davide solved some issues on the MMT side and we are limited to 16 cores per machines from the moses side.

From a product standpoint this is more than acceptable for now. So I moved this a production oriented release.

**Comment by hieuhoang** [comment]
working on it, all will be revealed soon.

**Comment by davidecaroselli** [comment]
hi @hieuhoang are you referring to regular Moses, or a different version? (Moses 2 maybe? :) )

**Comment by hieuhoang** [comment]
You know more than most ;) Need to get paper accepted somewhere before officially revealing anymore
